//
// Localization strings for TTDPatch.
//
// Czech translation by Miroslav Duda.
//

//-------------------------------------------
//  INFO ABOUT THIS LANGUAGE
//-------------------------------------------
SETNAME("Czech")
SETCODE("cz")
COUNTRYARRAY(countries) = { 421, 42, 0, 0x05, 0 };
SETARRAY(countries);
	// 421 is the Czech Republic (42 is Czechoslovakia in old DOS versions),
	// and 0x05 is Czech in Windows

DOSCODEPAGE(852)	// The default DOS code page for this language
WINCODEPAGE(1250)	// The default Windows code page for this language
EDITORCODEPAGE(852)	// The code page of all strings in this file.

DOSENCODING(IBM852)	// Encoding type for XML output from DOS and Windows;
WINENCODING(ISO-8859-2)	// DOS MUST be from IANA-CHARSETS and same as DOSCODEPAGE
			// Windows can be any ISO-8859-x encoding, doesn't have
			// to be related to WINCODEPAGE

//-------------------------------------------
//  PROGRAM BLURBS
//-------------------------------------------

// First line of output is something like "TTDPatch V1.5.1 starting.\n"
// The program name and version are autogenerated, only put the " starting\n"
// here
SETTEXT(LANG_STARTING, " byl spuçtØn.\n")


//-------------------------------------------
//  VERSION CHECKING
//-------------------------------------------

// In the version identifier, this is for the file size
SETTEXT(LANG_SIZE, "velikost")

// Shown if the version is recognized
SETTEXT(LANG_KNOWNVERSION, "Verze programu je spr vn \n")

// Warning if the version isn't recognized.  Be sure *not* to use tabs
// in the text.  All but the last lines should end in ...\n"
SETTEXT(LANG_WRONGVERSION, "\n"
	"POZOR!   Nezn m  verze programu. M…§ete se pokusit\n"
	"         jej i pýesto spustit a zjistit potýebn‚ informace, pokud\n"
	"         se to nepovede, TTD nahl s¡ chybu ochrany a bude ukonŸen.\n"
	"\n"
	"         V z vislosti na schopnostech operaŸn¡ho syst‚mu nakl dat s GPF, se m…§e\n"
	"         poŸ¡taŸ zablokovat a vy pýij¡t o data. Pro v¡ce informac¡ si pýeŸtØte Ÿ st\n"
	"        \"Version Trouble\" v TTDPatch manualu.\n"
	"\n"
	"OdpovØzte 'a' jen pokud opravdu v¡te, co dØl te. BYL JSTE VAROVµN!\n"
	"Chcete i pýesto TTD spustit? ")

// Keys which continue loading after the above warning. *MUST* be lower case.
// can be several different keys, e.g. one for your language "yjo"
SETTEXT(LANG_YESKEYS, "ay")

// Answering anything but the above keys gives this message.
SETTEXT(LANG_ABORTLOAD, "Nahr v n¡ programu bylo zastaveno.\n")

// otherwise continue loading
SETTEXT(LANG_CONTINUELOAD, "Pokus¡m se...\n")

// Warning if '-y' was used and the version is unknown
SETTEXT(LANG_WARNVERSION, "POZOR: Nezn m  verze!\n")


// -------------------------------------------
//    CREATING AND PATCHING TTDLOAD
// -------------------------------------------

// TTDLOAD.OVL doesn't exist
SETTEXT(LANG_OVLNOTFOUND, " nenalezen, hled m origin ln¡ soubory:\n")

// neither do the original files (two %s are two filenames)
SETTEXT(LANG_NOFILESFOUND, "Nemohu nal‚zt ani %s ani %s.\n")

// default Windows language executable (american/english/french/german/spanish).exe
SETTEXT(LANG_WINDEFLANGEXE, "AMERICAN.EXE");

// Shown when copying tycoon.exe or ttdx.exe (first %s) to ttdload.ovl (2nd %s)
SETTEXT(LANG_SHOWCOPYING, "Kop¡ruji %s do %s")

// Error if running the copy command fails.  %s is the command.
SETTEXT(LANG_COPYERROR_RUN, "Nelze spustit %s\n")

// Error if command returned successfully, but nothing was copied.
// %s=TTDLOAD.OVL
SETTEXT(LANG_COPYERROR_NOEXIST, "Chyba kop¡rov n¡ - soubor %s neexistuje.\n")

// Invalid .EXE format
SETTEXT(LANG_INVALIDEXE, "Nezjistitelnì .EXE form t.\n")

// Version could not be determined
SETTEXT(LANG_VERSIONUNCONFIRMED, "Nelze zjistit verzi programu.\n")

// Shows program name (1st %s) and version (2nd %s)
SETTEXT(LANG_PROGANDVER, "N zev programu:\n  %s\nVerze programu: %s\n")

// More than three numbers in the version string (not #.#.#)
SETTEXT(LANG_TOOMANYNUMBERS, "Verze obsahuje pý¡liç mnoho Ÿ¡sel!\n")

// .EXE is not TTD
SETTEXT(LANG_WRONGPROGRAM, "Toto nen¡ Transport Tycoon Deluxe.\n")

// Displays the parsed version number
SETTEXT(LANG_PARSEDVERSION, "Parsed verze je %s\n")

// The exe has been determined to be the DOS extended executable
SETTEXT(LANG_ISDOSEXTEXE, "Spustiteln‚ v DOSu.\n")

// The exe has been determined to be the Windows executable
SETTEXT(LANG_ISWINDOWSEXE, "Spustiteln‚ ve Windows.\n")

// The exe is of an unknown type
SETTEXT(LANG_ISUNKNOWNEXE, "Nezn mì spouçtØc¡ form t.\n")

// The exe is the wrong one for this TTDPatch, i.e. DOS/Windows mixed up. %s=DOS or Windows
SETTEXT(LANG_NOTSUPPORTED, "Promiåte, tato verze TTDPatch spolupracuje jen s %s verz¡.\n")

// If the original .exe segment length (%lx) is too large or too small
SETTEXT(LANG_INVALIDSEGMENTLEN, "æpatn  p…vodn¡ d‚lka segment… %lx")

// When increasing the segment length
SETTEXT(LANG_INCREASECODELENGTH, "Nastavuji velikost programu na %s MB.\n")

// Can't write to TTDLOAD.OVL (%s) [or TTDLOADW.OVL for the Windows version]
SETTEXT(LANG_WRITEERROR, "Nelze zapisovat do %s, je nastaven jen ke Ÿten¡\n")

// Installing the code loeader
SETTEXT(LANG_INSTALLLOADER, "Instaluji code loader.\n")

// TTDLOAD.OVL (%s) is invalid, needs to be deleted.
SETTEXT(LANG_TTDLOADINVALID, "Nemohu instalovat code loader")
SETTEXT(LANG_DELETEOVL, " - Zkuste vymazat %s.\n")

// TTDLOAD.OVL was verified to be correct
SETTEXT(LANG_TTDLOADOK, "%s je v poý dku.\n")

// Waiting for key before terminating TTDPatch after an error occured
SETTEXT(LANG_PRESSANYKEY, "Pro pýeruçen¡ stisknØte kl vesu.")

// Displayed on various warning conditions: Esc to exit, any other key to continue
SETTEXT(LANG_PRESSESCTOEXIT, "Stiskni kl vesu pro pokraŸov n¡ nebo Escape pro pýeruçen¡.")

// Loading custom in-game texts
SETTEXT(LANG_LOADCUSTOMTEXTS, "Nahr v m obvykl‚ hern¡ texty.\n")

// ttdpttxt.dat is not in a valid format
SETTEXT(LANG_CUSTOMTXTINVALID, "¬ten¡ %s: Chybnì form t souboru.\n")


//-----------------------------------------------
//   COMMAND LINE HELP (-h)
//-----------------------------------------------

// Introduction, prefixed with "TTDPATCH V<version> - "
SETTEXT(LANG_COMMANDLINEHELP, "Uprav¡ TTD a spust¡ patchovac¡ program %s\n"
	  "\n"
	  "Pou§it¡: TTDPATCH [-C cfg-soubor] [volby] [cesta k CD] [-W cfg-soubor]\n"
	  "\n")

// Lines of help for all on/off switches(volby), each at most 38 chars long.
// If you need more chars just insert another line.
TEXTARRAY(halflines,) =
	{ "-a: Vçechny volby kromØ -x",
	  "-d: V§dy uk zat cel‚ datum",
	  "-f: Refitov n¡ vlak…",
	  "-g: Oprava glob ln¡ch chyb",
	  "-k: Mal‚ letiçtØ v§dy",
	  "-l: Vlakov‚ n dra§¡ a§ 7x7",
	  "-n: Novì non-stop",
	  "-q: Vylepçen‚ nakl d n¡/vykl d n¡",
	  "-s: Povolen¡ cheat…",
	  "-u: Zlepçen¡ multiplayeru",
	  "-v: Zobrazen¡ aktivn¡ volby",
	  "-w: Presign ly automaticky",
	  "-y: PýeskoŸit hl çen¡ nezn m‚ verze",
	  "-z: Dlouh‚ vlaky (126 voz…)",

	  "-B: Dlouh‚ mosty",
	  "-D: Super-dynamit",
	  "-E: Pýesunout Ÿerven‚ hl çen¡",
	  "-F: Full load alespoå jednoho typu",
	  "-G: VìbØr n kladu ve stanici",
	  "-H: Upravit pýedmost¡",
	  "-I: Vypnout inflaci",
	  "-J: V¡ce letiçœ ve mØstØ",
	  "-L: P…jŸit/splatit max. s 'Ctrl'",
	  "-N: Rozç¡ýen‚ News",
	  "-O: Office Tower akceptuj¡ food",
	  "-P: Aktivace starìch vozidel",
	  "-R: Auta Ÿekaj¡c¡ ve frontØ",
	  "-S: Nov‚ modely lod¡",
	  "-T: Nov‚ modely vlak…",

	  "-2: Kompatibilita pro Windows 2000/XP",

	  "-Xb: éplatky v menu Local Autority",
	  "-Xd: Pýid n¡ depa do pý¡kazu GOTO",
	  "-Xe: NekoneŸn  hra po roce 2070",
	  "-Xf: Zefektivn¡ kooperuj¡c¡ vozidla",
	  "-Xg: Postupn‚ nakl d n¡/vykl d n¡",
	  "-Xh: Nov‚ domy ve mØstØ",
	  "-Xi: Zabr n¡ krachov n¡ pr…myslu",
	  "-Xl: Stavba pr…plav… a zdymadel",
	  "-Xm: Volba Load v menu",
	  "-Xo: Cheaty za pen¡ze",
	  "-Xp: Novì zp…sob vìpoŸtu vìkonnosti",
	  "-Xr: V§dy vytvoýit TTDLOAD.OVL",
	  "-Xs: Zobrazen¡ rychlosti",
	  "-Xw: Nastaven¡ presign l…",
	  "-Xx: Ukl d  a nahr v  dalç¡ data",

	  "-XA: Nucen  obnova vozidel s -Xa",
	  "-XB: Stavba pýi zapauzovan‚ hýe",
	  "-XE: Electrifikovan‚ tratØ",
	  "-XF: Nastavit experimentaln¡ volby",
	  "-XH: Ulo§it a zobrazit historii zpr v",
	  "-XI: Umo§nit path based signall.(PBS)",
	  "-XL: Zobrazit zisk v pýehledu vozidel",
	  "-XO: Umo§nit kop¡rov n¡ j¡zdn¡ch ý d…",
	  "-XP: Nov‚ modely letadel",
	  "-XR: Nov‚ modely aut",
	  "-XS: Ovl d n¡ PC soupeýe",
	  "-XZ: Verze s malou pamØt¡ (3.5MB)",

	  "-Ya: Ratingy tolerant. ke vØku vozidel",
	  "-Yb: StavØn¡ na svahu",
	  "-Yc: R…zn‚ ceny za r…zn‚ typy trat¡",
	  "-Yd: Nov‚ mosty",
	  "-Yg: Mo§nost zmØnit rychlost hry",
	  "-Yh: Umo§nit vyçç¡ mosty",
	  "-Ym: Umo§nit manu ln¡ zmØnu trat¡",
	  "-Yn: Umo§nit novou grafiku stanic",
	  "-Ys: Semafor na stranØ, kde jezd¡ auta",
	  "-Yt: Uk §at v¡ce info v oknØ mØst",
	  "-Yw: Rychlì prodej vagon…",

	  "-YC: StavØn¡ na pobýe§¡",
	  "-YD: Rozç¡ýen‚ nasataven¡ obt¡§nosti",
	  "-YF: Umo§nit FIFO nakl d n¡",
	  "-YH: V¡ce/nov‚ hotkeys",
	  "-YL: Omezit rychlost vlakovìch vagon…",
	  "-YN: Umo§nit nov‚ sch‚ma jmen mØst",
	  "-YP: Letadla se skuteŸnou rychlost¡",
	  "-YS: Star‚ semafory pýed rokem 1975",

	  NULL
	};
SETARRAY(halflines);

// Text describing the switches with values.  The lines have to be shorter
// than 79 chars, excluding the "\n".  Start new lines if necessary.
SETTEXT(LANG_FULLSWITCHES, "\n"
	  "-e #:    Umo§nit rozlehlejç¡ zast vky\n"
	  "-i #:    Nastaven¡ servisn¡ho intervalu ve dnech\n"
	  "-x #:    Rozç¡ýit vehicle array na 850*#. Dalç¡ informace v manu lu!\n"
	  "-mc #:   Zvìçit rychlost vlak… v kopc¡ch a zat Ÿk ch\n"
	  "-trpb #: Zvìçit poŸet vlak…, aut, letadel a lod¡\n"
	  "-M #:    Umo§nit v¡cemaçinovìm vlak…m nastavit zvìçen¡ rychlosti v %%.\n"
	  "-U #:    Pro stavbu tratØ umo§nit pou§¡t stejn‚ grafick‚ rozhran¡,\n"
	  "jako m  Locomotion. Hodnota 1 zapne nov‚ GUI bez Ctrl.\n"
	  "-Xa #:   Automatick  obnova vozidel # mØs¡ce pýed ukonŸen¡m jejich §ivotnosti\n"
	  "-Xc #:   Sn¡§¡ pravdØpodobnost hav rie letadla\n"
	  "-Yr #:   ZmØn¡ auto-vlakov‚ kolize na danì typ (1/2)\n"
	  "-Xt #:   Nastav¡ maxim ln¡ velikost mØst\n"
	  "-Xv #:   Uspoý d  seznam vozidel a nastav¡ interval mezi jeho aktualizacemi\n"
	  "-Xz #:   Vz jemnØ pýichyt v  okna\n"
	  "-XC #:   Umo§n¡ v¡ce mØn a nastav¡ jejich volby\n"
	  "-XD #:   Vybere, kter‚ katastrofy se mohou pýihodit\n"
	  "-XN #:   Po zadan‚m roce jsou noviny v TTD barevn‚\n"
	  "-XM #:   Umo§n¡ kombinovat monorail a maglev\n"
	  "-XT #:   Nastav¡ kolik mØst bude r…st rychleji a v¡ce\n"
	  "-XX #:   Rychlost na mostech u monorail a maglev v procentech z max.rychlosti\n"
	  "-XY #:   Nastav¡ startovn¡ rok pro novou hru\n"
	  "-XW #:   Rozt hne okno TTD na tento rozmØr v pixelech (pouze Windows verze)\n"
	  "-X1 #, -X2 #: Max. Ÿas Ÿek n¡ vlaku pýed jednosmØrnìmi resp. obousmØrnìmi semafory\n"
	  "-Yf #:   \"ZvØtç¡\" n kladn¡ vlaky danìm koeficientem\n"
	  "-Yl #:   Pýid  podporu koleŸka myçi a nastav¡ mo§nosti (pouze Windows verze)\n"
	  "-Yo #:   Ovl d n¡ dalç¡ch voleb (viz. dokumentace)\n"
	  "-Yp #:   Umo§n¡ s zen¡ v¡ce strom… najednou\n"
	  "-YA #:   Nepou§¡van‚ silnice ztrat¡ sv‚ho vlastn¡ka, re§im z vis¡ na parametru\n"
	  "-YB #:   V¡ce stavØc¡ch voleb, ovl d n¡ s parametrem\n"
	  "-YE #:   Nastav¡ Ÿas v sec. jak dlouho bude zobrazeno Ÿerven‚ hl çen¡\n"
	  "-YM #:   Zobraz¡ v¡ce (nebo m‚nØ) oblak… p ry, hodnota nastavuje mno§stv¡\n"
	  "-YG #:   Rozç¡ý¡ u§ivatelskì interface, vìbØr volby s parametrem\n"
	  "-YO #:   Povol¡ hranici snØhu v m¡rn‚m podneb¡ a nastav¡ jej¡ vìçku\n"
	  "-YR #:   Nastav¡ frekvenci obnovy mapy po # kroc¡ch\n"
	  "-YT #:   Nastav¡ algoritmus r…stu mØst\n"
	  "-YW #:   Nastav¡ maxim ln¡ poŸet otevýenìch oken\n"
	  "\n"
	  "-C cfg-file:  Spust¡ TTDPatch s t¡mto cfg souborem m¡sto ttdpatch.cfg\n"
	  "-W cfg-file:  Vytvoý¡ cfg soubor se souŸasnou konfigurac¡\n"
	  "-Xn cfgfile:  Pou§ije tento soubor jako konfiguraci pro novou grafiku\n"
	  "\n"
	  "Pozor na psan¡ velkìch a malìch p¡smen!\n"
	  "\n"
	  "Pý¡klad:  ttdpatch -fnqz -m 00 -c 13 -trpb 240 -FG -A 2 -v\n"
	  "\n"
	  "(Hint:  Jestli§e vçechno scrolovalo velmi rychle, vlo§te \"ttdpatch -h|more\")\n"
	  "\n")

// Referral to the docs, prefixed by "Copyright (C) 1999 by Josef Drexler.  "
SETTEXT(LANG_HELPTRAILER, "V¡ce informac¡ naleznete v TTDPATCH.TXT.\n")


//-----------------------------------------------
//  COMMAND LINE AND CONFIG FILE PARSING
//-----------------------------------------------

// if an on/off switch has a value other than the above (%s = wrong value)
SETTEXT(LANG_UNKNOWNSTATE, "Pozor: Nezn mì parametr %s, nastaveno na off.\n")

// switch is unknown.  %c is '-' or '/' etc, %s is the switch char
SETTEXT(LANG_UNKNOWNSWITCH, "Nezn mì parametr '%c%s'. Pou§ijte -h pro pomoc.\n")

// switch bit name is unknown.  First %s is bit name, 2nd is switch name
SETTEXT(LANG_UNKNOWNSWITCHBIT, "Nezn m  hodnota '%s' volby '%s'.\n")

// cfg command %s is unknown
SETTEXT(LANG_UNKNOWNCFGLINE, "Pozor: Chybnì pý¡kaz v cfg souboru '%s'.\n")

// Names of the switches for the '-v' options
// First string is shown always, second only if set and with the given
// value of the switch in %d.
// These lines (both parts) are limited to 36 chars, also consider how large
// the expansion of the %d can be for that switch.
SWITCHTEXT(uselargerarray, "Rozç¡ýen¡ poŸtu vozidel", " na %d*850")
SWITCHTEXT(usenewcurves, "Rychlosti v zat Ÿk ch", " k¢d %04x")
SWITCHTEXT(usenewmountain, "Rychlosti na svahu", " k¢d %04x")
SWITCHTEXT(usenewnonstop, "Odliçnì NON-STOP", "")
SWITCHTEXT(increasetraincount, "Max. poŸet vlak…", ": %d")
SWITCHTEXT(increaservcount, "Max. poŸet aut", ": %d")
SWITCHTEXT(setnewservinterval, "Servisn¡ interval", ": %d dn…")
SWITCHTEXT(usesigncheat, "Pou§it¡ cheat…", "")
SWITCHTEXT(allowtrainrefit, "Povoleno refitov n¡ vlak…", "")
SWITCHTEXT(increaseplanecount, "Max. poŸet letadel", ": %d")
SWITCHTEXT(increaseshipcount, "Max. poŸet lod¡", ": %d")
SWITCHTEXT(keepsmallairports, "V§dy stavØt mal  letiçtØ", "")
SWITCHTEXT(largerstations, "Kombinovan‚ stanice", " do %d Ÿtverc…")
SWITCHTEXT(morestationtracks, "Vlakov‚ n dra§¡ a§ 7x7", "")
SWITCHTEXT(longerbridges, "Dlouh‚ mosty", "")
SWITCHTEXT(improvedloadtimes, "Vylepçen‚ nakl d n¡/vykl d.", "")
SWITCHTEXT(mammothtrains, "Mamut¡ vlaky (max.d‚lka 126)", "")
SWITCHTEXT(presignals, "Super-semafory automaticky", "")
SWITCHTEXT(officefood, "Office Tower akceptuj¡ j¡dlo", "")
SWITCHTEXT(noinflation, "Vypnut  inflace", "")
SWITCHTEXT(maxloanwithctrl, "P…jŸit/splatit max. s 'Ctrl'", "")
SWITCHTEXT(persistentengines, "Aktivace starìch vozidel", "")
SWITCHTEXT(fullloadany, "Full load alespoå jednoho typu", "")
SWITCHTEXT(selectstationgoods, "VìbØr n kladu ve stanici", " pro %d dn…")
SWITCHTEXT(morethingsremovable, "V¡ce vØc¡ lze obnovit", "")
SWITCHTEXT(multihead, "V¡cemaçinov‚ vlaky", "rychlost: %d%%")
SWITCHTEXT(newlineup, "Auta Ÿekaj¡c¡ ve frontØ", "")
SWITCHTEXT(lowmemory, "N¡zkopamØœov  verze (3.5MB)", "")
SWITCHTEXT(generalfixes, "Obecn‚ opravy (viz. manu l)", "")
SWITCHTEXT(moreairports, "V¡ce letiçœ v jednom mØstØ", "")
SWITCHTEXT(bribe, "éplatky v menu Local Autority", "")
SWITCHTEXT(noplanecrashes, "Hav rie letadel", " k¢d %d")
SWITCHTEXT(showspeed, "Zobrazen  rychlost vozidel", "")
SWITCHTEXT(autorenew, "Auto-obnova vozidel", " od %d mØs¡c…")
SWITCHTEXT(cheatscost, "Cheaty za pen¡ze", "")
SWITCHTEXT(extpresignals, "Nastaven¡ presign l…", "")
SWITCHTEXT(diskmenu, "Volba Load v menu", "")
SWITCHTEXT(win2k, "NØkter‚ opravy pro Windows 2000/XP", "")
SWITCHTEXT(feederservice, "Pomocn  vozidla maj¡ zisk", "")
SWITCHTEXT(gotodepot, "Pýid n¡ dep do pý¡kazu GOTO", "")
SWITCHTEXT(newships, "Nov‚ modely lod¡", "")
SWITCHTEXT(subsidiaries, "Ovl d n¡ soupeý…", "")
SWITCHTEXT(gradualloading, "Postupn‚ nakl d n¡/vykl d.", "")
SWITCHTEXT(moveerrorpopup, "Pýesunuto Ÿerven‚ hl çen¡", "")
SWITCHTEXT(setsignal1waittime, "Novì Ÿekac¡ Ÿas pýed semafory", ":")
SWITCHTEXT(setsignal2waittime, "", "")				// dummy entry
SWITCHTEXT(maskdisasters, "Katastrofy", " k¢d %d")
SWITCHTEXT(forceautorenew, "Nucen  obnova vozidel", "")
SWITCHTEXT(morenews, "Rozç¡ýen‚ News", "")
SWITCHTEXT(unifiedmaglev, "Sjednocen‚ maglev", " k¢d %d")
SWITCHTEXT(newbridgespeeds, "Max rychlost na mostech", " k¢d %d%%")
SWITCHTEXT(eternalgame, "NekoneŸn  hra po roce 2070", "")
SWITCHTEXT(showfulldate, "V§dy zobrazeno cel‚ datum", "")
SWITCHTEXT(newtrains, "Nov‚ modely vlak…", "")
SWITCHTEXT(newrvs, "Nov‚ modely aut", "")
SWITCHTEXT(newplanes, "Nov‚ modely letadel", "")
SWITCHTEXT(signalsontrafficside, "Semafory vlevo-vpravo podle aut", "")
SWITCHTEXT(electrifiedrail, "Elektrifikovan‚ tratØ", "")
SWITCHTEXT(newstartyear, "Startovn¡ rok", ": %d")
SWITCHTEXT(newerrorpopuptime, "Trv n¡ Ÿerven‚ho hl çen¡", ": %d s")
SWITCHTEXT(newtowngrowthfactor, "Faktor r…stu mØst", " k¢d %d")
SWITCHTEXT(largertowns, "VØtç¡ mØsta", ", ka§d‚ 1 z %d")
SWITCHTEXT(miscmods, "Mnohostrann‚ m¢dy", " k¢d %ld")
SWITCHTEXT(loadallgraphics, "Nahr t ka§dì soubor nov‚ grafiky", "")
SWITCHTEXT(saveoptdata, "Ulo§en¡ a nahr t¡ rozç¡ýenìch dat", "")
SWITCHTEXT(morebuildoptions, "Rozç¡ýen‚ stavØn¡", " k¢d %d")
SWITCHTEXT(semaphoresignals, "Star‚ semafory pýed rokem 1975", "")
SWITCHTEXT(morehotkeys, "V¡ce voleb ovl danìch kl vesami", "")
SWITCHTEXT(plantmanytrees, "S zen¡ v¡ce strom… najednou", ", k¢d %d")
SWITCHTEXT(morecurrencies, "V¡ce mØn", ", k¢d %d")
SWITCHTEXT(manualconvert, "Manu ln¡ zmØna trat¡", "")
SWITCHTEXT(newtowngrowthrate, "Algoritmus r…stu mØst", " k¢d %d")
SWITCHTEXT(displmoretownstats, "V¡ce statistik v oknØ mØst", "")
SWITCHTEXT(enhancegui, "Rozç¡ýenì hern¡ interface", "")
SWITCHTEXT(newagerating, "Rating tolerantnØjç¡ ke vØku vozidel", "")
SWITCHTEXT(buildonslopes, "StavØn¡ na svahu", "")
SWITCHTEXT(buildoncoasts, "StavØn¡ na pobýe§¡ bez dynamitu", "")
SWITCHTEXT(experimentalfeatures, "Posledn¡ experiment ln¡ mo§nosti", ": %u")
SWITCHTEXT(tracktypecostdiff, "R…zn‚ ceny za r…zn‚ typy trat¡", "")
SWITCHTEXT(planespeed, "Re ln  rychlost letadel", ": %d/4")
SWITCHTEXT(fastwagonsell, "Rychlejç¡ prodej vagon…", "")
SWITCHTEXT(newrvcrash, "Auto-vlakov‚ kolize"," k¢d %d")
SWITCHTEXT(stableindustry, "Pr…mysl nekrachuje pýi stabl. ekonom","")
SWITCHTEXT(newperformance, "Nov‚ hodnocen¡ vìkonnosti", "")
SWITCHTEXT(sortvehlist, "Tý¡dit seznam vozidel", ", refresh po: %d")
SWITCHTEXT(showprofitinlist, "Zobrazuje zisk v seznamu vozidel", "")
SWITCHTEXT(newspapercolour, "Noviny jsou barevn‚", " po roce %d")
SWITCHTEXT(sharedorders, "Umo§nit kop¡rov n¡ j¡zdn¡ch ý d…", "")
SWITCHTEXT(moresteam, "Zobrazit v¡ce oblak… p ry", ": %x")
SWITCHTEXT(abandonedroads, "Nepou§¡van‚ silnice ztrat¡ vlastn¡ka", ", re§im %d")
SWITCHTEXT(newstations, "Umo§nit novou grafiku stanic", "")
SWITCHTEXT(buildwhilepaused, "Umo§nit stavØt pýi zapauzovan‚ hýe", "")
SWITCHTEXT(losttrains, "Varov n¡ o ztracen‚m vlaku", " po %d dnech")
SWITCHTEXT(lostrvs, "Varov n¡ o ztracen‚m automobilu", " po %d dnech")
SWITCHTEXT(lostships, "Varov n¡ o ztracen‚ lodi", " po %d dnech")
SWITCHTEXT(lostaircraft, "Varov n¡ o ztracen‚m letadle", " po %d dnech")
SWITCHTEXT(maprefresh, "Obnovov n¡ mapy po", ": %d kroc¡ch")
SWITCHTEXT(disconnectontimeout, "Opdojit hru po s¡ti,je-li bez odezvy", " po %d sec.")
SWITCHTEXT(moretoylandfeatures, "Umo§nit n hodn‚ procesy v toylandu", ": %d")
SWITCHTEXT(stretchwindow, "Rozt hnout okno TTD", " na %d pixel…")
SWITCHTEXT(canals, "StavØt pr…plavy s zdymadla", "")
SWITCHTEXT(higherbridges, "Umo§nit vyçç¡ mosty", "")
SWITCHTEXT(gamespeed, "Mo§nost zmØnit rychlost hry", ", vìchoz¡ hodnota %d")
SWITCHTEXT(freighttrains, "\"ZvØtç¡\" n kladn¡ vlaky o koeficient", " (x%d)")
SWITCHTEXT(mousewheel, "Pýid  podporu koleŸka myçi",", nastaven¡: %d")
SWITCHTEXT(morewindows, "Zvìç¡ max. poŸet otevýenìch oken", " na %d")
SWITCHTEXT(enhanceddiffsettings, "Rozç¡ýen‚ nasataven¡ obt¡§nosti", "")
SWITCHTEXT(newbridges, "Nov‚ mosty", "")
SWITCHTEXT(newhouses, "Nov‚ domy ve mØstech", "")
SWITCHTEXT(newtownnames,"Novì styl pojmenov n¡ mØst","")
SWITCHTEXT(moreanimation,"Povolit v¡ce animovanìch pol¡Ÿek",", a§ do %d")
SWITCHTEXT(newshistory, "Historie zpr v", "")
SWITCHTEXT(wagonspeedlimits, "Omezen¡ rychlosti pro vag¢ny", "")
SWITCHTEXT(pathbasedsignalling, "Povolit PBS (path based signalling)", "")
SWITCHTEXT(aichoosechances, "PravdØpodobnost,co bude AI stavØt", "")
SWITCHTEXT(custombridgeheads, "Upraven  pýedmost¡", "")
SWITCHTEXT(townbuildnoroads, "MØsta nestav¡ silnice", "")
SWITCHTEXT(newcargodistribution, "Zlepçen‚ rozdØlov n¡ n kladu", "")
SWITCHTEXT(windowsnap, "Okna se pýichyt¡", " kdy§ jsou bl¡§e ne§ %d pixel…")
SWITCHTEXT(resolutionwidth, "Rozliçen¡ - ç¡ýka", " %d pixel…")
SWITCHTEXT(resolutionheight, "Rozliçen¡ - vìçka", " %d pixel…")
SWITCHTEXT(newindustries, "Novì pr…mysl", "")
SWITCHTEXT(locomotiongui, "Povolit GUI jako v Locomotion", "")
SWITCHTEXT(fifoloading, "FIFO nakl d n¡ (kdo dý¡v,ten dý¡v)", "");
SWITCHTEXT(tempsnowline, "Povolit hranici snØhu v m¡rn‚m podneb¡", "")
SWITCHTEXT(townroadbranchprob, "PravdØpdb. vytvoýen¡ siln.odboŸky", " na %d")
SWITCHTEXT(newcargos, "Povolit nov‚ druhy n kladu", "")
SWITCHTEXT(enhancemultiplayer, "Zlepçenì multiplayer (povolit v¡ce hr Ÿ…)", "")
SWITCHTEXT(newsounds, "Povolit pýid n¡ novìch zvuk… do hry", "")
SWITCHTEXT(morestats, "Umo§nit z¡sk v n¡ v¡ce statistik", "")
SWITCHTEXT(onewayroads, "Povolit zmØnu silnic na jednosmØrky s 'Ctrl'", "")
SWITCHTEXT(irrstations, "Umo§nit stavbu nepravidelnìch n dra§¡", "")
SWITCHTEXT(autoreplace, "VymØnit star  vozidla za nov ", "; %d%% min. spolehlivost nov‚ho modelu")
SWITCHTEXT(autoslope, "Umo§nit zmØnu ter‚nu bez odstranØn¡ staveb", "")
SWITCHTEXT(followvehicle, "N sledovat vozidlo pohledem v oknØ", "")
SWITCHTEXT(trams, "Povolit tramvaje na silnic¡ch", "")
SWITCHTEXT(enhancetunnels, "Povolit koleje nad vjezdem do tunelu", "")
SWITCHTEXT(forcegameoptions, "Povolit zmØnu nastaven¡ hry","")

//---------------------------------------
//  BIT SWITCH DESCRIPTIONS
//---------------------------------------

// Description for noplanecrashes bits
BITSWITCH(noplanecrashes)
BIT(normdis,      "norm ln¡ letadlo nehavaruje pokud jsou vypnuty katastrofy")
BIT(jetsdis,      "proudov  letadla na malìch letiçt¡ch nehavaruj¡ pokud jsou vypnuty katastrofy")
BIT(normbrdown,   "norm ln¡ letadlo se pýi hav rii pouze porouch , pomØr * 4")
BIT(jetssamerate, "stejnì pomØr pro proudov  letadla na malìch letiçt¡ch a norm ln¡ hav rie")
BIT(normoff,      "norm ln¡ letadla nehavaruj¡")
BIT(jetsoff,      "proudov  letadla na malìch letiçt¡ch nehavaruj¡")

// Description for miscmods bits
BITSWITCH(miscmods)
BIT(nobuildonbanks,        "mØsta nestav¡ na býehu")
BIT(servintonlyhuman,      "nastaven¡ servisn¡ho intervalu se nevztahuje na AI")
BIT(noroadtakeover,        "mØsta nezaberou vçechny cesty v editoru sc‚n ý…")
BIT(gradualloadbywagon,    "posstupn‚ nakl d n¡ nakl d  pýednostnØ po jednotlivìch vagonech")
BIT(dontfixlitres,         "nemØå litry tak, §e 1 tuna je 1000 l, nam¡sto 100 l")
BIT(dontfixtropicbanks,    "neopravuj typy pobýe§¡ v sub-tropick‚m klimatu")
BIT(dontfixhousesprites,   "neopravuj kancel ýe, kter‚ se zobrazuj¡ jako kostely")
BIT(oldtownterrmodlimit,   "nemØå horn¡ cenu £pravy ter‚nu pro mØsta")
BIT(nozeppelinonlargeap,   "zabraå vzducholod¡m havarovat na velkìch letiçt¡ch")
BIT(nodefaultoldtracktype, "nepou§¡vej pýedeçlì druh kolej¡ jako novì default")
BIT(usevehnnumbernotname,  "nemØå pou§it¡ jmen vozidel v novinovìch zpr v ch")
BIT(norescalecompanygraph, "nemØå mØý¡tko grafu spoleŸnost¡ kdy§ jsou spoleŸnosti odebr ny z vìbØru")
BIT(noyearlyfinances,      "nezobrazuj roŸn¡ finanŸn¡ vìkaz 1. ledna")
BIT(notimegiveaway,        "nezkouçej vyhazovat Ÿasov‚ £seky kv…li £spoýe energie")
BIT(nodesynchwarning,      "nevaruj pýi desynchronizaci multiplayerov‚ hry")
BIT(noworldedgeflooding,   "nenech vej okraje mapy zatopen‚")
BIT(doshowintro,           "uka§ £vod do hry (nepýeskakuj ho)")
BIT(nonewspritesorter,     "nepou§¡vej novì algoritmus vyb¡r n¡ sprit…")
BIT(nodiagonalflooding,    "znemo§ni …hlopý¡Ÿn‚ zaplaven¡ a rohov  pobýe§¡")
BIT(noenhancedcomp,        "nezlepçuj algoritmus komprese ulo§enìch her")
BIT(breakdownatsignal,     "neopravuj poruchu vlaku pýi Ÿek n¡ na sign lu st…j")
BIT(smallspritelimit,      "nezvyçuj limit poŸtu sprit…")
BIT(displaytownsize,       "zobrazuj velikost mØsta v n zvu")
BIT(noextendstationrange,  "nezvyçuj nejvØtç¡ dovolenou vzd lenost mezi znaŸkou stanice a pr…myslem pro pýev §en‚ zbo§¡")
BIT(nooldvehiclenews,      "nevytv ýej nov‚ zpr vy kdy§ je vozidlo zastaral‚")
BIT(dontfixpaymentgraph,   "neopravuj osu X v oknØ grafu ceny za pýepravenì n klad")
BIT(loaduntilgreen,        "pokraŸuj v nakl d n¡ ve stanici dokud nen¡ odjezdov‚ n vØstidlo na volno")
BIT(dontshowaltitude,      "nezobrazuj vìçku v oknØ informac¡ o pol¡Ÿku")
BIT(nogrfidsinscreenshots, "nezobrazuj aktivn¡ GrfIDy ve screenshotech")
BIT(dontchangesnow,        "nemØå zp…sob vìpoŸtu vìçky pro zasnØ§en¡")

// Description for morebuildoptions bits
BITSWITCH(morebuildoptions)
BIT(ctunnel,         "povol ký¡§en¡ tunel…")
BIT(oilrefinery,     "povol rafin‚rii vçude")
BIT(moreindustries,  "povol v¡ce ne§ jeden pr…mysl ka§d‚ho druhu")
BIT(removeobjects,   "povol odstranØn¡ soch, maj k… a vys¡laŸ…")
BIT(removeindustry,  "povol odstranØn¡ pr…myslu")
BIT(closeindustries, "povol stejn‚mu pr…myslu bìt bl¡zko vedle sebe")
BIT(enhancedbuoys,   "povol b¢j¡m, aby fungovaly jako norm ln¡ stanice")
BIT(bulldozesignals, "automaticky odstraåuj n vØstidla na trati")

// Description for experimentalfeatures bits
BITSWITCH(experimentalfeatures)
BIT(slowcrossing, "vlaky pýed pýejezdem zpomal¡")
BIT(cooperative,  "spolupr ce (kooperativn¡ hra), velmi omezen ")
BIT(mandatorygrm, "GRF Resource Management je povinnì pro soubory .grf")

// Description for maskdisasters bits
BITSWITCH(maskdisasters)
BIT(zeppelincrash,      "Povol hav rii vzducholodi")
BIT(smallufo,           "Povol mal‚ UFO")
BIT(refineryexplosion,  "Povol vìbuch rafin‚rie")
BIT(factoryexplosion,   "Povol vìbuch tov rny")
BIT(largeufo,           "Povol velk‚ UFO")
BIT(smallsubmarine,     "Povol malou ponorku")
BIT(largesubmarine,     "Povol velkou ponorku")
BIT(coalminesubsidence, "Povol pokles poddolovan‚ho ter‚nu")

// Description for mousewheel bits
BITSWITCH(mousewheel)
BIT(cursorzoom, "Zoom se stýedem v m¡stØ kursoru nam¡sto stýedu obrazovky")
BIT(safezoom,   "Zoom pouze po zarolov n¡ koleŸkem o dva \"zoubky\"")
BIT(legacy,     "Umo§nit podporu pro starç¡ operaŸn¡ syst‚my a ovladaŸe (norm lnØ nepotýebn‚)")

// Description for plantmanytrees bits
BITSWITCH(plantmanytrees)
BIT(morethanonepersquare,   "Povol zasazen¡ v¡ce ne§ jednoho stromu na pol¡Ÿko")
BIT(rectangular,            "Umo§ni zasadit obd‚ln¡kovou oblast se stiknutìm 'Ctrl'")
BIT(morethanonerectangular, "V¡ce ne§ jeden strom na pol¡Ÿko pýi obd‚ln¡kov‚m s zen¡")

// Description for moretoylandfeatures bits
BITSWITCH(moretoylandfeatures)
BIT(lighthouses, "Povolit maj ky na pobýe§¡ v Toylandu")
BIT(woodlands,   "Povolit lesy (shluky strom…) v Toylandu")

// Description for locomotiongui bits
BITSWITCH(locomotiongui)
BIT(usenewgui,      "Umo§nit nov‚ GUI")
BIT(defaultnewgui,  "StandardnØ pou§ij nov‚ GUI (pokud je toto zak z no, nov‚ GUI m…§e bìt vyvol no s 'Ctrl'; pokud je povoleno, s 'Ctrl' bude pou§ito star‚ GUI)")
BIT(defaultstation, "TlaŸ¡tko stavby stanice otevýe Locomotion GUI staniŸn¡ z lo§ku")

// Description for pathbasedsignalling bits
BITSWITCH(pathbasedsignalling)
BIT(autoconvertpresig,    "Pýev‚st vjezdov , odjezdov  a cestov  n vØstidla na PBS n vØstidla")
BIT(manualpbssig,         "Povolit ruŸn¡ nastaven¡ PBS n vØstidel")
BIT(preservemanualpresig, "Nepýev dØj vìhybky s ruŸnØ nastavenìmi n vØstidly na PBS")
BIT(showreservedpath,     "Zobraz vytvoýenou vlakovou cestu tmavØji")
BIT(shownonjunctionpath,  "Zobraz vytvoýenou vlakovou cestu tak‚ na ne-vìhybkovìch pol¡Ÿc¡ch")
BIT(allowunsafejunction,  "Nezastavuj vlak u nejist‚hoPBS n vØstidla")
BIT(allowunsafereverse,   "Nezastavuj vlak, kterì se nem…§e bezpeŸnØ obr tit")

// Description for newsounds bits
BITSWITCH(newsounds)
BIT(highfrequency, "(pouze DOS) M¡chej zvuky na 22KHz m¡sto standardn¡ch 11KHz. Umo§åuje spr vnØ pýehr vat  22KHz zvuky.")

// Description for morecurrencies bits
BITSWITCH(morecurrencies)
BIT(symbefore, "Symbol mØny se v§dy zobrazuje pýed Ÿ¡slem")
BIT(symafter,  "Symbol mØny se v§dy zobrazuje za Ÿ¡slem")
BIT(noeuro,    "Nezav dØj Euro")
BIT(comma,     "V§dy pou§ij Ÿ rku k oddØlen¡ tis¡c…")
BIT(period,    "V§dy pou§ij teŸku k oddØlen¡ tis¡c…")

// Description for forcegameoptions bits
BITSWITCH(forcegameoptions)
BIT(trafficleft,	"Vnuœ hýe levostrannì silniŸn¡ provoz")
BIT(trafficright,	"Vnuœ hýe pravostrannì silniŸn¡ provoz")
BIT(imperial,		"Vnuœ hýe pou§it¡ britskìch d‚lkovìch jednotek (m¡le)")
BIT(metric,		"Vnuœ hýe pou§it¡ metrickìch d‚lkovìch jednotek (kilometry)")
BIT(townsenglish,	"Nastav anglickì styl jmen mØst")
BIT(townsfrench,	"Nastav francouzskì styl jmen mØst")
BIT(townsgerman,	"Nastav nØmeckì styl jmen mØst")
BIT(townsamerican,	"Nastav americkì styl jmen mØst")
BIT(townslatin,		"Nastav latinskoamerickì styl jmen mØst")
BIT(townssilly,		"Nastav bl znivì styl jmen mØst")
BIT(autosavedisabled,	"Zruç automatick‚ ukl d n¡")
BIT(autosave3months,	"Nastav automatick‚ ukl d n¡ po 3 mØs¡c¡ch")
BIT(autosave6months,	"Nastav automatick‚ ukl d n¡ po 6 mØs¡c¡ch")
BIT(autosave12months,	"Nastav automatick‚ ukl d n¡ po 12 mØs¡c¡ch")


// A cfg file (%s) could not be found and is ignored.
SETTEXT(LANG_CFGFILENOTFOUND, "Nemohu nal‚zt cfg soubor %s.  Ignoruji jej.\n")

// Couldn't write the config file
SETTEXT(LANG_CFGFILENOTWRITABLE, "Nemohu otevý¡t %s pro z pis.\n")

// A non-comment line is longer than 32 chars, rest ignored.
SETTEXT(LANG_CFGLINETOOLONG, "POZOR!  KonfiguraŸn¡ ý dek je delç¡ ne§ 32 znak…, zbytek ignorov n.\n")

// Shown if an obsolete switch is used. First option is %s which is the
// config name, second one is %s which is the command line char
SETTEXT(LANG_SWITCHOBSOLETE, "Volba `%s' (%s) je nefunkŸn¡. Pros¡m, nepou§¡vejte ji v pý¡çt¡\n"
		"verzi bude odstranØna.\n")

//---------------------------------------------------
//   CONFIG FILE COMMENTS (for '-W')
//---------------------------------------------------

// This is the intro at the start of the config file.  No constraints on line lengths.
SETTEXT(CFG_INTRO,
	CFG_COMMENT "\n"
	CFG_COMMENT "KonfiguraŸn¡ soubor TTDPatch.cfg byl automaticky vytvoýen pomoc¡ TTDPatch -W N zevSouboru.\n"
	CFG_COMMENT "(TTDPatch %s)\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Form t volby je:\n"
	CFG_COMMENT "   N zev = Hodnota k¢d\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Znak \"=\" m…§e bìt opominut a nahrazen mezerou.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Hodnota yes/no [y/n] ano/ne, m…§e bìt zad na tØmito znaky:\n"
	CFG_COMMENT "yes, y, on, 1, a, no, n, off, 0,\n"
	CFG_COMMENT "Jestli§e je hodnota vynech na je volba nastavena na ano/yes.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Pro volby s k¢dem je rozsah d n v pozn mce\n"
	CFG_COMMENT "V pý¡padØ, §e k¢d je opominut je volba nastavena na Default.\n"
	CFG_COMMENT "NØkter‚ volby mohou bìt vypnuty zad n¡m k¢du, kterì je vypne.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Koment ýe jsou vçechny ý dky zaŸ¡naj¡c¡ dvØma lom¡tky.\n"
	CFG_COMMENT "\n")

// Line before previously unset switches
SETTEXT(CFG_NEWSWITCHINTRO, "**** Seznam voleb ****")

// For switches which have no command line equivalent
SETTEXT(CFG_NOCMDLINE, "pýep¡naŸ nem  mo§nost z pisu v pý¡kazov‚m ý dku")

// 
// All can have a place holder %s to stand for the actual setting name,
// and all but CFG_CDPATH can have a %s *after* the %s for the command
// line switch.
// They will have the "comment" char and a space prefixed.
//
SETTEXT(CFG_SHIPS, "`%s' (%s) Maxim ln¡ poŸet lod¡.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_CURVES, "`%s' (%s) Rychlost v zat Ÿk ch 0 - normal, 1 - rychlejç¡, 2 - nejrychlejç¡, 3 - re ln .  Jedno Ÿ¡slo pro ka§dì typ trat¡ a silnici.  Default 0120.")
SETTEXT(CFG_MOUNTAINS, "`%s' (%s) Rychlost na svahu 0 - normal, 1 - rychlejç¡, 2 - nejrychlejç¡, 3 - re ln . Jedno Ÿ¡slo pro ka§dì typ trat¡ a silnici.  Default 0120.")
SETTEXT(CFG_SPREAD, "`%s' (%s) Rozlehlost spoleŸnìch zast vek.  Rozsah %ld - %ld Ÿtverc….  Default %ld.")
SETTEXT(CFG_TRAINREFIT, "`%s' (%s) Zpý¡stupn¡ refitov n¡ maçin.")
SETTEXT(CFG_SERVINT, "`%s' (%s) PoŸ teŸn¡ servisn¡ interval pro nov  vozidla.  Rozsah %ld - %ld dn….  Default %ld.")
SETTEXT(CFG_NOINFLATION, "`%s' (%s) Vypne vçechny inflace, pro n kupy i pro n vratnost.")
SETTEXT(CFG_LARGESTATIONS, "`%s' (%s) Umo§n¡ pýidat v¡ce n stupiçœ a delç¡ stanice, do 15x15.")
SETTEXT(CFG_NONSTOP, "`%s' (%s) Odliçn  \"Non-stop\" volba.")
SETTEXT(CFG_PLANES, "`%s' (%s) Maxim ln¡ poŸet letadel.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_LOADTIME, "`%s' (%s) Nov  kalkulace Ÿasu pýi nakl d n¡ a vykl d n¡.")
SETTEXT(CFG_ROADVEHS, "`%s' (%s) Maxim ln¡ poŸet aut.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_SIGNCHEATS, "`%s' (%s) Zapne cheaty.")
SETTEXT(CFG_TRAINS, "`%s' (%s) Maxim ln¡ poŸet vlak….  Rozsah %ld - %ld.  Default %ld.")
//*#define CFG_PLAYERS "`%s' (-%s) Nastav¡, kteý¡ hr Ÿi mohou po§¡vat cheaty.  Seznam hr Ÿ… od 0 - 7"
SETTEXT(CFG_VERBOSE, "`%s' (%s) Uk §e seznam voleb a jejich hodnot pýed spuçtØn¡m TTD.")
SETTEXT(CFG_PRESIGNALS, "`%s' (%s) Automaticky nastavuje super-semafory.")
SETTEXT(CFG_MOREVEHICLES, "`%s' (%s) Celkovì poŸet vozidel na hodnota*850.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_MAMMOTHTRAINS, "`%s' (%s) Dlouh‚ vlaky s a§ 126 vagony.")
SETTEXT(CFG_FULLLOADANY, "`%s' (%s) Umo§n¡ aby vlak opustil stanici jestli§e jeden z typ… n kladu je nalo§en.")
SETTEXT(CFG_SELECTGOODS, "S `%s' (%s) Zbo§¡ se objev¡ ve stanici a§ ho nØkter‚ vozidlo vy§aduje, a zmiz¡ po zadan‚m poŸtu dn¡ pokud je odvoz zastaven (nikdo si pro nØj nepýijel). Zad n¡ hjodnoty 2 znamen  §e zbo§¡ nikdy nezmiz¡. Rozsah: %ld..%ld.  Default: %ld.")
SETTEXT(CFG_DEBTMAX, "`%s' (%s) Zapne p…jŸov n¡/spl cen¡ cel‚ maxim ln¡ Ÿ stky s 'Ctrl'.")
SETTEXT(CFG_OFFICEFOOD, "`%s' (%s) Office towers akceptuj¡ j¡dlo (tropic/arctic scenaria).")
SETTEXT(CFG_ENGINESPERSIST, "`%s' (%s) Zobraz¡ ke koupi star  vozidla.")
SETTEXT(CFG_CDPATH, "`%s' (%s) Nastav¡ cestu k CD.")
// 
SETTEXT(CFG_KEEPSMALLAP, "`%s' (%s) Umo§n¡ v§dy stavØt mal  letiçtØ.")
SETTEXT(CFG_LONGBRIDGES, "`%s' (%s) Umo§n¡ stavØt mosty dlouh‚ a§ 127 Ÿtverc….")
SETTEXT(CFG_DYNAMITE, "`%s' (%s) Umo§n¡ v¡ce mo§nost¡ pro bour n¡ dynamitem.")
SETTEXT(CFG_MULTIHEAD, "`%s' (%s) Umo§n¡ v¡ce maçinov‚ vlaky s 'Ctrl'.  Parametr je max. souŸet rychlost¡ maçin, v procentech %ld %ld, default %ld%%.")
SETTEXT(CFG_RVQUEUEING, "`%s' (%s) Nastav¡ aby auta Ÿekala ve frontØ pýed stanic¡ a neot Ÿela se.")
SETTEXT(CFG_LOWMEMORY, "`%s' (%s) Umo§n¡ aby TTDPatch bØ§el i s pamØt¡ do 3.5MB, ale sn¡§¡ maxim ln¡ poŸet vozidel na 2x850.")
SETTEXT(CFG_GENERALFIXES, "`%s' (%s) Odstran¡ nØkter‚ mal‚ chyby viz. maul l.")
SETTEXT(CFG_MOREAIRPORTS, "`%s' (%s) Umo§n¡ stavbu v¡ce ne§ dvou letiçœ ve mØstØ.")
SETTEXT(CFG_BRIBE, "`%s' (%s) Pýid  mo§nost upl cen¡ `bribe' v local authority menu.")
SETTEXT(CFG_PLANECRCTRL, "`%s' (%s) Umo§n¡ ovl d n¡ hav ri¡ letadel.")
SETTEXT(CFG_SHOWSPEED, "`%s' (%s) Uk §e souŸasnou rychlost vozidla v jeho oknØ.")
SETTEXT(CFG_AUTORENEW, "`%s' (%s) Zapne autoobnovu vozidel kdy§ dos hnou pl novan‚ho ukonŸen¡ jejich §ivotnosti. Parametr je poŸet mØs¡c… od tohoto term¡nu.  Rozsah %ld a§ +%ld.  Default %ld.")
SETTEXT(CFG_CHEATSCOST, "`%s' (%s) Umo§n¡ aby cheaty st ly pen¡ze kdy§ se pou§ij¡.")
SETTEXT(CFG_EXTPRESIGNALS, "`%s' (%s) Umo§n¡ mØnit mezi norm ln¡mi semafory a super-semafory pomoc¡ 'Ctrl'.")
SETTEXT(CFG_FORCEREBUILDOVL, "`%s' (%s) Umo§n¡ aby TTDPatch zmØnil pýi ka§d‚m startu TTDLOAD.OVL nebo TTDLOADW.OVL.")
SETTEXT(CFG_DISKMENU, "`%s' (%s) Pýid  do hern¡ho menu funkci LOAD GAME a do scenario menu, funkci LOAD GAME a SAVE GAME (s 'Ctrl').")
SETTEXT(CFG_WIN2K, "`%s' (%s) UdØl  Windows verzi TTD compatibiln¡ s Windows 2000/XP.")
SETTEXT(CFG_FEEDERSERVICE, "`%s' (%s) ZmØn¡ unload a profit ve stanic¡ch akceptuj¡c¡ch n klad od pomocnìch vozidel viz. manul l.")
SETTEXT(CFG_GOTODEPOT, "`%s' (%s) Umo§n¡ pýid n¡ depa jako c¡l vozidla.")
SETTEXT(CFG_NEWSHIPS, "`%s' (%s) Aktivuje nov‚ typy lod¡ vŸetnØ nov‚ grafiky.")
SETTEXT(CFG_SUBSIDIARIES, "`%s' (%s) Umo§n¡ ovl dat soupeýe pýi vlastnØn¡ 75%%.")
SETTEXT(CFG_GRADUALLOADING, "`%s' (%s) ZmØn¡ nakl d n¡ a vykl d n¡ n klad… na v¡ce realistick‚ (tak‚ aktivuje `loadtime').")
SETTEXT(CFG_MOVEERRORPOPUP, "`%s' (%s) Pýem¡st¡ Ÿerven‚ hl çen¡ do horn¡ho lev‚ho rohu obrazovky.")
SETTEXT(CFG_SIGNAL1WAITTIME, "`%s' (%s) PoŸet dn…, po kterìch se vlak otoŸ¡ pýed jednosmØrnìm semaforem.  Rozsah 0 - 254, nebo 255 pro neot Ÿen¡. Default 70.")
SETTEXT(CFG_SIGNAL2WAITTIME, "`%s' (%s) PoŸet dn…, po kterìch se vlak otoŸ¡ pýed obousmØrnìm semaforem. Hodnota 0 - 254, nebo 255 pro neot Ÿen¡. Default 20.")
SETTEXT(CFG_DISASTERS, "`%s' (%s) Nastav¡ katastrofy, kter‚ mohou nastat.")
SETTEXT(CFG_FORCEAUTORENEW, "`%s' (%s) Pýinut¡ vozidla zajet do depa, kdy§ je Ÿas na autoobnovu (viz. `autorenew').")
SETTEXT(CFG_MORENEWS, "`%s' (%s) Hra informuje o dalç¡ch ud lostech (napý. vyk cen¡ vçech strom… u Lumber millu v tropick‚m sc‚n riu).")
SETTEXT(CFG_UNIFIEDMAGLEV, "`%s' (%s) Umo§n¡ kupovat monorail maçiny v maglev depu a naopak. K¢d: 1 - zmØn¡ vçechny maglev na monorail; 2 - zmØn¡ vçechny monorail na maglev; 3 - udr§uje monorail a maglev oddØlenØ.")
SETTEXT(CFG_BRIDGESPEEDS, "`%s' (%s) ZmØn¡ rychlostn¡ limit na tubusovìch mostech pro monorail a maglev na procento z maxim ln¡ rychlosti nejrychlejç¡ maçiny, kterou je mo§no koupit.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_ETERNALGAME, "`%s' (%s) Umo§n¡ hru i po roce 2070. LetopoŸet se nezastav¡.")
SETTEXT(CFG_SHOWFULLDATE, "`%s' (%s) V§dy uk §e cel‚ datum (i kdy§ hra nen¡ zapauzovan ).")
SETTEXT(CFG_NEWTRAINS, "`%s' (%s) Aktivuje nov‚ modely vlak… vŸetnØ nov‚ grafiky.")
SETTEXT(CFG_NEWRVS, "`%s' (%s) Aktivuje nov‚ modely aut vŸetnØ nov‚ grafiky.")
SETTEXT(CFG_NEWPLANES, "`%s' (%s) Aktivuje nov‚ modely letadel vŸetnØ nov‚ grafiky.")
SETTEXT(CFG_SIGNALSONTRAFFICSIDE, "`%s' (%s) Zobraz¡ semafory na t‚ stranØ, po kter‚ jezd¡ auta.")
SETTEXT(CFG_ELECTRIFIEDRAIL, "`%s' (%s) Odstran¡ monorail nebo maglev a m¡sto toho pýid  elektrifikovan‚ tratØ.")
SETTEXT(CFG_STARTYEAR, "`%s' (%s) Nastav¡ startovn¡ rok pro n hodnou hru a umo§n¡ rozs hlejç¡ vìbØr startovn¡ho roku v editoru. Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_ERRORPOPUPTIME, "`%s' (%s) ¬as, po kter‚m automaticky zmiz¡ Ÿerven‚ hl çen¡ v sekund ch.  Rozsah 1 - 255, ( 0 pro velmi dlouhì Ÿas.  Default 10.")
SETTEXT(CFG_TOWNGROWTHLIMIT, "`%s' (%s) Maxim ln¡ mo§nì rozsah mØst. Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_LARGERTOWNS, "`%s' (%s) PoŸet mØst, ze kterìch jedno roste rychleji a v¡ce (tak‚ aplikuje `towngrowthlimit' selektivnØ).  Rozsah %ld - %ld.  Default %ld (jedno mØsto ze Ÿtyý).")
SETTEXT(CFG_MISCMODS, "`%s' (%s) ZmØn¡ funkci nØkterìch voleb nebo je modifikuje viz. manu l.")
SETTEXT(CFG_LOADALLGRAPHICS, "`%s' (%s) Pýinut¡ TTDPatch v§dy nahr t vçechny *.grf soubory v newgrf(w).cfg, bez ohledu na to, zda byly pou§ity v pýedch zej¡c¡m spuçtØn¡ hry nebo ne.")
SETTEXT(CFG_SAVEOPTDATA, "`%s' (%s) TTDPatch ulo§¡ pýidan  data na konec souboru (funguje i pro nahr v n¡ save s pýidanìmi daty).")
SETTEXT(CFG_MOREBUILDOPTIONS, "`%s' (%s) V¡ce mo§nost¡ pýi stavØn¡.")
SETTEXT(CFG_SEMAPHORES, "`%s' (%s) Pýed rokem 1975 jdou postavit pouze star‚ mechanick‚ semafory.")
SETTEXT(CFG_MOREHOTKEYS, "`%s' (%s) Zapnuty nov‚ kl vesy pro ovl d n¡ nØkterìch funkc¡ ve hýe.")
SETTEXT(CFG_MANYTREES, "`%s' (%s) Umo§n¡ zasadit  v¡ce ne§ jeden strom najednou, oznaŸen¡m dvou protilehlìch vrchol… obdl‚ln¡ku s Ctrl.")
SETTEXT(CFG_MORECURRENCIES,"`%s' (%s) Zapne v¡ce mØn vŸetnØ Euro po roce 2002.")
SETTEXT(CFG_MANCONVERT,"`%s' (%s) Umo§n¡ ruŸn¡ zmØnu trat¡ um¡stØn¡m nov‚ho typu tratØ na ji§ existuj¡c¡ traœ (bez dynamitu).")
SETTEXT(CFG_NEWAGERATING, "`%s' (%s) Rating zast vek je v¡ce tolerantn¡ k vØku vozidel.  Vag¢ny mohou bìt a§ 21 let star‚ m¡sto 3 let.")
SETTEXT(CFG_ENHANCEGUI,"`%s' (%s) ZmØn¡ grafickì vzhled nØkterìch oken.")
SETTEXT(CFG_TOWNGROWTHRATEMODE, "`%s' (%s) Umo§n¡ definovat pravidla pro kalkulaci r…stu mØst. 0 - TTD original, 1 - TTD vylepçen‚, 2 - u§ivatelsk‚.  Viz dokumentace.")
SETTEXT(CFG_TOWNGROWTHRATEMIN, "`%s' (%s) Definuje minim ln¡ r…st mØst. Jedn  se o poŸet novìch dom… za sto let.  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TOWNGROWTHRATEMAX, "`%s' (%s) Definuje maxim ln¡ r…st mØst. Jedn  se o poŸet novìch dom… za sto let.  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRACTSTATIONEXIST, "`%s' (%s) Definuje kolik z existuj¡c¡ch aktivn¡ch zast vek zvyçuje r…st mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld +%ld.  Default %ld.")
SETTEXT(CFG_TGRACTSTATIONS, "`%s' (%s) Definuje kolik zast vek zvyçuje r…st mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRACTSTATIONSWEIGHT, "`%s' (%s) Definuje jak aktivn¡ zast vky pýisp¡vaj¡ k r…stu mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRPASSOUTWEIGHT, "`%s' (%s) Definuje jak efektivnØ odj¡§dØj¡c¡ lid‚ pýisp¡vaj¡ k r…stu mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRMAILOUTWEIGHT, "`%s' (%s) Definuje jak efektivnØ odj¡§dØj¡c¡ poçta pýisp¡v  k r…stu mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRPASSINMAX, "`%s' (%s) Definuje maxim ln¡ poŸet pýij¡§dØj¡c¡ch lid¡, kterì m…§e m¡t efekt na r…st mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRPASSINWEIGHT, "`%s' (%s) Definuje jak efektivnØ pýij¡§dØj¡c¡ lid‚ pýisp¡vaj¡ k r…stu mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRMAILINOPTIM, "`%s' (%s) Definuje optim ln¡ populaci na ka§d‚ 2 bal¡ky pý¡j¡§dØj¡c¡ poçty (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRMAILINWEIGHT, "`%s' (%s) Definuje jak efektivnØ pýij¡§dØj¡c¡ poçta pýisp¡v  k r…stu mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRGOODSINOPTIM, "`%s' (%s) Definuje optim ln¡ populaci na ka§d‚ 2 ks zbo§¡ (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRGOODSINWEIGHT, "`%s' (%s) Definuje jak efektivnØ pýij¡§dØj¡c¡ zbo§¡ pýisp¡v  k r…stu mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRFOODINMIN, "`%s' (%s) Definuje minim ln¡ potýebu j¡dla ve mØstech ve snØhem pokrytìch m¡stech a v pouçt¡ch. Kolik populace na 2 tuny pýij¡§dØj¡c¡ho j¡dla (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRFOODINOPTIM, "`%s' (%s) Definuje optimum populace na ka§d‚ 2 tuny pýij¡§dØj¡c¡ho j¡dla (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRFOODINWEIGHT, "`%s' (%s) Definuje jak efektivnØ pýij¡§dØj¡c¡ j¡dlo pýisp¡v  k r…stu mØst (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRWATERINMIN, "`%s' (%s) Definuje minim ln¡ potýebu vody ve mØstech v pouçt¡ch. Kolik populace na 2 tuny (2000 litr…) pýij¡§dØj¡c¡ vody (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRWATERINOPTIM, "`%s' (%s) Definuje optimum populace na ka§d‚ 2 tuny (2000 litr…) pýij¡§dØj¡c¡ vody v tropick‚m klimatu (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRWATERINWEIGHT, "`%s' (%s) Definuje jak efektivnØ pýij¡§dØj¡c¡ vody pýisp¡v  k r…stu mØst v tropick‚m klimatu (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRSWEETSINOPTIM, "`%s' (%s) Definuje optim ln¡ populaci na ka§d‚ 2 ks pýij¡§dØj¡c¡ch sladkost¡ v dØtsk‚m klimatu (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRSWEETSINWEIGHT, "`%s' (%s) Definuje jak efektivnØ pýiji§dØj¡c¡ sladkosti pýisp¡vaj¡ k r…stu mØst v dØtsk‚m klimatu (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRFIZZYDRINKSINOPTIM, "`%s' (%s) Definuje optim ln¡ populaci na ka§d‚ 2 ks pýij¡§dØj¡c¡ch limon d v dØtsk‚m klimatu (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRFIZZYDRINKSINWEIGHT, "`%s' (%s) Definuje jak efektivnØ limon dy pýisp¡vaj¡ k r…stu mØst v dØtsk‚m klimatu (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TGRTOWNSIZEBASE, "`%s' (%s) Definuje z kladn¡ poŸet mØstskìch budov pro vìpoŸet volby `tgrtownsizefactor' (viz. dokumentace).  Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRTOWNSIZEFACTOR, "`%s' (%s) Definuje, jak velikì vliv m  velikost mØst na r…st mØst (viz. dokumentace). Aktivn¡ pouze kdy§ volba `towngrowthratemode' = 2.  Rozsah %ld - %ld.  Default %ld (tzn. 25 procentn¡ vliv).")
SETTEXT(CFG_TOWNMINPOPULATIONSNOW, "`%s' (%s) Definuje minimum populace v snØhem pokrytìch mØstech, od kter‚ho mohou r…st bez podpory j¡dla. Aktivn¡ pouze kdy§ jsou volby `towngrowthratemode', `towngrowthlimit' a `generalfixes' zapnuty.  Rozsah %ld - %ld.  Default %ld.")
SETTEXT(CFG_TOWNMINPOPULATIONDESERT, "`%s' (%s) Definuje minimum populace ve mØstech na pouçti, od kter‚ho mohou r…st bez podpory vodou a j¡dlem. Aktivn¡ pouze kdy§ jsou volby `towngrowthratemode', `towngrowthlimit' a `generalfixes' zapnuty.  Rozsah %ld - %ld. Default %ld.")
SETTEXT(CFG_MORETOWNSTATS, "`%s' (%s) Zobraz¡ v¡ce informac¡ v oknØ mØsta.")
SETTEXT(CFG_BUILDONSLOPES, "`%s' (%s) Umo§n¡ stavØn¡ trat¡, silnic a zast vek na svahu se stejnìm z kladem jako u dom….")
SETTEXT(CFG_BUILDONCOASTS, "`%s' (%s) Umo§n¡ stavØn¡ na býehu bez pýedchoz¡ho pou§it¡ dynamitu.")
SETTEXT(CFG_TRACKTYPECOSTDIFF, "`%s' (%s) R…zn‚ typy trat¡ maj¡ r…znou cenu.")
SETTEXT(CFG_EXPERIMENTALFEATURES, "`%s' (%s) Zapne nov‚ experiment ln¡ volby.")
SETTEXT(CFG_PLANESPEED, "`%s' (%s) Zrychl¡ letadla na jejich skuteŸnou indikovanou rychlost (p…vodn¡ rychlost je Ÿtvrtinov  oproti indikovan‚) a pýi stavu Brake Down zredukuje rychlost na 5/8.  Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_FASTWAGONSELL, "`%s' (%s) Rychlejç¡ prodej vag¢n… s Ctrl")
SETTEXT(CFG_NEWRVCRASH,"`%s' (%s) MØn¡ auto-vlakov‚ kolize. Hodnota 1 znamen , §e vlak po kolizi s autem bude chv¡li ve stavu Brake Down. Hodnota 2 vypne auto-vlakov‚ kolize. Default 1.");
SETTEXT(CFG_STABLEINDUSTRY,"`%s' (%s) ¦ dnì pr…mysl nezkrachuje pýi stabiln¡ ekonomice (v menu Difficulty settings je polo§ka Economy nastavena na Steady).");
SETTEXT(CFG_NEWPERF, "`%s' (%s) uplatåuje rozumnØjç¡ vìpoŸet vìkonnosti vzhledem k zisk…m vozidel.")
SETTEXT(CFG_SORTVEHLIST, "`%s' (%s) ýad¡ vozidla v oknØ seznamu vozidel. Hodnota ud v  Ÿas mezi dvØma aktualizacemi. Ni§ç¡ hodnota vy§aduje v¡ce Ÿasu procesoru, ale udr§uje seznam aktu lnØjç¡. Nastaven¡ na 10 znamen  pýibli§nØ jeden den v TTD. Rozsah %ld..%ld. Default %ld.")
SETTEXT(CFG_NEWSPAPERCOLOUR, "`%s' (%s) zmØn¡ noviny na barevn‚ v dan‚m roce. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_SHAREDORDERS, "`%s' (%s) umo§n¡ sd¡len‚ nebo zkop¡rovan‚ j¡zdn¡ ý dy.")
SETTEXT(CFG_SHOWPROFITINLIST, "`%s' (%s) zobraz¡ barevnØ rozliçen‚ zisky v seznamu vozidel.")
SETTEXT(CFG_MORESTEAM, "`%s' (%s) zobraz¡ v¡ce (nebo m‚nØ) oblak… p ry. Hodnota m  dvØ Ÿ¡slice, prvn¡ pro d‚lku oblaku p ry, druhou pro frekvenci, pýiŸem§ 2 je default TTD. Pýid n¡/odebr n¡ jedn‚ zdvojn sob¡/zpoloviŸn¡ d‚lku nebo frekvenci. Rozsah %02lx..%02lx.  Default %02lx.")
SETTEXT(CFG_ABANDONEDROADS, "`%s' (%s) zp…sob¡, §e silnice ztrat¡ sv‚ho majitele pokud nejsou po urŸitou dobu pou§¡v ny, tak§e m…§ete odstranit nepou§¡van‚ silnice, pokud pýek §ej¡ v cestØ. Tak‚ z¡sk te vlastnictv¡ silnic, kter‚ pou§¡vaj¡ vaçe vozidla. V re§imu 0 vçechny silnice ztrat¡ sv‚ majitele, v re§imu 1 jsou silnice bl¡zko mØst pýevzaty mØstem pokud nejsou nØjakì Ÿas pou§¡v ny, v re§imu 2 jsou pýevzaty okam§itØ.")
SETTEXT(CFG_NEWSTATIONS, "`%s' (%s) umo§n¡ novou grafiku stanic.")
SETTEXT(CFG_BUILDWHILEPAUSED, "`%s' (%s) umo§n¡ prov dØt vçechny stavebn¡ operace pýi zapauzovan‚ hýe.")
SETTEXT(CFG_TRAINLOSTTIME, "`%s' (%s) d v  varovnou hl çku o ztracen‚m vlaku po zadan‚m poŸtu dn¡. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_RVLOSTTIME, "`%s' (%s) d v  varovnou hl çku o ztracen‚m automobilu po zadan‚m poŸtu dn¡. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_SHIPLOSTTIME, "`%s' (%s) d v  varovnou hl çku o ztracen‚ lodi po zadan‚m poŸtu dn¡. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_AIRCRAFTLOSTTIME, "`%s' (%s) d v  varovnou hl çku o ztracen‚m letadle po zadan‚m poŸtu dn¡. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_MAPREFRESH, "`%s' (%s) pýenastav¡ frekvenci obnnovov n¡ okna mapy. Ni§ç¡ hodnota znamen  rychlejç¡ pýekreslen¡ a v¡ce vyu§it¡ procesoru. Default TTD je 64. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_NETWORKTIMEOUT, "`%s' (%s) odpoj¡ s¡œovou hru pokud nen¡ odezva po zadanì poŸet sekund. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_TOYLANDFEATURES, "`%s' (%s) umo§n¡ prvky krajiny, kter‚ jsou norm lnØ v n hodn‚ hýe v Toylandu znemo§nØn‚, jako napý¡klad maj ky.")
SETTEXT(CFG_STRETCHWINDOW, "`%s' (%s) rozt hne okno TTD do t‚to vodorovn‚ velikosti v pixelech (pouze pro Windows verzi TTD spuçtØnou v oknØ). Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_CANALS, "`%s' (%s) umo§n¡ stavØt pr…plavy a zdymadla pou§it¡m n stroje 'koupit pozemek' z menu stavby doku.")
SETTEXT(CFG_FREIGHTTRAINS, "`%s' (%s) n sob¡ n klad pýev §enì n kladn¡m vlakem zadanou hodnotou pro simulaci velmi dlouhìch n kladn¡ch vlak…. P…sob¡ to pouze na zrychlen¡, vlaky nepýev §ej¡ v¡ce n kladu. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_GAMESPEED, "`%s' (%s) umo§åuje mØnit rychlost hry. Toto vy§aduje hotkeys patch. Stiskem kl vesy 'q' se hra dvakr t zrychl¡ (a§ do maxim lnØ 8x rychlejç¡), stiskem kl vesy 'w' se hra zpomal¡. Hodnota je poŸ teŸn¡ nastaven¡. Rozsah %ld..%ld.  Default %ld.")
SETTEXT(CFG_HIGHERBRIDGES, "`%s' (%s) umo§n¡ stavØt vyçç¡ mosty.")
SETTEXT(CFG_NEWGRFCFG, "`%s' (%s) vybere konfiguraŸn¡ soubor pro novou grafiku.")
SETTEXT(CFG_MOUSEWHEEL, "`%s' (%s) umo§åuje pou§it¡ koleŸka myçi ve Windows verzi.")
SETTEXT(CFG_MOREWINDOWS, "`%s' (%s) umo§n¡ v¡ce otevýenìch oken na obrazovce. Default TTD je 10, ale 3 pozice jsou v§dy obsazen‚ (hlavn¡ panel n stroj…, hlavn¡ pohled, stavovì ý dek), tak§e souŸasn‚ maximum je 7. Rozbalovac¡ nab¡dky a novinov‚ zpr vy se tak‚ poŸ¡taj¡ jako okna. Rozsah %ld..%ld. Default %ld.")
SETTEXT(CFG_ENHANCEDDIFFICULTYSETTINGS, "'%s' (%s) umo§åuje vybrat '§ dn‚' pro poŸet pr…myslu v nastaven¡ obt¡§nosti.")
SETTEXT(CFG_NEWBRIDGES, "`%s' (%s) umo§åuje novou grafiku pro mosty.")
SETTEXT(CFG_NEWHOUSES, "`%s' (%s) aktivuje nov‚ typy budov ve mØstØ s novou grafikou.")
SETTEXT(CFG_NEWTOWNNAMES, "`%s' (%s) umo§åuje pýidat nov‚ n zvy mØst pro n hodn‚ hry pomoc¡ novìch grf soubor….")
SETTEXT(CFG_MOREANIMATION, "`%s' (%s) umo§åuje zvìçit poŸet pol¡Ÿek, kter  budou animov na. Default TTD je 256. Rozsah %ld..%ld. Default %ld.")
SETTEXT(CFG_NEWSHISTORY, "`%s' (%s) umo§åuje z znam a zobrazen¡ historie zpr v.")
SETTEXT(CFG_WAGONSPEEDLIMITS, "`%s' (%s) umo§åuje omezen¡ rychlosti pro vag¢ny.")
SETTEXT(CFG_PATHBASEDSIGNALLING, "`%s' (%s) umo§åuje PBS - path based signalling. Pýed pou§it¡m si pýeŸtØte manu l, spr vn‚ pou§it¡ t‚to funkce je ponØkud obt¡§nØjç¡.")
SETTEXT(CFG_CUSTOMBRIDGEHEADS, "`%s' (%s) upravuje pýedmost¡.")
SETTEXT(CFG_TOWNBUILDNOROADS, "`%s' (%s) mØsta nestav¡ silnice.")
SETTEXT(CFG_NEWCARGODISTRIBUTION, "`%s' (%s) zlepçen‚ rozdØlov n¡ n kladu.")
SETTEXT(CFG_WINDOWSNAP, "`%s' (%s) dovol¡ okn…m se vz jemnØ pýichyt vat. Rozsah %ld..%ld. Default %ld.")
SETTEXT(CFG_RESOLUTIONWIDTH, "`%s' (%s) umo§åuje a nastavuje ç¡ýku rozliçen¡ obrazu.")
SETTEXT(CFG_RESOLUTIONHEIGHT, "`%s' (%s) umo§åuje a nastavuje vìçku rozliçen¡ obrazu.")
SETTEXT(CFG_AICHOOSECHANCES, "`%s' (%s) ud v  jakou pravdØpodobnost pou§¡t, kdy§ se AI rozhoduje co bude stavØt (pravdØpodobnost stavby lodn¡ linky je 1 - çance §eleznice - çance silnice - çance letadla).")
SETTEXT(CFG_AIBUILDRAILCHANCE, "`%s' (%s) pravdØpodobnost, §e AI bude stavØt §elezniŸn¡ spojen¡, kdy§ bude cht¡t postavit novou trasu. Rozsah %ld..%ld, 0=0%%, 65535=100%%. Default %ld.")
SETTEXT(CFG_AIBUILDRVCHANCE, "`%s' (%s) pravdØpodobnost, §e AI bude stavØt automobilov‚ spojen¡, kdy§ bude cht¡t postavit novou trasu. Rozsah %ld..%ld, 0=0%%, 65535=100%%. Default %ld.")
SETTEXT(CFG_AIBUILDAIRCHANCE, "`%s' (%s) pravdØpodobnost, §e AI bude stavØt leteck‚ spojen¡, kdy§ bude cht¡t postavit novou trasu. Rozsah %ld..%ld, 0=0%%, 65535=100%%. Default %ld.")
SETTEXT(CFG_NEWINDUSTRIES, "`%s' (%s) umo§åuje podporu pro nov‚ druhy pr…myslu.")
SETTEXT(CFG_LOCOMOTIONGUI, "`%s' (%s) umo§åuje nov‚ GUI jako v Locomotion.")
SETTEXT(CFG_FIFOLOADING, "`%s' (%s) umo§åuje FIFO nakl d n¡ (kdo dý¡v pýijede, ten dý¡v nakl d ).")
SETTEXT(CFG_TEMPSNOWLINE, "`%s' (%s) umo§åuje hranici snØhu v m¡rn‚m podneb¡ (potýebuje vhodnì grafickì .grf soubor pro skuteŸn‚ zobrazen¡ snØhu)")
SETTEXT(CFG_TOWNROADBRANCHPROB, "`%s' (%s) mØn¡ pravdØpodobnost, §e mØsto postav¡ silniŸn¡ odboŸku. 0 znamen  skoro § dn‚ odboŸky, 65535 znamen  odboŸky vçude kde je to mo§n‚. Default TTD je 26214. Rozsah %ld..%ld. Default %ld.")
SETTEXT(CFG_NEWCARGOS, "`%s' (%s) umo§åuje podporu pro nov‚ druhy n kladu.")
SETTEXT(CFG_ENHMULTI, "`%s' (%s) zlepçuje multiplayer dovolen¡m v¡ce lidskìch hr Ÿ….")
SETTEXT(CFG_ONEWAYROADS, "`%s' (%s) umo§åuje jednosmØrn‚ silnice")
SETTEXT(CFG_NEWSOUNDS, "`%s' (%s) dovoluje do hry pýidat nov‚ zvuky pýes r…zn‚ .grf soubory.")
SETTEXT(CFG_IRRSTATIONS, "`%s' (%s) dovoluje postavit n dra§¡ v nepravideln‚m tvaru.")
SETTEXT(CFG_MORESTATS, "`%s' (%s) umo§åuje z¡sk n¡ v¡ce statistik (funguje pouze pokud je souŸasnØ povolen‚ 'enhancegui').")
SETTEXT(CFG_AUTOREPLACE, "`%s' (%s) pýi obnovØ star‚ho vozidla ho vymØn¡ za nejlepç¡ dostupnì novì typ s danou minim ln¡ spolehlivost¡ v procentech. Rozsah 1..100, default 80.")
SETTEXT(CFG_AUTOSLOPE, "`%s' (%s) dovoluje zmØnu ter‚nu bez nutnosti bourat stavby na nØm.")
SETTEXT(CFG_FOLLOWVEHICLE, "`%s' (%s) dovoluje, aby hlavn¡ pohled sledoval vozidlo pýi kliknut¡ pravìm myç¡tkem na tlaŸ¡tko 'Vystýedit Pohled' v oknØ vozidla.")
SETTEXT(CFG_TRAMS, "`%s' (%s) dovoluje stavØt tramvaje.")
SETTEXT(CFG_ENHANCETUNNELS, "`%s' (%s) dovoluje stavØt traœ nad vjezdem do tunelu.")
SETTEXT(CFG_FORCEGAMEOPTIONS, "`%s' (%s) dovol¡ v m vynutit mo§nosti hry.")


//----------------------------------------------------
//   SWITCH DISPLAY ('-v')
//----------------------------------------------------

// Wait for a key before displaying the switches
SETTEXT(LANG_SWWAITFORKEY, "\nStiskem Enter se spust¡ TTD, stiskem Escape se program pýeruç¡, stiskem jin‚ kl vesy se uk §ou volby a jejich hodnoty.")

// Introduction
SETTEXT(LANG_SHOWSWITCHINTRO, "    Nastaven¡ voleb:   (%c zapnuto, %c vypnuto)\n")

// Five characters: vertical line for the table; enabled switch; disabled switch;
// table heading; table heading column separator.
SETTEXT(LANG_SWTABLEVERCHAR, "³+-ÄÂ")

// 1-way and 2-way captions after "New train wait time on red signals"
SETTEXT(LANG_SWONEWAY, "JednosmØrn‚: ")
SETTEXT(LANG_SWTWOWAY, "ObousmØrn‚: ")

// Train wait time is either in days or infinite
SETTEXT(LANG_TIMEDAYS, "%d dn…")
SETTEXT(LANG_INFINITETIME, "nekoneŸnì")

// Shows the keys to scroll the verbose switch table
SETTEXT(LANG_SCROLLKEYS, " Kl vesy: Nahoru Dol… PgUp PgDown Home End ")

// ... and to abort TTDPatch
SETTEXT(LANG_SCROLLABORTKEY, " Escape = zruçit ")

// Shows the load options for ttdload.  %s is the given parameters to be passed to ttdload
SETTEXT(LANG_SWSHOWLOAD, "Enter/Space = spustit \"TTDLOAD %s\"")

SETTEXT(LANG_SWABORTLOAD, "\nProgram je pýeruçen u§ivatelem.\n")


//---------------------------------------
//  STARTUP AND REPORTING
//---------------------------------------

// Internal error in TTDPatch (%d is error number)
SETTEXT(LANG_INTERNALERROR, "*** Vnitýn¡ chyba TTDPatch #%d ***\n")

// Error fixing the Windows version HDPath registry entry
SETTEXT(LANG_REGISTRYERROR, "TTD nen¡ spr vnØ nainstalov n (chyba registru %d)\n")

// Trying no-registry file
SETTEXT(LANG_TRYINGNOREGIST, "Zkouç¡m neregistrov‚ informace z %s\n")

// no-registry file failed
SETTEXT(LANG_NOREGISTFAILED, "Neregistrov‚ informace nejsou dostupn‚.\n")

// DOS reports not enough memory available to start TTD
SETTEXT(LANG_NOTENOUGHMEMTTD, "Nen¡ dost pamØti pro start programu. Nyn¡ je to start TTD, a je potýeba %d KB.\n")

// Other out-of-memory messages
// %s je funkce nebo jm‚no promØnn‚ pro identifikaci kde selhalo pýidØlen¡ pamØti
SETTEXT(LANG_NOTENOUGHMEM, "%s: Nedostatek dostupn‚ pamØti, potýebuji o %d KB v¡ce.\n")

// Swapping TTDPatch out
SETTEXT(LANG_SWAPPING, "Swapov n¡ ukonŸeno.\n")

// Just before running ttdload, show this.
// 1st %s is ttdload.ovl, then %s is a space if there are options,
// and the 3rd %s contains the options
SETTEXT(LANG_RUNTTDLOAD, "Startuje %s%s%s\n")

// Error executing ttdload.  1st %s is ttdload.ovl, 2nd %s is the error message from the OS
SETTEXT(LANG_RUNERROR, "Nemohu naj¡t %s: %s\n")

// Failed to create the new process for ttdloadw.ovl
SETTEXT(LANG_CRPROCESSFAIL, "Tvorba procesu selhala")

// Interprocess communication error: TTDPatchW seems to be already running
SETTEXT(LANG_IPCEXISTS, "Jin‚ spuçtØn¡ TTDPatche pr vØ bØ§¡!\n")

// Failed to convert language strings to Unicode
SETTEXT(LANG_STRINGCONVFAIL, "Chyba pýi pý¡pravØ dat TTDPatche!\n")

// Show the result after after running, %s is one of the following strings
SETTEXT(LANG_RUNRESULT, "Vìsledek: [%s]\n")
SETTEXT(LANG_RUNRESULTOK, "OK")
SETTEXT(LANG_RUNRESULTERROR, "Chyba!")



//---------------------------------------
//  MESSAGES DISPLAYED BY TTDLOAD
//---------------------------------------

// Messages in this category will have "TTDPatch: " prefixed and "\r\n" suffixed
// when displayed by the DOS version.

// Out of memory (in protected mode)
SETTEXT(LANG_PMOUTOFMEMORY, "Nedostatek voln‚ pamØti!")

// Interprocess communication failed (WinTTDX only)
SETTEXT(LANG_PMIPCERROR, "Pýenosov  chyba procesu")


