//
// Localization strings for TTDPatch.
//

//-------------------------------------------
//  INFO ABOUT THIS LANGUAGE
//-------------------------------------------
SETNAME("Danish")
SETCODE("dk")
COUNTRYARRAY(countries) = { 45, 0, 0x06, 0 };
SETARRAY(countries);
	// 45 is Denmark, and 0x06 is Danish in Windows

DOSCODEPAGE(850)	// The default DOS code page for this language
WINCODEPAGE(1252)	// The default Windows code page for this language
EDITORCODEPAGE(850)	// The code page of all strings in this file.

DOSENCODING(IBM850)	// Encoding type for XML output from DOS and Windows;
WINENCODING(ISO-8859-1)	// DOS MUST be from IANA-CHARSETS and same as DOSCODEPAGE
			// Windows can be any ISO-8859-x encoding, doesn't have
			// to be related to WINCODEPAGE

//-------------------------------------------
//  PROGRAM BLURBS
//-------------------------------------------

// First line of output is something like "TTDPatch V1.5.1 starting.\n"
// The program name and version are autogenerated, only put the " starting\n"
// here
SETTEXT(LANG_STARTING, " starter.\n")


//-------------------------------------------
//  VERSION CHECKING
//-------------------------------------------

// In the version identifier, this is for the file size
SETTEXT(LANG_SIZE, "stõrrelse")

// Shown if the version is recognized
SETTEXT(LANG_KNOWNVERSION, "Denne version af programmet har kendte adresser.\n")

// Warning if the version isn't recognized.  Be sure *not* to use tabs
// in the text.  All but the last lines should end in ...\n"
SETTEXT(LANG_WRONGVERSION, "\n"
	"ADVARSEL! Din program version er ukendt for programmet. Du kan prõve\n"
	"          at starte det alligevel og bestemme den nõdvendige information, men hvis\n"
	"          dette gÜr galt, vil TTD terminere med en beskyttelsesfejl (Protection Fault).\n"
	"\n"
	"          Dit system kan resikere at gÜ ned med evt. datatab til fõlge, alt efter \n"
	"          hvor godt dit operativsystem hÜndterer en beskyttelsesfejl (GPF).\n"
	"          Vër venlig at lëse\n"
	"          \"Version Trouble\" afsnittet i TTDPatch manualen for mere\n"
	"          information.\n"
	"\n"
        "Svar kun 'j' (ja), hvis du er helt sikker pÜ hvad du gõr. NU ER DU ADVARET!\n"
	"Vil du alligevel starte TTD? ")

// Keys which continue loading after the above warning. *MUST* be lower case.
// can be several different keys, e.g. one for your language "yjo"
SETTEXT(LANG_YESKEYS, "j")

// Answering anything but the above keys gives this message.
SETTEXT(LANG_ABORTLOAD, "Programindlësning afbrudt.\n")

// otherwise continue loading
SETTEXT(LANG_CONTINUELOAD, "Jeg skal gõre mit bedste...\n")

// Warning if '-y' was used and the version is unknown
SETTEXT(LANG_WARNVERSION, "Advarsel: versionen er ukendt!\n")


// -------------------------------------------
//    CREATING AND PATCHING TTDLOAD
// -------------------------------------------

// TTDLOAD.OVL doesn't exist
SETTEXT(LANG_OVLNOTFOUND, " ej fundet, leder efter originale filer:\n")

// neither do the original files (two %s are two filenames)
SETTEXT(LANG_NOFILESFOUND, "kunne hverken finde %s eller %s.\n")

// default Windows language executable (american/english/french/german/spanish).exe
SETTEXT(LANG_WINDEFLANGEXE, "AMERICAN.EXE");

// Shown when copying tycoon.exe or ttdx.exe (first %s) to ttdload.ovl (2nd %s)
SETTEXT(LANG_SHOWCOPYING, "Kopierer %s til %s")

// Error if running the copy command fails.  %s is the command.
SETTEXT(LANG_COPYERROR_RUN, "Kunne ikke afvikle %s\n")

// Error if command returned successfully, but nothing was copied.
// %s=TTDLOAD.OVL
SETTEXT(LANG_COPYERROR_NOEXIST, "Kopieringsfejl - filen %s eksisterer ikke.\n")

// Invalid .EXE format
SETTEXT(LANG_INVALIDEXE, "Forkert .EXE format.\n")

// Version could not be determined
SETTEXT(LANG_VERSIONUNCONFIRMED, "Kunne ikke bestemme program version.\n")

// Shows program name (1st %s) and version (2nd %s)
SETTEXT(LANG_PROGANDVER, "Programnavnet er:\n  %s\nDen nõjagtige version er %s\n")

// More than three numbers in the version string (not #.#.#)
SETTEXT(LANG_TOOMANYNUMBERS, "Versionen har for mange tal!\n")

// .EXE is not TTD
SETTEXT(LANG_WRONGPROGRAM, "Dette er ikke Transport Tycoon Deluxe.\n")

// Displays the parsed version number
SETTEXT(LANG_PARSEDVERSION, "Oversat version er %s\n")

// The exe has been determined to be the DOS extended executable
SETTEXT(LANG_ISDOSEXTEXE, "Dette er et DOS udviddet eksekverbart program (extended executable).\n")

// The exe has been determined to be the Windows executable
SETTEXT(LANG_ISWINDOWSEXE, "Dette er et Windows program.\n")

// The exe is of an unknown type
SETTEXT(LANG_ISUNKNOWNEXE, "Dette er ikke et kendt eksekverbart format.\n")

// The exe is the wrong one for this TTDPatch, i.e. DOS/Windows mixed up. %s=DOS or Windows
SETTEXT(LANG_NOTSUPPORTED, "Beklager, men denne version af TTDPatch virker kun med %s versionen.\n")

// If the original .exe segment length (%lx) is too large or too small
SETTEXT(LANG_INVALIDSEGMENTLEN, "Forkert original segment. Lëngde: %lx")

// When increasing the segment length
SETTEXT(LANG_INCREASECODELENGTH, "Setter program stõrrelse til %s MB.\n")

// Can't write to TTDLOAD.OVL (%s) [or TTDLOADW.OVL for the Windows version]
SETTEXT(LANG_WRITEERROR, "Kan ikke skrive til %s, er den ikke skrivbar (read-only)?\n")

// Installing the code loeader
SETTEXT(LANG_INSTALLLOADER, "Installerer kodeindlëseren.\n")

// TTDLOAD.OVL (%s) is invalid, needs to be deleted.
SETTEXT(LANG_TTDLOADINVALID, "Kunne ikke installere kodeindlëseren")
SETTEXT(LANG_DELETEOVL, " - prõv at slette %s.\n")

// TTDLOAD.OVL was verified to be correct
SETTEXT(LANG_TTDLOADOK, "%s er OK.\n")

// Waiting for key before terminating TTDPatch after an error occured
SETTEXT(LANG_PRESSANYKEY, "Tryk en tast for at afbryde.")

// Displayed on various warning conditions: Esc to exit, any other key to continue
SETTEXT(LANG_PRESSESCTOEXIT, "Tryk Escape for at annullere, eller en vilkÜrlig tast for at fortsëtte")

// Loading custom in-game texts
SETTEXT(LANG_LOADCUSTOMTEXTS, "Henter sërlige tekster til spillet.\n")

// ttdpttxt.dat is not in a valid format
SETTEXT(LANG_CUSTOMTXTINVALID, "Lëser %s: Ugyldigt fil format.\n")


//-----------------------------------------------
//   COMMAND LINE HELP (-h)
//-----------------------------------------------

// Introduction, prefixed with "TTDPATCH V<version> - "
SETTEXT(LANG_COMMANDLINEHELP, "Patcher TTD og starter det patchede program %s\n"
	  "\n"
	  "Syntaks: TTDPATCH [-C cfg-fil] [parametre] [CD sti] [-W cfg-fil]\n"
	  "\n")

// Lines of help for all on/off switches, each at most 38 chars long.
// If you need more chars just insert another line.
TEXTARRAY(halflines,) =
	{ "-a:  Alle parametre pÜ nër -x",
	  "-d:  Vis altid den fulde dato",
	  "-f:  Gõr togenes last konfigurerbar",
	  "-g:  Generelle fejlrettelser",
	  "-k:  Behold smÜ lufthavne",
	  "-l:  Op til 7 parroner",
	  "-n:  Ny non-stop hÜndtering",
	  "-q:  Forbedret lësning/lodsningstids",
          "     algoritme",
	  "-s:  Tillad skilte-snydekoder ",
          "     (sign cheats)",
	  "-u:  Forbedre multiplayer spil",
	  "-v:  Vis parameterne med detaljer",
	  "-w:  Automatisk indstilling af ",
          "     fremskudt signal indstillinger",
	  "-y:  Skip ukendt versions spõrgsmÜl",
	  "-z:  Mammut tog (126 vogne)",

	  "-B:  Tillad lange broer",
	  "-D:  Dynamit kan sprënge flere ting",
	  "-E:  Flyt de rõde fejlmeddelelser",
	  "-F:  'Full load' (fuld last) betyder",
          "     'af en enkel lastttype'",
	  "-G:  Valgbare godstyper pÜ station",
	  "-H:  Tilpasbare brohoveder",
	  "-I:  Fjern inflation",
	  "-J:  Tillad flere lufthavne pr. by",
	  "-L:  LÜn/tilbagebetal max. med 'Ctrl'",
	  "-N:  Nyheder pÜ flere begivenheder",
	  "-O:  Kontorbygninger vil modtage mad",
	  "-P:  Lokomotiver i brug er blivende",
	  "-R:  Kõretõjer venter i kõ",
	  "-S:  Nye skibsmodeller",
	  "-T:  Nye tog modeller",

	  "-2:  Kompatibel med Windows 2000/XP",

	  "-Xb: Bestikkelse af lokale myndigheder",
	  "-Xd: Tilfõjelse af remiser pÜ togruten",
	  "-Xe: Uendeligt spil efter 2070",
	  "-Xf: Tvungen lodsning ved transport",
          "     mellem flere kõretõjer",
	  "-Xg: Gradvis lastning af fartõjer",
	  "-Xh: Nye slags huse i byerne",
	  "-Xi: Ingen industrier lukker pga. ",
          "     dÜrlig õkonomi",
	  "-Xl: Bygge kanaler og sluser",
	  "-Xm: Load mulighed i disk menu",
	  "-Xo: Skilte-snydekoder (sign cheats)",
          "     koste penge",
	  "-Xp: Ny ydelses beregning",
	  "-Xr: Genudregn altid TTDLOAD.OVL",
	  "-Xs: Vis hastighed i status bar",
	  "-Xw: Extra fremskudt signal opstëtning",
	  "-Xx: Gemmer og henter yderligere data",

	  "-XA: Tvunget auto-fornyelse med -Xa",
	  "-XB: Gõr det muligt at bygge mens spillet er sat pÜ pause",
	  "-XE: Elektrificerede jernbaner",
	  "-XF: Aktivere eksperimentielle dele",
	  "-XH: Gemmer+viser nyhedstelegrammer",
	  "-XI: Muliggõr rute bestemt signalering",
	  "-XL: Viser profit i kõretõjslisten",
	  "-XO: Muliggõr delte/kopieret ordre",
	  "-XP: Nye fly modeller",
	  "-XR: Nye kõretõjer",
	  "-XS: FÜ kontrol over AI tilskud",
	  "-XZ: Version med lavt",
          "     hukommelsesforbrug(3.5MB)",

	  "-Ya: Klassificering mere tolerant",
          "     overfor vognalder",
	  "-Yb: Bygge flere ting pÜ skrÜninger",
	  "-Yc: Sportyper har forskellig pris",
	  "-Yd: Nye brotyper",
	  "-Yg: Spillets hastighed kan ëndres",
	  "-Yh: Tillader hõje broer",
	  "-Ym: Tillad manuel sportype ëndring",
	  "-Yn: Nye stationstyper",
	  "-Ys: Togsignaler i samme side som",
          "     kõrselsretning",
	  "-Yt: Flere statistikker i byvinduet",
	  "-Yw: Hurtigere vognsalg",

	  "-YC: Byg direkte pÜ kyster",
	  "-YD: Udvider svërhedsgrads indstillingerne",
	  "-YF: Fõrst-ind, fõrst-ud lastning",
	  "-YH: Flere/nye genvejstaster",
	  "-YL: Hastighedsbegrënsning pÜ togvogne",
	  "-YN: Nye temaer for bynavne",
	  "-YP: Fly bevëger sig den viste hastig.",
	  "-YS: Semaforesignaler fõr 1975",

	  NULL
	};
SETARRAY(halflines);

// Text describing the switches with values.  The lines have to be shorter
// than 79 chars, excluding the "\n".  Start new lines if necessary.
SETTEXT(LANG_FULLSWITCHES, "\n"
	  "-e #:    Forõg maksimal afstand mellem stationsenheder\n"
	  "-i #:    Standard service interval i dage\n"
	  "-x #:    Udvid fartõjs fortegnelse til 850*#. Lës fõrst dokumentationen!\n"
	  "-mc #:   Ny hhv. bjerg(m) og kurve(c) hÜndtering\n"
	  "-trpb #: Forõg max antallet af hhv. tog (t), biler (r), fly(p) eller skibe(s) \n"
	  "-M #:    Tillad tog med forspand, sët hast.forõgelse i procent\n"
	  "-U #:    Muliggõr ny lokomotiv grafik uden brug af Ctrl.\n"
	  "-Xa #:   Forny automatisk fartõjer # mÜneder efter deres estimerede livsforlõb\n"
	  "-Xc #:   Kontroller hyppigheden af flystyrt\n"
	  "-Yr #:   índre tog/kõretõj kollisions type (1/2)\n"
	  "-Xt #:   Sët den maksimale bystõrrelse til\n"
	  "-Xv #:   Sorter kõretõjslisten og bestem opdateringstiden\n"
	  "-Xz #:   Trëkker vinduer sammen\n"
	  "-XC #:   Tillad flere valutaer, og vëlg hvordan valutaen skal vises\n"
	  "-XD #:   Vëlg hvilke katastrofer der mÜ indtrëffe\n"
	  "-XN #:   Nyhedstelegrammer i farver efter det givende Ür\n"
	  "-XM #:   Foren monorail og maglev sporsystemer\n"
	  "-XT #:   Bestem en ud af hvormange byer der skal vokse hurtigere og stõrre\n"
	  "-XX #:   Nye monorail og maglev brohastigheder, i procent af max loko.hastighed\n"
	  "-XY #:   Sët standard startÜr for nye vilkÜrlige (random) spil\n"
	  "-XW #:   Strëkker TTD's vindue til dette antal pixels (kun windows version)\n"
	  "-X1 #, -X2 #: max tid (i dage) et tog venter hhv ved en-vejs og to-vejs signaler\n"
	  "-Yf #:   Gõr gods tog tungere med den givende faktor\n"
	  "-Yl #:   Understyttelse og indstilling af musehjul (kun windows version)\n"
	  "-Yo #, -Zm #:   Kontrollere forskellige elementer i andre kontaker (jvf. dokumentation)\n"
	  "-Yp #:   Tillad plantning af mange trëer, vëlg plantemetode\n"
	  "-YA #:   Ubrugte veje mister deres ejer, indstillinger vëlges ved parametre\n"
	  "-YB #:   Flere bygge muligheder, vëlg mulighederne vha. parametre\n"
	  "-YE #:   Bestem hvor lënge (i sek.) de rõde fejlvinduer bliver vist\n"
	  "-YM #:   Vis flere (eller fërre) dampskyer, vërdier fastsëtter mëngden\n"
	  "-YG #:   Forbedre brugerfladen, vëlg mulighederne vha. parametre\n"
	  "-YO #:   Muliggõr snelinie i tempareret klima, og fastsëttelse af dens hõjde\n"
	  "-YR #:   Sëtter kortets opdateringsfrekvens til # per sekund\n"
	  "-YT #:   Bestem algoritmen der styrer byernes vëkst\n"
	  "-YW #:   Bestemmer maximum antal af Übne vinduer\n"
	  "\n"
	  "-C cfg-fil:  indlës denne konfigurationsfil i stedet for ttdpatch.cfg\n"
	  "-W cfg-fil:  laver en konfigurationsfil med nuvërende konfiguration\n"
	  "-Xn cfg-fil: Bruger denne fil som konfigurationsfil for nye grafiksët\n"
	  "\n"
	  "Husk, at store/smÜ bogstaver har vigtig betydning!\n"
	  "\n"
	  "Ekspempel:  ttdpatch -fnqz -m 00 -c 13 -trpb 240 -FG -A 2 -v\n"
	  "\n"
	  "(Hint:  Hvis der ikke er plads nok pÜ skërmen til at se alt hvad der blev udskrevet, skriv\"ttdpatch -h|more\")\n"
	  "\n")

// Referral to the docs, prefixed by "Copyright (C) 1999 by Josef Drexler.  "
SETTEXT(LANG_HELPTRAILER, "Se TTDPATCH.TXT for yderligere detaljer.\n")


//-----------------------------------------------
//  COMMAND LINE AND CONFIG FILE PARSING
//-----------------------------------------------

// if an on/off switch has a value other than the above (%s = wrong value)
SETTEXT(LANG_UNKNOWNSTATE, "Advarsel: Ukendt tënd/sluk status %s, sat til slukket.\n")

// switch is unknown.  %c is '-' or '/' etc, %s is the switch char
SETTEXT(LANG_UNKNOWNSWITCH, "Ukendt parameter '%c%s'.  Brug -h for hjëlp.\n")

// switch bit name is unknown.  First %s is bit name, 2nd is switch name
SETTEXT(LANG_UNKNOWNSWITCHBIT, "Ukendt bit '%s' for switch '%s'.\n")

// cfg command %s is unknown
SETTEXT(LANG_UNKNOWNCFGLINE, "Advarsel: Ulovlig cfg linie '%s'.\n")

// Names of the switches for the '-v' options
// First string is shown always, second only if set and with the given
// value of the switch in %d.
// These lines (both parts) are limited to 36 chars, also consider how large
// the expansion of the %d can be for that switch.
SWITCHTEXT(uselargerarray, "Udvid antallet af vogne", " til %d*850")
SWITCHTEXT(usenewcurves, "Ny kurve hÜndtering", " for %04x")
SWITCHTEXT(usenewmountain, "Ny bjerg hÜndtering", " for %04x")
SWITCHTEXT(usenewnonstop, "Ny non-stop hÜndtering", "")
SWITCHTEXT(increasetraincount, "Nyt tog antal", ": %d")
SWITCHTEXT(increaservcount, "Nyt bil antal", ": %d")
SWITCHTEXT(setnewservinterval, "Nyt std. service interval", ": %d dage")
SWITCHTEXT(usesigncheat, "Brug skilte-snydekoder (sign cheats)", "")
SWITCHTEXT(allowtrainrefit, "Tillad konfigurering af togenes last", "")
SWITCHTEXT(increaseplanecount, "Nyt fly antal", ": %d")
SWITCHTEXT(increaseshipcount, "Nyt skibs antal", ": %d")
SWITCHTEXT(keepsmallairports, "Behold smÜ lufthavne", "")
SWITCHTEXT(largerstations, "Forõg stationspredning", " til %d felter")
SWITCHTEXT(morestationtracks, "Udviddede stationer", "")
SWITCHTEXT(longerbridges, "Lëngere broer", "")
SWITCHTEXT(improvedloadtimes, "Forbedret lësnings tidsudregning", "")
SWITCHTEXT(mammothtrains, "Mammut tog (lëngde 127)", "")
SWITCHTEXT(presignals, "Set fremskudte signaler automatisk", "")
SWITCHTEXT(officefood, "Kontorbygninger vil modtage mad", "")
SWITCHTEXT(noinflation, "Fjern inflation", "")
SWITCHTEXT(maxloanwithctrl, "Max lÜn/tilbagebetal 'Ctrl'", "")
SWITCHTEXT(persistentengines, "Blivende lokomotiver hvis brugt", "")
SWITCHTEXT(fullloadany, "Full load gëlder for Çn lastttype", "")
SWITCHTEXT(selectstationgoods, "Valgbare godstyper pÜ station", " for %d dage")
SWITCHTEXT(morethingsremovable, "Flere ting kan fjernes/bortsprënges", "")
SWITCHTEXT(multihead, "Tog med forspand", ", hast.forõg.: %d%%")
SWITCHTEXT(newlineup, "Kõretõjsopmarchering i kõ", "")
SWITCHTEXT(lowmemory, "Lavhukommelsesversion (3.5MB)", "")
SWITCHTEXT(generalfixes, "Generelle fejlrettelser (se doku.)", "")
SWITCHTEXT(moreairports, "Flere lufthavne tilladt pr. by", "")
SWITCHTEXT(bribe, "Vis bestikkelses mulighed", "")
SWITCHTEXT(noplanecrashes, "Flystyrts hyppighedskontrol", ": %d")
SWITCHTEXT(showspeed, "Hvis hastighed i status bar", "")
SWITCHTEXT(autorenew, "Autoforny lokomotiver", " hver %d. mÜned")
SWITCHTEXT(cheatscost, "Skilte-snydekoder koster penge", "")
SWITCHTEXT(extpresignals, "Indstil fremskudte signaler med Ctrl", "")
SWITCHTEXT(diskmenu, "Vis hente muligheder i disk menu", "")
SWITCHTEXT(win2k, "Anvend Windows 2000/XP patches", "")
SWITCHTEXT(feederservice, "Fõdningsservice med tvungen lodsning", "")
SWITCHTEXT(gotodepot, "Tilfõj remiser til togruten", "")
SWITCHTEXT(newships, "Nye skibsmodeller", "")
SWITCHTEXT(subsidiaries, "FÜ kontrol over AI tilskud", "")
SWITCHTEXT(gradualloading, "Gradvis lastning af fartõjer", "")
SWITCHTEXT(moveerrorpopup, "Flyt de rõde fejlmeddelelser", "")
SWITCHTEXT(setsignal1waittime, "Nye togventetider ved signal", ":")
SWITCHTEXT(setsignal2waittime, "", "")				// dummy entry
SWITCHTEXT(maskdisasters, "Liste over katastrofer", ": %d")
SWITCHTEXT(forceautorenew, "Tvungen autofornyelse af lokomotiver", "")
SWITCHTEXT(morenews, "Nyheder om flere begivenheder", "")
SWITCHTEXT(unifiedmaglev, "Foren maglev", ", mode %d")
SWITCHTEXT(newbridgespeeds, "Max hastighed pÜ maglev-broer", ": %d%%")
SWITCHTEXT(eternalgame, "Uendeligt spil efter 2070", "")
SWITCHTEXT(showfulldate, "Vis altid den fulde dato", "")
SWITCHTEXT(newtrains, "Nye togmodeller", "")
SWITCHTEXT(newrvs, "Nye kõretõjer", "")
SWITCHTEXT(newplanes, "Nye flymodeller", "")
SWITCHTEXT(signalsontrafficside, "Signaler i 'kõrselsretningen'", "")
SWITCHTEXT(electrifiedrail, "Elektrificerede jernbaner", "")
SWITCHTEXT(newstartyear, "standard start Ür", ": %d")
SWITCHTEXT(newerrorpopuptime, "Ny fejlvindue visningstid", ": %d sec.")
SWITCHTEXT(newtowngrowthfactor, "Bestem byernes vëkst faktor", " to %d")
SWITCHTEXT(largertowns, "Stõrre byer", ", each 1 out of %d")
SWITCHTEXT(miscmods, "Forskellige ëndringer", ": %ld")
SWITCHTEXT(loadallgraphics, "Hent altid alle nye grafikelementer", "")
SWITCHTEXT(saveoptdata, "Gemmer og henter yderligere data", "")
SWITCHTEXT(morebuildoptions, "Flere byggemuligheder", ": %d")
SWITCHTEXT(semaphoresignals, "Semafore fõr 1975", "")
SWITCHTEXT(morehotkeys, "Flere/nye genvejstaster", "")
SWITCHTEXT(plantmanytrees, "Plant mange trëer", "")
SWITCHTEXT(morecurrencies, "Tillad flere valutaer", ", flags: %d")
SWITCHTEXT(manualconvert, "Tillad manuel sportype ëndring", "")
SWITCHTEXT(newtowngrowthrate, "Ny by vëkst algoritme", ": %d")
SWITCHTEXT(displmoretownstats, "Vis flere statistiker om byerne", "")
SWITCHTEXT(enhancegui, "Forbedret brugerflade i sillet", "")
SWITCHTEXT(newagerating, "Ratings bedre i forhld til vognalder", "")
SWITCHTEXT(buildonslopes, "Bygge flere ting pÜ skrÜninger", "")
SWITCHTEXT(buildoncoasts, "Byg direkte pÜ kyster", "")
SWITCHTEXT(experimentalfeatures, "Aktivere seneste eksperiment. dele", ": %u")
SWITCHTEXT(tracktypecostdiff, "Sportyper har forskellig pris", "")
SWITCHTEXT(planespeed, "Brug reele flyhastighed", ": %d/4")
SWITCHTEXT(fastwagonsell, "Hurtigere vognsalg", "")
SWITCHTEXT(newrvcrash, "índre tog/bil kollision"," (mode %d)")
SWITCHTEXT(stableindustry, "Forhindre industrilukninger","")
SWITCHTEXT(newperformance, "Ny ydelses beregning", "")
SWITCHTEXT(sortvehlist, "Sorter kõretõjslisterne", ", forsinkelse: %d")
SWITCHTEXT(showprofitinlist, "Vis profit i kõretõjslisten", "")
SWITCHTEXT(newspapercolour, "Nyhedstelegrammer er i farver", " after %d")
SWITCHTEXT(sharedorders, "Muliggõr delte/kopieret ordre", "")
SWITCHTEXT(moresteam, "Vis flere dampskyer", ": %x")
SWITCHTEXT(abandonedroads, "Ubrugte veje mister deres ejer", ", mode %d")
SWITCHTEXT(newstations, "Nye stationstyper", "")
SWITCHTEXT(buildwhilepaused, "Byg mens spillet er pÜ pause", "")
SWITCHTEXT(losttrains, "Advarsel om vildfarende tog", " efter %d dage")
SWITCHTEXT(lostrvs, "Advarsel om vildfarende kõretõjer", " efter %d dage")
SWITCHTEXT(lostships, "Advarsel om vildfarende skibe", " efter %d dage")
SWITCHTEXT(lostaircraft, "Advarsel om vildfarende fly", " efter %d dage")
SWITCHTEXT(maprefresh, "Nye korts opdateringsfrekvens", ": %d gange")
SWITCHTEXT(disconnectontimeout, "Afbryd et netvërkspil hvis der ikke er noget svar", " efter %d sek.")
SWITCHTEXT(moretoylandfeatures, "Tillader nogle tilfëldige bygniner i terrënet i Toyland", ": %d")
SWITCHTEXT(stretchwindow, "Strëkker TTD's vindue", " til %d pixels")
SWITCHTEXT(canals, "Byg kanaler og sluser", "")
SWITCHTEXT(higherbridges, "Tillad hõjere broer", "")
SWITCHTEXT(gamespeed, "Valdfri spilhastighed", ", start med %d")
SWITCHTEXT(freighttrains, "Gõr godstog tungere", " (x%d)")
SWITCHTEXT(mousewheel, "Tillad brug af musehjul",", indstilling: %d")
SWITCHTEXT(morewindows, "Forõg antallet af maximum vinduer", " til %d")
SWITCHTEXT(enhanceddiffsettings, "Udvid svërhedsgrads indstillingerne", "")
SWITCHTEXT(newbridges, "Nye broer", "")
SWITCHTEXT(newhouses, "Nye huse i byerne", "")
SWITCHTEXT(newtownnames,"Nye temaer for bynavne","")
SWITCHTEXT(moreanimation,"Tillad flere animerede felter",", op til %d")
SWITCHTEXT(newshistory, "Nyheds historier", "")
SWITCHTEXT(wagonspeedlimits, "Hastighedsbegrënsninger for togvogne", "")
SWITCHTEXT(pathbasedsignalling, "Rute bestemt signalering", "")
SWITCHTEXT(aichoosechances, "Bestem med hvilken sansynlighed AI bygger nye ruter", "")
SWITCHTEXT(custombridgeheads, "Mere funktionsdygtige brohoveder", "")
SWITCHTEXT(townbuildnoroads, "Byer bygger ingen veje", "")
SWITCHTEXT(newcargodistribution, "Forbedret varer distribution", "")
SWITCHTEXT(windowsnap, "Trëkker vinduer sammen", " NÜr de er tëttere end %d pixels")
SWITCHTEXT(resolutionwidth, "Oplõsningsbredde ", " %d pixels")
SWITCHTEXT(resolutionheight, "Oplõsningshõjde", " %d pixels")
SWITCHTEXT(newindustries, "Nye industrier", "")
SWITCHTEXT(locomotiongui, "Tillader ny lokomotiv grafik", "")
SWITCHTEXT(fifoloading, "Tillader fõrst-ind, fõrst-ud lastning", "");
SWITCHTEXT(tempsnowline, "Muliggõr snelinie i tempareret klima", "")
SWITCHTEXT(townroadbranchprob, "Hõjere sandsynlighed for sideveje", " til %d")
SWITCHTEXT(newcargos, "Tillader nye godstyper", "")
SWITCHTEXT(enhancemultiplayer, "Udvider netvërksspil (tillader flere spillere)", "")
SWITCHTEXT(newsounds, "Muliggõr tilfõjelsen af flere nye lydeffekter", "")
SWITCHTEXT(morestats, "Tillader visning af flere statistiske oplysninger", "")
SWITCHTEXT(onewayroads, "Tillader ensrettede gader ved brug af 'Ctrl'", "")
SWITCHTEXT(irrstations, "Tillader bygning af iregulëre stationer", "")
SWITCHTEXT(autoreplace, "Opgradere kõretõjer nÜr de bliver gamle", "; %d%% min. driftsikkerhed for ny model")
SWITCHTEXT(autoslope, "Tillader terrënëndringer uden at fjerne bygninger", "")
SWITCHTEXT(followvehicle, "Fõlg kõretõjets bevëgelse fra hovedkortet", "")
SWITCHTEXT(trams, "Tillader sporvogne pÜ vejene", "")
SWITCHTEXT(enhancetunnels, "Tillader bygning af spor ovenpÜ tunnelÜbninger", "")
SWITCHTEXT(forcegameoptions, "Gõr det muligt at gennemtvinge spil indstillinger","")

//---------------------------------------
//  BIT SWITCH DESCRIPTIONS
//---------------------------------------

// Beskrivelse af flystyrts bits
BITSWITCH(noplanecrashes)
BIT(normdis,      "Normale flystyrt deaktiveret hvis katastrofer er deaktvieret")
BIT(jetsdis,      "Jetflystyrt i smÜ lufthavne deaktiveret hvis katastrofer er deaktvieret")
BIT(normbrdown,   "Normale flystyrt men kun for fly med tekniske problemer, sandsynlighed * 4")
BIT(jetssamerate, "Samme sandsynlighed for jetflystyrt i smÜ lufthavne og normale flystyrt")
BIT(normoff,      "Normale flystyrt deaktiveret")
BIT(jetsoff,      "Jetflystyrt i smÜlufthavne deaktiveret")

// Description for miscmods bits
BITSWITCH(miscmods)
BIT(nobuildonbanks,        "Byer bygger ikke pÜ kystfelter")
BIT(servintonlyhuman,      "Serviceintervallet gëlder ikke AI spillere")
BIT(noroadtakeover,        "Byer gõr ikke krav pÜ alle vejfelter i scenarie redigeringsprogrammet")
BIT(gradualloadbywagon,    "Lastning af vogne en efter en fõrst")
BIT(dontfixlitres,         "índre ikke liter sÜ 1000 l er 1 ton istedet for 100 l")
BIT(dontfixtropicbanks,    "Bank typer bliver ikke ëndret i sub-tropisk klima")
BIT(dontfixhousesprites,   "Kontore som bliver vist som kirke bliver ikke ëndret")
BIT(oldtownterrmodlimit,   "Den dyreste pris for terrënëndringer for byer bliver ikke ëndret")
BIT(nozeppelinonlargeap,   "Zeppeliner styrter ikke ned pÜ store lufthavne")
BIT(nodefaultoldtracktype, "Brug ikke forgÜende spor type som standard")
BIT(usevehnnumbernotname,  "Kõretõjsnavne bliver ikke brugt i nyhedstelegrammer")
BIT(norescalecompanygraph, "Skalaen i virksomhedsgrafen biver ikke ëndre nÜr virksonheder bliver fravalgt")
BIT(noyearlyfinances,      "Vis ikke virksomhedsfinanser den 1. jan.")
BIT(notimegiveaway,        "Giver ikke processor kraft vëk til andre programmer")
BIT(nodesynchwarning,      "Giv ikke advarsel nÜr multiplayer spil ikke bliver synkroniseret")
BIT(noworldedgeflooding,   "Lav ikke bõlger langs kanten af kortet")
BIT(doshowintro,           "Vis spillet intro")
BIT(nonewspritesorter,     "Bruger ikke den nye grafik sorterings algoritme")
BIT(nodiagonalflooding,    "Deaktivere diagonale bõlger og hjõrne kystfelter")
BIT(noenhancedcomp,        "Brug ikke den forbedret algoritme nÜr der gemmes spil")
BIT(breakdownatsignal,     "Reparer ikke nedbrudte tog nÜr de holder for rõdt signal")
BIT(smallspritelimit,      "Grafik grënsen bliver ikke forhõjet")
BIT(displaytownsize,       "Hvis byens stõrrelse i navnet")
BIT(noextendstationrange,  "Forõg ikke den tilladte maximum afstand mellem stationer og industrier for godsleveringer")
BIT(nooldvehiclenews,      "Vis ikke beskeder om at kõretõjer er blevet for gamle")
BIT(dontfixpaymentgraph,   "X-aksen i vinduet der viser betalingsraten for levering af gods bliver ikke rettet")
//BIT(loaduntilgreen,        "Bliv ved med at laste ved stationen indtil udkõrselssignalet er grõnt")
BIT(dontshowaltitude,      "Vis ikke hõjden i feltinfovinduet")
BIT(nogrfidsinscreenshots, "Vis ikke aktive grf-id's i skërmprint")
BIT(dontchangesnow,        "MÜden mëgden af sne bliver beregnet pÜ bliver ikke ëndret")

// Description for morebuildoptions bits
BITSWITCH(morebuildoptions)
BIT(ctunnel,         "Tillader krydsende tunneler")
BIT(oilrefinery,     "Tillader olieraffinaderi overalt")
BIT(moreindustries,  "Tillader mere en Çn industri af den samme type")
BIT(removeobjects,   "Tillader rydning af statuer, fyrtÜrne og radiotÜrne")
BIT(removeindustry,  "Tillader rydning af industrier")
BIT(closeindustries, "Tillader at industrier af samme type kan ligge meget tët")
BIT(enhancedbuoys,   "Tillader bõjer der fungere som almindelige stationer")
BIT(bulldozesignals, "Rydautomatisk signaler nÜr 'bulldozeren' bliver brugt")

// Description for experimentalfeatures bits
BITSWITCH(experimentalfeatures)
BIT(slowcrossing, "Toge sëtter farten ved niveauskëringer (baneoverskëringer)")
BIT(cooperative,  "Kooperativt spil, meget begrënset")
BIT(mandatorygrm, "gõr 'GRF Resource Management' obligatorisk for .grf filer")

// Description for maskdisasters bits
BITSWITCH(maskdisasters)
BIT(zeppelincrash,      "Tillad zeppelin nedstyrtning")
BIT(smallufo,           "Tillad lille UFO")
BIT(refineryexplosion,  "Tillad raffinaderi eksplosioner")
BIT(factoryexplosion,   "Tillad fabrik eksplosioner")
BIT(largeufo,           "Tillad stor UFO")
BIT(smallsubmarine,     "Tillad lille ubÜd")
BIT(largesubmarine,     "Tillad stor ubÜd")
BIT(coalminesubsidence, "Tillad kul mine sammenstyrtning")

// Description for mousewheel bits
BITSWITCH(mousewheel)
BIT(cursorzoom, "Zoom ved musemarkõren istedet for centrum af skërmen")
BIT(safezoom,   "Zoom kun efter musehjulet er blevet rullet to hak")
BIT(legacy,     "Aktiver understõttelse for gamle operativsystemer og drivere (normalt ikke nõdvendigt)")

// Description for plantmanytrees bits
BITSWITCH(plantmanytrees)
BIT(morethanonepersquare,   "Tillad plantning af mere en tre trëer i hvert felt")
BIT(rectangular,            "Tillad plantning over et rektangulërt omrÜde med 'Ctrl'")
BIT(morethanonerectangular, "Ved brug af den rektangulëre plantnings funktion kan der plantes mere end tre trëer i hvert felt")

// Description for moretoylandfeatures bits
BITSWITCH(moretoylandfeatures)
BIT(lighthouses, "Tillader fyrtÜrne pÜ kystfelter i Toyland")
BIT(woodlands,   "Tillader skovomrÜder (grupper af trëer) i Toyland")

// Description for locomotiongui bits
BITSWITCH(locomotiongui)
BIT(usenewgui,      "Aktiverer den nye grafiske brugergrënseflade")
BIT(defaultnewgui,  "Brug den nye grafiske brugergrënseflade som standard (hvis aktiveret kan den gamle brugergrënseflade benyttet ved brug af 'Ctrl', og omvendt hvis deaktiveret)")
BIT(defaultstation, "Gõr at stations byggemenuen er i 'Locomotion' stil")

// Description for pathbasedsignalling bits
BITSWITCH(pathbasedsignalling)
BIT(autoconvertpresig,    "Konvertere indkõrsles-, udkõrsels- og kombisignaler om til sporbaseret signaler")
BIT(manualpbssig,         "Tillad manuel instilling af sporbaseret signaler")
BIT(preservemanualpresig, "KovertÇr ikke sporskifter med manuelt valgte signaltype til sporbaseret signaler")
BIT(showreservedpath,     "Vis de reserverede sporfelter mõrkere")
BIT(shownonjunctionpath,  "Vis reserverede sportfelter nÜr de ikke er sporskifter")
BIT(allowunsafejunction,  "Stands ikke toge ved usikre sporbaseret signaler")
BIT(allowunsafereverse,   "Stands ikke toge der ikke kan kõre sikkert baglëns")

// Description for newsounds bits
BITSWITCH(newsounds)
BIT(highfrequency, "(kun for DOS) Mixer lyde ved 22kHz i stedet de standard 11kHz. Tillader korrekt playback ved 22kHz samples")

// Description for morecurrencies bits
BITSWITCH(morecurrencies)
BIT(symbefore, "Valuta symbolet bliver altid vist fõr tallet")
BIT(symafter,  "Valuta symbolet bliver altid vist ")
BIT(noeuro,    "Euroen bliver ikke introduceret (õv!)")
BIT(comma,     "Komma bliver altid brugt til tusindtalsseperator")
BIT(period,    "Punktum bliver altid brugt til tusindtalsseperator")

// Description for forcegameoptions bits
BITSWITCH(forcegameoptions)
BIT(trafficleft,	"Tvinger trafikken til at kõre i venstre side af vejen")
BIT(trafficright,	"Tvinger trafikken til at kõre i hõjre side af vejen")
BIT(imperial,	"Bruger engelske miles som lëngdemÜl")
BIT(metric,		"Bruger kilometre som lëngdemÜl")
BIT(townsenglish,	"Giver byerne engelskklingende navne")
BIT(townsfrench,	"Giver byerne franskklingende navne")
BIT(townsgerman,	"Giver byerne tyskklingende navne")
BIT(townsamerican,	"Giver byerne nordamerikanskklingende navne")
BIT(townslatin,		"Giver byerne latinamerikanskklingende navne")
BIT(townssilly,		"Giver byerne skõre engelske navne")
BIT(autosavedisabled,	"Deaktivere den automatiske gemfunktion")
BIT(autosave3months,	"Sëtter den automatiske gemfunktion til hver 3. mÜned")
BIT(autosave6months,	"Sëtter den automatiske gemfunktion til hver 6. mÜned")
BIT(autosave12months,	"Sëtter den automatiske gemfunktion til hver 12. mÜned")


// A cfg file (%s) could not be found and is ignored.
SETTEXT(LANG_CFGFILENOTFOUND, "Kunne ikke finde cfg fil %s.  Ignoreret.\n")

// Couldn't write the config file
SETTEXT(LANG_CFGFILENOTWRITABLE, "Kunne ikke Übne %s for skrivning.\n")

// A non-comment line is longer than 32 chars, rest ignored.
SETTEXT(LANG_CFGLINETOOLONG, "Advarsel!  Linie i konfigurationen er lëngere end 32 karakterer, trunkeret.\n")

// Shown if an obsolete switch is used. First option is %s which is the
// config name, second one is %s which is the command line char
SETTEXT(LANG_SWITCHOBSOLETE, "Parametren `%s' (%s) er forëldet. UndgÜ venligst at bruge den.\n"
		"Den vil blive fjernet i fremtidige versioner.\n")

//---------------------------------------------------
//   CONFIG FILE COMMENTS (for '-W')
//---------------------------------------------------

// This is the intro at the start of the config file.  No constraints on line lengths.
SETTEXT(CFG_INTRO,
	CFG_COMMENT "\n"
	CFG_COMMENT "TTDPatch Konfigurations Fil, automatisk opbygget af TTDPatch -W filnavn.\n"
	CFG_COMMENT "(TTDPatch %s)\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Format for parametrene er:\n"
	CFG_COMMENT "   parameternavn = parametervërdi\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "\"=\"-tegnet og mellemrum kan udelades.  Forskel pÜ store/smÜ bogstaver ignoreres.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "For ja/nej [j/n] paramtetre, kan vërdien vëre en af:\n"
	CFG_COMMENT "   yes, y, on, 1, no, n, off, 0\n"
	CFG_COMMENT "Hvis der ikke er udfyldt noget for en ja/nej parameter, antages den standard til at vëre ja hvis intet er angivet.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "For parametre med vërdi mulighed [v], er intervallet beskrevet\n"
	CFG_COMMENT "i kommentarerne, lige som standardvërdien hvis ingen er angivet.  Parametren kan\n"
	CFG_COMMENT "slÜs fra ved at give den en af 'fra' vërdierne.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Kommentarer i linier startes med et tegn som ikke er et bogstav.\n"
	CFG_COMMENT "\n")

// Line before previously unset switches
SETTEXT(CFG_NEWSWITCHINTRO, "**** Nye kontakter ****")

// For switches which have no command line equivalent
SETTEXT(CFG_NOCMDLINE, "ikke en kommandolinie kontakt")

// 
// All can have a place holder %s to stand for the actual setting name,
// and all but CFG_CDPATH can have a %s *after* the %s for the command
// line switch.
// They will have the "comment" char and a space prefixed.
//
SETTEXT(CFG_SHIPS, "`%s' (%s) forõger max. antallet af skibe.  Intervallet er %ld..%ld.  Standard %ld.")
SETTEXT(CFG_CURVES, "`%s' (%s) Sëtter kurverhastighed til normal (0), hurtig (1), hurtigst (2) eller realistist (3). Et ciffer for hver jernbane, monorail, maglev og kõretõjer. Standard 0120.") 
SETTEXT(CFG_MOUNTAINS, "`%s' (%s) Sëtter bjerghastighed til normal (0), hurtig (1), hurtigst (2) eller realistist (3). Et ciffer for hver jernbane, monorail, maglev og kõretõjer. Standard 0120.")  
SETTEXT(CFG_SPREAD, "`%s' (%s) gõr det muligt at have stationsenheder spredt mere ud.  Interval  %ld..%ld.  Standard %ld.")
SETTEXT(CFG_TRAINREFIT, "`%s' (%s) gõr det muligt at omkonfigurere lasten pÜ lokomotiver.")
SETTEXT(CFG_SERVINT, "`%s' (%s) Tillader at sëtte fõrste service interval for nye lokomotiver.  Interval  %ld..%ld.  Standard %ld.")
SETTEXT(CFG_NOINFLATION, "`%s' (%s) fjerner inflation, bÜde for indtëgter og udgifter.")
SETTEXT(CFG_LARGESTATIONS, "`%s' (%s) tillader at give stationer flere perroner eller spor, op til 15x15.")
SETTEXT(CFG_NONSTOP, "`%s' (%s) fÜr \"Non-stop\" ordren til at opfõre sig anderledes.")
SETTEXT(CFG_PLANES, "`%s' (%s) forõger max antal fly.  Interval %ld..%ld.  Standard %ld.")
SETTEXT(CFG_LOADTIME, "`%s' (%s) giver en anderledes udregning af tid for lësning/lodsning.")
SETTEXT(CFG_ROADVEHS, "`%s' (%s) forõger max antal kõretõjer.  Interval  %ld..%ld.  Standard %ld.")
SETTEXT(CFG_SIGNCHEATS, "`%s' (%s) tillader skiltesnydekoder (sign cheats).")
SETTEXT(CFG_TRAINS, "`%s' (%s) forõger max antal tog.  Interval  %ld..%ld.  Standard %ld.")
//*#define CFG_PLAYERS "`%s' (-%s) sëtter hvilke(n) spiller(e) der skal pÜvirkes af snydekoderne.  Det er en liste af spillere i intervallet  0..7"
SETTEXT(CFG_VERBOSE, "`%s' (%s) viser opsummering af parametre inden TTD startes.")
SETTEXT(CFG_PRESIGNALS, "`%s' (%s) Sëtter fremskudte signaler ('pre-signals') op automatisk for at forbedre stationshÜndtering.")
SETTEXT(CFG_MOREVEHICLES, "`%s' (%s) forõger max antal fartõjer til vërdi*850.  Interval  %ld..%ld.  Standard %ld.")
SETTEXT(CFG_MAMMOTHTRAINS, "`%s' (%s) tillader mammut tog med op til 126 vogne.")
SETTEXT(CFG_FULLLOADANY, "`%s' (%s) fÜr tog til at forlade stationen hvis vogne til hvilken som helst godstype er fyldt.")
SETTEXT(CFG_SELECTGOODS, "Med `%s' (%s) ankommer gods kun nÜr der fõrste gang har vëret forsõgt at hente denne type fra den givne station, and disappear after the given number of days if the service stops.  Specifying 2 means goods never disappear.  Range: %ld..%ld.  Default: %ld.")
SETTEXT(CFG_DEBTMAX, "`%s' (%s) tillader at betale/lÜne max belõb ved at holde 'Ctrl' tasten nede.")
SETTEXT(CFG_OFFICEFOOD, "`%s' (%s) fÜr kontorbygninger til at modtage mad (tropiske/arktiske scenarier).")
SETTEXT(CFG_ENGINESPERSIST, "`%s' (%s) sõrger for, at lokomotivtyper er tilgëngelige, sÜ lënge mindst en af denne type er i drift.")
SETTEXT(CFG_CDPATH, "`%s' (%s) indstiller CD stien.")
// 
SETTEXT(CFG_KEEPSMALLAP, "`%s' (%s) sõrger for, at man altid kan bygge smÜ lufthavne.")
SETTEXT(CFG_LONGBRIDGES, "`%s' (%s) tillader broer med op til 127 felters lëngde.")
SETTEXT(CFG_DYNAMITE, "`%s' (%s) tillader, at flere ting kan fjernes med dynamit.")
SETTEXT(CFG_MULTIHEAD, "`%s' (%s) tillader et arbitrërt antal lokomotiver pÜ et tog. Kõb ekstra lokomotiver med 'Ctrl'.  Parameter er max hastighedsforõgelse pr. lokomotiv, i procent fra %ld-%ld, standard %ld%%.")
SETTEXT(CFG_RVQUEUEING, "`%s' (%s) tillader, at kõretõjer stiller sig i kõ ved en station, i stedet for at vende om.")
SETTEXT(CFG_LOWMEMORY, "`%s' (%s) tillader TTDPatch at kõre med 3.5MB hukommelse, men reducerer max udviddelsen af antal kõretõjer med 2(*850).")
SETTEXT(CFG_GENERALFIXES, "`%s' (%s) retter diverse forskellige smÜting, se dokumentationen for yderligere detaljer.")
SETTEXT(CFG_MOREAIRPORTS, "`%s' (%s) tillader at man kan bygge flere lufthavne end de normale to pr. by.")
SETTEXT(CFG_BRIBE, "`%s' (%s) tillader at bestikke de lokale myndigheder, dette er et nyt menu punkt under lokale myndigheder (local authorities).")
SETTEXT(CFG_PLANECRCTRL, "`%s' (%s) tillader kontrol med, hvornÜr/tit fly styrter.")
SETTEXT(CFG_SHOWSPEED, "`%s' (%s) viser hastigheden for fartõjer i status baren i deres vindue.")
SETTEXT(CFG_AUTORENEW, "`%s' (%s) fornyer automatisk lokomitiver nÜr de bliver alt for gamle (very old).  Interval  %ld..%ld.  Standard %ld.")
SETTEXT(CFG_CHEATSCOST, "`%s' (%s) sõrger for, at det koster penge, nÜr skiltesnydekoder (sign cheats) bruges.")
SETTEXT(CFG_EXTPRESIGNALS, "`%s' (%s) giver mulighed for at skifte mellem normale, fremskude, udlõbs- og kombinerede signaler med 'Ctrl'.")
SETTEXT(CFG_FORCEREBUILDOVL, "`%s' (%s) sõrger for, at TTDPatch genkompilerer TTDLOAD.OVL eller TTDLOADW.OVL hver gang programmet startes.")
SETTEXT(CFG_DISKMENU, "`%s' (%s) tilfõjer et Hent (Load) menupunkt til disk menuen, og en hent spil (eller gem spil med 'Ctrl' til scenarie opbygningsprogrammet.")
SETTEXT(CFG_WIN2K, "`%s' (%s) gõr Windows versionen af TTD kompatibel med Windows 2000/XP.")
SETTEXT(CFG_FEEDERSERVICE, "`%s' (%s) modificerer tvungen lodsning og profit pÜ en station sÜ godset kan forlade stationen i stedet for at give indtëgt lige nu og her.")
SETTEXT(CFG_GOTODEPOT, "`%s' (%s) tillader at tilfõje en remise/garage/dok til fartõjers ordrer.")
SETTEXT(CFG_NEWSHIPS, "`%s' (%s) ëndrer skibsmodellerne og giver flere mulige skibe og flere mulige ombygningsmuligheder (refit).")
SETTEXT(CFG_SUBSIDIARIES, "`%s' (%s) tillader dig at styre AI firmaer hvis du ejer 75%% af aktierne.")
SETTEXT(CFG_GRADUALLOADING, "`%s' (%s) ëndrer mÜden fartõjer lësses til en mere realistisk og gradvis metode (aktiverer ogsÜ ladetid, `loadtime').")
SETTEXT(CFG_MOVEERRORPOPUP, "`%s' (%s) flytter alle rõde fejlmeddelelser til õverste hõjre hjõrne.")
SETTEXT(CFG_SIGNAL1WAITTIME, "`%s' (%s) ëndre det antal dage et tog venter ved et en-vejssignal fõr det vender om. Interval 0..254, eller  255 for at venter evigt.")
SETTEXT(CFG_SIGNAL2WAITTIME, "`%s' (%s) ëndre det antal dage et tog venter ved et to-vejssignal fõr det vender om. Interval 0..254, eller  255 for at venter evigt.")
SETTEXT(CFG_DISASTERS, "`%s' (%s) tillader valg af hvilke katastrofer der mÜ indtrëffe.")
SETTEXT(CFG_FORCEAUTORENEW, "`%s' (%s) tvinger et kõretõj til vërksted nÜr det er tid til auto-fornyelse (jvf `autorenew').")
SETTEXT(CFG_MORENEWS, "`%s' (%s) genere beskeder/nyheder om flere begivenheder, se ogsÜ dokumentationen for mere information.")
SETTEXT(CFG_UNIFIEDMAGLEV, "`%s' (%s) gõr det muligt at kõbe monorail lokomotiver i maglev depoter og omvendt. indstilling: 1 - ëndre alle maglev lokomotiver til monorail; 2 - ëndre alle monorail lokomotiver til maglev; 3 - holder monorail og maglev adskilt.")                                         
SETTEXT(CFG_BRIDGESPEEDS, "`%s' (%s) ëndre hastigheden pÜ monorail og maglev rõrbroer til denne procentdel af den hõjeste lokomotivhastighed i dens klasse. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_ETERNALGAME, "`%s' (%s)  tallader uendelige spil - datoen bliver ikke nulstillet efter 2070.")
SETTEXT(CFG_SHOWFULLDATE, "`%s' (%s) vis altid den fulde dato i statusbaren, og ikke kun nÜr spillet bliver sat pÜ pause.")
SETTEXT(CFG_NEWTRAINS, "`%s' (%s) aktivere nye togmodeller med nye grafikellementer.")
SETTEXT(CFG_NEWRVS, "`%s' (%s) aktivere nye kõretõjsmodeller med nye grafikellementer.")
SETTEXT(CFG_NEWPLANES, "`%s' (%s) aktivere nye flymodeller med nye grafikellementer.")
SETTEXT(CFG_SIGNALSONTRAFFICSIDE, "`%s' (%s) viser jernbaresignaler i samme side som kõretõjerne kõrer.")
SETTEXT(CFG_ELECTRIFIEDRAIL, "`%s' (%s) fjerne et af de magnetiske sporsystemer (monorail eller maglev) og erstatter det med et elektrificeret jernbane system.")
SETTEXT(CFG_STARTYEAR, "`%s' (%s) bestemmer det normale startÜr for vilkÜrlige (random) spil og giver stõrre muligheder for startÜr i scenario editoren. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_ERRORPOPUPTIME, "`%s' (%s) ëndre det tidsrum de rõde popup vinduer bliver vist. Interval 1..255 (i sekunder) , eller 0 for meget lang tid. Standard 10.")
SETTEXT(CFG_TOWNGROWTHLIMIT, "`%s' (%s) ëndre den faktor der betemmer hvor store byer kan blive. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_LARGERTOWNS, "`%s' (%s) gõr at en by ud af den givne antal, vokser huritgere og stõrre (tilfõjer ogsÜ `towngrowthlimit'). Interval %ld..%ld. Standard %ld (1 ud af 4 byer).") 
SETTEXT(CFG_MISCMODS, "`%s' (%s) gõr det muligt at ëndre effekten af andre kontakter, se dokumentation for mere info.")
SETTEXT(CFG_LOADALLGRAPHICS, "`%s' (%s) tvinger TTDPatch til at hente alle .grf filer i newgrf(w).cfg, uanset om de har vëret brugt fõr i spillet eller ej.")
SETTEXT(CFG_SAVEOPTDATA, "`%s' (%s) gõr at TTDPatch gemmer og henter yderligere (valgfrit) data i slutningen af de gemte spil.")
SETTEXT(CFG_MOREBUILDOPTIONS, "`%s' (%s) giver flere bygge muligheder.")
SETTEXT(CFG_SEMAPHORES, "`%s' (%s) ëndre nye signaler bygget fõr 1975 til semafore signaler.")
SETTEXT(CFG_MOREHOTKEYS, "`%s' (%s) aktivere nye genvejstaster.")
SETTEXT(CFG_MANYTREES, "`%s' (%s) tillader plantning af mere end et trë i hvert felt, eller over et retangulërt omrÜder vha Ctrl.")
SETTEXT(CFG_MORECURRENCIES,"`%s' (%s) giver flere valutaer og Euroen.")
SETTEXT(CFG_MANCONVERT,"`%s' (%s) tillader manuel sporëndring ved at placere de nye spor ovenpÜ de eksisterende spor.")
SETTEXT(CFG_NEWAGERATING, "`%s' (%s) gõr stationsandelen (ratings) mere tolerent overfor vognalder. Nu kan vogenen vëre 21 istedet for 3 Ür gamle.")
SETTEXT(CFG_ENHANCEGUI,"`%s' (%s) forbedre brugergrënsefladen.")
SETTEXT(CFG_TOWNGROWTHRATEMODE, "`%s' (%s) gõr det muligt at definere reglerne der ligger til grund for udregningen af udvidelseshastigheden for byer. Indstilling: 0 - TTD original, 1 - TTD udvidet, 2 - personlig. Jvf. dokumentationen.")
SETTEXT(CFG_TOWNGROWTHRATEMIN, "`%s' (%s) definere den mindste voksehastighed for byer, ved nye huse per Ürhundrede. Kun aktiv hvis `towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TOWNGROWTHRATEMAX, "`%s' (%s) definere den stõrste voksehastighed for byer, ved nye huse per Ürhundrede. Kun aktiv hvis `towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRACTSTATIONEXIST, "`%s' (%s) definere hvor meget tilstedevërelsen af en aktiv station betyder for byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRACTSTATIONS, "`%s' (%s) definere hvor meget hver aktive station styrker byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRACTSTATIONSWEIGHT, "`%s' (%s) definere hvor effektivt aktive stationer medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRPASSOUTWEIGHT, "`%s' (%s) definere hvor effektivt transporterede passagere medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRMAILOUTWEIGHT, "`%s' (%s) definere hvor effektivt transporterede post medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRPASSINMAX, "`%s' (%s) definere det maximum antal af ankomne passagere der kan  medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRPASSINWEIGHT, "`%s' (%s) definere hvor effektivt ankomne passagere medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRMAILINOPTIM, "`%s' (%s) definere den optimale befolkning per hver 2 sëkke post af ankommen post (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRMAILINWEIGHT, "`%s' (%s) definere hvor effektivt ankommen post medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRGOODSINOPTIM, "`%s' (%s) definere den optimale befolkning per hver 2 kasse af ankommen gods (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRGOODSINWEIGHT, "`%s' (%s) definere hvor effektivt ankommen gods medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRFOODINMIN, "`%s' (%s) definere det minimum madbehov for byer i sne- eller õrkenomrÜder, i befolkning per 2 tons af ankommen mad (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRFOODINOPTIM, "`%s' (%s) definere den optimale befolkning per hver 2 tons af ankommen mad (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRFOODINWEIGHT, "`%s' (%s) definere hvor effektivt ankommen mad medvirker til byens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRWATERINMIN, "`%s' (%s) definere det minimum vandbehov for byer i õrkenomrÜder, i befolkning per 2 tons (2.000 liter) af ankommen vand (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRWATERINOPTIM, "`%s' (%s) definere den optimale befolkning per hver 2 tons (2.000 liter) af ankommen vand i det sub-tropiske klima (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRWATERINWEIGHT, "`%s' (%s) definere hvor effektivt ankommen vand medvirker til byens vëkst i det subtropiske klima (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRSWEETSINOPTIM, "`%s' (%s) definere den optimale befolkning per hver 2 sëkke af ankommen slik (sweets) i legetõjsland klimaet (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRSWEETSINWEIGHT, "`%s' (%s) definere hvor effektivt ankommen slik (sweets) medvirker til byens vëkst i legetõjsland klimaet (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRFIZZYDRINKSINOPTIM, "`%s' (%s) definere den optimale befolkning per hver 2 ankommen sodavand (fizzy drinks) i legetõjsland klimaet (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRFIZZYDRINKSINWEIGHT, "`%s' (%s) definere hvor effektivt ankommen sodavand (fizzy drinks) medvirker til byens vëkst i legetõjsland klimaet (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRTOWNSIZEBASE, "`%s' (%s) definere det basis antal af bygninger i byen for beregningen der involvere `tgrtownsizefactor' (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld.")
SETTEXT(CFG_TGRTOWNSIZEFACTOR, "`%s' (%s) definere hvor meget byens stõrrelse betyder for dens vëkst (jvf dokumentation for mere information). Kun aktiv hvis towngrowthratemode' er sat til 2. Interval %ld..%ld. Standard %ld (svare til 25%% indflydelse (63/255)).")
SETTEXT(CFG_TOWNMINPOPULATIONSNOW, "`%s' (%s) definere den mindste befolkning som byer i sne-omrÜder kan vokse til uden madforsyninger. Kun aktiv hvis `towngrowthratemode', `towngrowthlimit' eller `generalfixes' er slÜet til. Interval %ld..%ld. Standard %ld.") 
SETTEXT(CFG_TOWNMINPOPULATIONDESERT, "`%s' (%s) definere den mindste befolkning som byer i õrken-omrÜder kan vokse til uden mad- og vandforsyninger. Kun aktiv hvis `towngrowthratemode', `towngrowthlimit' eller `generalfixes' er slÜet til. Interval %ld..%ld. Standard %ld.") 
SETTEXT(CFG_MORETOWNSTATS, "With `%s' (%s) Yderligere statistiker bliver vist i byens informationsvindue.")
SETTEXT(CFG_BUILDONSLOPES, "`%s' (%s) gõr det muligt at bygge spor, veje og stationer pÜ skrÜninger, pÜ et fundament ligesom husene.")
SETTEXT(CFG_BUILDONCOASTS, "`%s' (%s) gõr det muligt at bygge pÜ kyster og flodsider uden fõrst at skulle bruge dynamit-vërktõjet.")
SETTEXT(CFG_TRACKTYPECOSTDIFF, "`%s' (%s) giver forskellige sporsystemer forskellige priser.")
SETTEXT(CFG_EXPERIMENTALFEATURES, "`%s' (%s) aktivere seneste eksperimentielle dele.")
SETTEXT(CFG_PLANESPEED, "`%s' (%s) gõr at fly bevëger sig den hastighed der er vist, og ikke det kvarte, og reducere hastigheden til 5/8 i tilfëlde af nedbrud.  OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_FASTWAGONSELL, "`%s' (%s) giver hurtigere vognsalg vha. Ctrl")
SETTEXT(CFG_NEWRVCRASH,"`%s' (%s) ëndre tog/kõretõj kollisioner. 1 gõr at toget byder ned efter kollisionen. 2 afskaffer tog/kõretõj kollisioner. Standard: type 1.");
SETTEXT(CFG_STABLEINDUSTRY,"`%s' (%s) modvirker industrilukninger hvis õkonomien er sat til rolig (Steady) i svërhedsgrad indstillingerne");
SETTEXT(CFG_NEWPERF, "`%s' (%s) giver en mere realistisk ydelsesberegning mht. kõretõjernes indtjening")
SETTEXT(CFG_SORTVEHLIST, "`%s' (%s) sortere kõretõjerne i kõretõjslisten. Parametret bestemmer hvor tid der skal gÜ mellem to opdateringer. Lavere vërdi giver hurtigere opdateringer, men krëver mere processorkraft. Vërdien 10 svëre cirka til en dag i spillet. OmrÜde %ld..%ld. Standardvërdi %ld.") 
SETTEXT(CFG_NEWSPAPERCOLOUR, "`%s' (%s) gõr at nyhedstelegrammer udkommer i farver de givende Ür. OmrÜde %ld..%ld. Standardvërdi %ld.")
SETTEXT(CFG_SHAREDORDERS, "`%s' (%s) tillader delte eller kopierede ordre.")
SETTEXT(CFG_SHOWPROFITINLIST, "`%s' (%s) giver en farvetkodet visning af profit i kõretõjslisten.")
SETTEXT(CFG_MORESTEAM, "`%s' (%s) viser flere (eller fërre) dampskyer pÜ damlokomotiver. Parametret har to cifre, det fõrste bestemmer lëngden af dampskyen, det andet antallet af skyer, hvor 2 er TTD's standardvërdi. Ved at lëgge en til eller fra kan fordoble eller halvere lëngden eller antallet. omrÜde %02lx..%02lx.  Standardvërdi %02lx.")
SETTEXT(CFG_ABANDONEDROADS, "`%s' (%s) gõr at veje mister deres ejer efter et stykke hvis de ligger ubrugte hen, og dermed gõr det muligt at fjerne dem. Man kan pÜ den mÜde ogsÜ fÜ ejerskab over veje uden ejer hvis man begynder at bruge dem. Ved vërdi 0 kan alle veje miste deres ejer, ved vërdi 1 kan nërliggende byer overtage ejerskabet hvis vejene ligger ubenyttede hen og ved vërdi 2 overtager byerne ejerskabet med det samme.")
SETTEXT(CFG_NEWSTATIONS, "`%s' (%s) aktivere grafikken til de nye stationer.")
SETTEXT(CFG_BUILDWHILEPAUSED, "`%s' (%s) tillader alt byggeri ogsÜ nÜr spillet er sat pÜ pause.")
SETTEXT(CFG_TRAINLOSTTIME, "`%s' (%s) giver en advarsel hvis et tog er faret vild efter det givende antal dage. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_RVLOSTTIME, "`%s' (%s) giver en advarsel hvis en lastbil/bus er faret vild efter det givende antal dage. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_SHIPLOSTTIME, "`%s' (%s) giver en advarsel hvis et skib er faret vild efter det givende antal dage. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_AIRCRAFTLOSTTIME, "`%s' (%s) giver en advarsel hvis et fly er faret vild efter det givende antal dage. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_MAPREFRESH, "`%s' (%s) giver en anden opdateringsfrekvens pÜ kortet i stedet for TTD's standardvërsdi pÜ 64. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_NETWORKTIMEOUT, "`%s' (%s) afbryder et netvërkspil hvis der ikke er noget svar i det givende antal sekunder. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_TOYLANDFEATURES, "`%s' (%s) aktivere nogle tilfëldige bygninger i terrënet fx. fyrtÜrn, som normalt er deaktiveret i Toyland.")
SETTEXT(CFG_STRETCHWINDOW, "`%s' (%s) strëkker TTD vinduer til givne antal horisontale pixels (kun nÜr TTD bliver vist i et vindue i Windows). OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_CANALS, "`%s' (%s) tillader at man kan bygge kanaler og sluser ved brug af 'buy land' knappen fra skips konstruktionsmenuen.")
SETTEXT(CFG_FREIGHTTRAINS, "`%s' (%s) ganger godsmëngden for godstoge med den givende faktor, for at simulere meget lange godstoge. Parametre har kun indflydelse pÜ togets accelaration, ikke hvor meget gods godstoget reelt transportere. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_GAMESPEED, "`%s' (%s) gõr det muligt at ëndret spillet hastighed. Krëver at genvejstast patchen er installeret. Ved at trykke 'q' forõges hastigheden med en faktor 2 (til max 8x hastigheden). ved at trykke 'w' kan den sënkes igen. Parametret er starthastigheden. OmrÜde %ld..%ld.  Standardvërdi %ld.") 
SETTEXT(CFG_HIGHERBRIDGES, "`%s' (%s) tillader konstruktion af hõjere broer.")
SETTEXT(CFG_NEWGRFCFG, "`%s' (%s) vëlger konfigurationsfilen for de nye grafik sët.")
SETTEXT(CFG_MOUSEWHEEL, "`%s' (%s) gõr det muligt at bruge musehjulet i Windows versionen.")
SETTEXT(CFG_MOREWINDOWS, "`%s' (%s) gõr det muligt at have flere vinduer Übne samtidigt. TTD's stadardvërdi er 10, men 3 pladser er allerede optaget (hovedvërktõjslinien, det store kort, statusbaren), sÜ det reele antal er 7. Rullemenuer og nyheder tëller ogsÜ som vinduer.  OmrÜde %ld..%ld. Standardvërdi %ld.")
SETTEXT(CFG_ENHANCEDDIFFICULTYSETTINGS, "'%s' (%s) gõr det muligt at vëlge 'ingen' ('none') under antal industrier i svërhedsgradsindstillingerne.")
SETTEXT(CFG_NEWBRIDGES, "`%s' (%s) aktivere nye grafikker for broer.")
SETTEXT(CFG_NEWHOUSES, "`%s' (%s) aktiverer nye slags grafik for bygninger i byer med de nye grafiksët.")
SETTEXT(CFG_NEWTOWNNAMES, "`%s' (%s) tillader muligheden for selv at lave bynavne i 'random games' via en ny grf-fil.")
SETTEXT(CFG_MOREANIMATION, "`%s' (%s) tillader en stigning i antallet af felter som kan vëre animeret. TTD's standard er 256. OmrÜde %ld..%ld.  Standardvërdi %ld.")
SETTEXT(CFG_NEWSHISTORY, "`%s' (%s) gõr det muligt at gemme og vise nyhedstelegrammer.")
SETTEXT(CFG_WAGONSPEEDLIMITS, "`%s' (%s) gõr det muligt at sëtte en hastighedsbegrënsning for tog vogne.")
SETTEXT(CFG_PATHBASEDSIGNALLING, "`%s' (%s) aktiverer sporbaseret signaler. Vër venlig at lëse manualen FùR du aktivrer denne funktion, da den er lidt svër at bruge korrekt (manualen er desvërre ikke oversat).") 
SETTEXT(CFG_CUSTOMBRIDGEHEADS, "`%s' (%s) gõr det muligt at bygge tilpassede brohoveder.")
SETTEXT(CFG_TOWNBUILDNOROADS, "`%s' (%s) byer bygger ingen veje.")
SETTEXT(CFG_NEWCARGODISTRIBUTION, "`%s' (%s) er en forbedret gods distribution.")
SETTEXT(CFG_WINDOWSNAP, "`%s' (%s) rykker vinduer sammen, nÜr det er tët pÜ hinanden. Range %ld..%ld. Default %ld.")
SETTEXT(CFG_RESOLUTIONWIDTH, "`%s' (%s) aktiverer og bestemmer bredden af oplësningen i patchen.")
SETTEXT(CFG_RESOLUTIONHEIGHT, "`%s' (%s) aktiverer og bestemmer hõjden af oplësningen i patchen.")
SETTEXT(CFG_AICHOOSECHANCES, "`%s' (%s) bestemmer sandsynligheden for hvad AI bygger som det nëste (sandsynligheden for en skipsrute er 1-sandsynligheden for en togrute-sandsynligheden for en vejrute-sandsynligheden for en flyrute).")
SETTEXT(CFG_AIBUILDRAILCHANCE, "`%s' (%s) er sandsynlighed for at AI bygger en togrute som den nëste rute. OmrÜde %ld..%ld, 0=0%%, 65535=100%%. Standardvërdi %ld.")
SETTEXT(CFG_AIBUILDRVCHANCE, "`%s' (%s) er sandsynlighed for at AI bygger en lastbils- eller busrute som den nëste rute. OmrÜde %ld..%ld, 0=0%%, 65535=100%%. Standardvërdi %ld.")
SETTEXT(CFG_AIBUILDAIRCHANCE, "`%s' (%s) er sandsynlighed for at AI bygger en flyrute som den nëste rute. OmrÜde %ld..%ld, 0=0%%, 65535=100%%. Standardvërdi %ld.")
SETTEXT(CFG_NEWINDUSTRIES, "`%s' (%s) aktivere understõttelse af nye industrytyper.")
SETTEXT(CFG_LOCOMOTIONGUI, "`%s' (%s) aktivere ny lokomotiv grafik.")
SETTEXT(CFG_FIFOLOADING, "`%s' (%s) aktivere fõrst ind/fõrst ud lastning.")
SETTEXT(CFG_TEMPSNOWLINE, "`%s' (%s) gõr at der vises sne i tempereret klima (den pÜgëldende grf-fil er nõdvendig fõr der kan vises sne).")
SETTEXT(CFG_TOWNROADBRANCHPROB, "`%s' (%s) ëndre sandsynligheden for at en by bygger en sidevej. 0 betyder ingen sideveje, 65535 betyder sideveje overalt hvor det er muligt. TTD's standardvërdi er 26214. OmrÜde %ld..%ld. Standardvërdi %ld.")
SETTEXT(CFG_NEWCARGOS, "`%s' (%s) aktiverer understõttelse for nye godstyper.")
SETTEXT(CFG_ENHMULTI, "`%s' (%s) forbedre multiplayer spil ved at tillade flere menneskelige spillere.")
SETTEXT(CFG_ONEWAYROADS, "`%s' (%s) gõr det muligt at bygge ensretede gader.")
SETTEXT(CFG_NEWSOUNDS, "`%s' (%s) tillader tilfõjelse af lyde til spillet ved skrëddersyede grf-filer.")
SETTEXT(CFG_IRRSTATIONS, "`%s' (%s) tillader at man kan bygge stationer med irregulëre former.")
SETTEXT(CFG_MORESTATS, "`%s' (%s) gõr det muligt at vise flere statistikker (virker kun sammen med enhancegui-patchen er aktiveret).")
SETTEXT(CFG_AUTOREPLACE, "`%s' (%s) opgrader kõretõjer til den nyeste model med den laveste laveste driftsikkerhed. OmrÜde 1..100. Standardvërdi 80.")
SETTEXT(CFG_AUTOSLOPE, "`%s' (%s) tillader at man kan ëndre terrënet uden er ryde evt. bygninger.")
SETTEXT(CFG_FOLLOWVEHICLE, "`%s' (%s) tillader at hovedvinduet kan fõlge et kõretõj ved et klik med hõjre museknap pÜ 'Center Viev'-knappen i kõretõjsvinduet.")
SETTEXT(CFG_TRAMS, "`%s' (%s) tillader at man kan bygge sporvogne.")
SETTEXT(CFG_ENHANCETUNNELS, "`%s' (%s) tillader at man kan bygge spor henover tunnelÜbninger.")
SETTEXT(CFG_FORCEGAMEOPTIONS, "`%s' (%s) gõr det muligt at gennemtvinge spil indstillinger.")


//----------------------------------------------------
//   SWITCH DISPLAY ('-v')
//----------------------------------------------------

// Wait for a key before displaying the switches
SETTEXT(LANG_SWWAITFORKEY, "\nTryk Enter for at kõrer TTD, Escape for at annullere, eller en vilkÜrlig tast for at vise indstillingerne.")

// Introduction
SETTEXT(LANG_SHOWSWITCHINTRO, "    Benyttede parametre:   (%c tëndt, %c slukket)\n")

// Five characters: vertical line for the table; enabled switch; disabled switch;
// table heading; table heading column separator.
SETTEXT(LANG_SWTABLEVERCHAR, "≥*˙ƒ¬")

// 1-way and 2-way captions after "Nye togventetider vej rõdt signal"
SETTEXT(LANG_SWONEWAY, "en-vejs: ")
SETTEXT(LANG_SWTWOWAY, "To-vejs: ")

// Train wait time is either in days or infinite
SETTEXT(LANG_TIMEDAYS, "%d dag(e)")
SETTEXT(LANG_INFINITETIME, "uendeligt")

// Shows the keys to scroll the verbose switch table
SETTEXT(LANG_SCROLLKEYS, " Taster: Op Ned PageUp PageDown Home End ")

// ... and to abort TTDPatch
SETTEXT(LANG_SCROLLABORTKEY, " Escape = afbryd ")


// Shows the load options for ttdload.  %s is the given parameters to be passed to ttdload
SETTEXT(LANG_SWSHOWLOAD, "Enter/Mellemrum = kõr \"TTDLOAD %s\"")

SETTEXT(LANG_SWABORTLOAD, "\nProgram indlësning afbrudt pÜ brugerens anfordring.\n")


//---------------------------------------
//  STARTUP AND REPORTING
//---------------------------------------

// Internal error in TTDPatch (%d is error number)
SETTEXT(LANG_INTERNALERROR, "*** Intern TTDPatch fejl #%d ***\n")

// Error fixing the Windows version HDPath registry entry
SETTEXT(LANG_REGISTRYERROR, "TTD er ikke installeret ordenligt (registreringsfejl %d)\n")

// Trying no-registry file
SETTEXT(LANG_TRYINGNOREGIST, "Prõver ikke registreret information fra %s\n")

// no-registry file failed
SETTEXT(LANG_NOREGISTFAILED, "Ikke registreret information er ikke tilgëngelig.\n")

// DOS reports not enough memory available to start TTD
SETTEXT(LANG_NOTENOUGHMEMTTD, "Der er ikke nok hukommelse ledig to start TTD, skal bruge %d KB mere.\n")

// Other out-of-memory messages
// %s is a function or variable name to identify where the memory allocation failed
SETTEXT(LANG_NOTENOUGHMEM, "%s: Der er ikke hukkomelsesplads nok, der er brug for %d KB mere.\n")

// Swapping TTDPatch out
SETTEXT(LANG_SWAPPING, "Swapper ud.\n")

// Just before running ttdload, show this.
// 1st %s is ttdload.ovl, then %s is a space if there are options,
// and the 3rd %s contains the options
SETTEXT(LANG_RUNTTDLOAD, "Starter %s%s%s\n")

// Error executing ttdload.  1st %s is ttdload.ovl, 2nd %s is the error message from the OS
SETTEXT(LANG_RUNERROR, "Kunne ikke udfõre %s: %s\n")

// Failed to create the new process for ttdloadw.ovl
SETTEXT(LANG_CRPROCESSFAIL, "Procesoprettelsen er fejlet")

// Interprocess communication error: TTDPatchW seems to be already running
SETTEXT(LANG_IPCEXISTS, "En anden version af TTDPatch kõre allerede!\n")

// Failed to convert language strings to Unicode
SETTEXT(LANG_STRINGCONVFAIL, "Der opstod en fejl under forarbejdningen af TTDPatchens data!\n")

// Show the result after after running, %s is one of the following strings
SETTEXT(LANG_RUNRESULT, "Resultat: [%s]\n")
SETTEXT(LANG_RUNRESULTOK, "OK")
SETTEXT(LANG_RUNRESULTERROR, "Fejl!")



//---------------------------------------
//  MESSAGES DISPLAYED BY TTDLOAD
//---------------------------------------

// Messages in this category will have "TTDPatch: " prefixed and "\r\n" suffixed
// when displayed by the DOS version.

// Out of memory (in protected mode)
SETTEXT(LANG_PMOUTOFMEMORY, "Ikke nok fri hukommelse!")

// Interprocess communication failed (WinTTDX only)
SETTEXT(LANG_PMIPCERROR, "Interproces kommunication fejl")
