//
// Localization strings for TTDPatch.
//

//-------------------------------------------
//  INFO ABOUT THIS LANGUAGE
//-------------------------------------------
SETNAME("English")
SETCODE("en")
COUNTRYARRAY(countries) = { -1, 0, 0x09, -1, 0 };
SETARRAY(countries);
	// english is default language (-1), and 0x09 is English in Windows

DOSCODEPAGE(437)	// The default DOS code page for this language
WINCODEPAGE(1252)	// The default Windows code page for this language
EDITORCODEPAGE(437)	// The code page of all strings in this file.

DOSENCODING(IBM437)	// Encoding type for XML output from DOS and Windows;
WINENCODING(ISO-8859-1)	// DOS MUST be from IANA-CHARSETS and same as DOSCODEPAGE
			// Windows can be any ISO-8859-x encoding, doesn't have
			// to be related to WINCODEPAGE

//-------------------------------------------
//  PROGRAM BLURBS
//-------------------------------------------

// First line of output is something like "TTDPatch V1.5.1 starting.\n"
// The program name and version are autogenerated, only put the " starting\n"
// here
SETTEXT(LANG_STARTING, " starting.\n")


//-------------------------------------------
//  VERSION CHECKING
//-------------------------------------------

// In the version identifier, this is for the file size
SETTEXT(LANG_SIZE, "size")

// Shown if the version is recognized
SETTEXT(LANG_KNOWNVERSION, "This version of the program has known addresses.\n")

// Warning if the version isn't recognized.  Be sure *not* to use tabs
// in the text.  All but the last lines should end in ...\n"
SETTEXT(LANG_WRONGVERSION, "\n"
	"WARNING! Your program version is not known to this program. We can now try\n"
	"         to start it anyway and determine the necessary information, but if\n"
	"         that fails, TTD may receive a Protection Fault and terminate.\n"
	"\n"
	"         Depending on how well your operating system handles a GPF, it may\n"
	"         cause your computer to lock up, and you may lose data. Please read\n"
	"         the \"Version Trouble\" section in the TTDPatch manual for more\n"
	"         information.\n"
	"\n"
	"Answer 'y' only if you really know what you are doing. YOU HAVE BEEN WARNED!\n"
	"Do you want to start TTD anyway? ")

// Keys which continue loading after the above warning. *MUST* be lower case.
// can be several different keys, e.g. one for your language "yjo"
SETTEXT(LANG_YESKEYS, "y")

// Answering anything but the above keys gives this message.
SETTEXT(LANG_ABORTLOAD, "Program load aborted.\n")

// otherwise continue loading
SETTEXT(LANG_CONTINUELOAD, "I'll try to do my best...\n")

// Warning if '-y' was used and the version is unknown
SETTEXT(LANG_WARNVERSION, "WARNING: Version is unknown!\n")


// -------------------------------------------
//    CREATING AND PATCHING TTDLOAD
// -------------------------------------------

// TTDLOAD.OVL doesn't exist
SETTEXT(LANG_OVLNOTFOUND, " not found, looking for original files:\n")

// neither do the original files (two %s are two filenames)
SETTEXT(LANG_NOFILESFOUND, "Could find neither %s nor %s.\n")

// default Windows language executable (american/english/french/german/spanish).exe
SETTEXT(LANG_WINDEFLANGEXE, "AMERICAN.EXE");

// Shown when copying tycoon.exe or ttdx.exe (first %s) to ttdload.ovl (2nd %s)
SETTEXT(LANG_SHOWCOPYING, "Copying %s to %s")

// Error if running the copy command fails.  %s is the command.
SETTEXT(LANG_COPYERROR_RUN, "Couldn't run %s\n")

// Error if command returned successfully, but nothing was copied.
// %s=TTDLOAD.OVL
SETTEXT(LANG_COPYERROR_NOEXIST, "Copy error - file %s doesn't exist.\n")

// Invalid .EXE format
SETTEXT(LANG_INVALIDEXE, "Unrecognized .EXE format.\n")

// Version could not be determined
SETTEXT(LANG_VERSIONUNCONFIRMED, "Could not determine program version.\n")

// Shows program name (1st %s) and version (2nd %s)
SETTEXT(LANG_PROGANDVER, "The program name is:\n  %s\nThe exact version is %s\n")

// More than three numbers in the version string (not #.#.#)
SETTEXT(LANG_TOOMANYNUMBERS, "Version has too many numbers!\n")

// .EXE is not TTD
SETTEXT(LANG_WRONGPROGRAM, "This is not Transport Tycoon Deluxe.\n")

// Displays the parsed version number
SETTEXT(LANG_PARSEDVERSION, "Parsed version is %s\n")

// The exe has been determined to be the DOS extended executable
SETTEXT(LANG_ISDOSEXTEXE, "This is the DOS extended executable.\n")

// The exe has been determined to be the Windows executable
SETTEXT(LANG_ISWINDOWSEXE, "This is the Windows executable.\n")

// The exe is of an unknown type
SETTEXT(LANG_ISUNKNOWNEXE, "This is not a known executable format.\n")

// The exe is the wrong one for this TTDPatch, i.e. DOS/Windows mixed up. %s=DOS or Windows
SETTEXT(LANG_NOTSUPPORTED, "Sorry, this version of TTDPatch works only with the %s version.\n")

// If the original .exe segment length (%lx) is too large or too small
SETTEXT(LANG_INVALIDSEGMENTLEN, "Invalid original segment length of %lx")

// When increasing the segment length
SETTEXT(LANG_INCREASECODELENGTH, "Setting program size to %s MB.\n")

// Can't write to TTDLOAD.OVL (%s) [or TTDLOADW.OVL for the Windows version]
SETTEXT(LANG_WRITEERROR, "Can't write to %s, is it read-only?\n")

// Installing the code loeader
SETTEXT(LANG_INSTALLLOADER, "Installing code loader.\n")

// TTDLOAD.OVL (%s) is invalid, needs to be deleted.
SETTEXT(LANG_TTDLOADINVALID, "Couldn't install code loader")
SETTEXT(LANG_DELETEOVL, " - try deleting %s.\n")

// TTDLOAD.OVL was verified to be correct
SETTEXT(LANG_TTDLOADOK, "%s is OK.\n")

// Waiting for key before terminating TTDPatch after an error occured
SETTEXT(LANG_PRESSANYKEY, "Press any key to abort.")

// Displayed on various warning conditions: Esc to exit, any other key to continue
SETTEXT(LANG_PRESSESCTOEXIT, "Press Escape to abort, or any other key to continue.")

// Loading custom in-game texts
SETTEXT(LANG_LOADCUSTOMTEXTS, "Loading custom in-game texts.\n")

// ttdpttxt.dat is not in a valid format
SETTEXT(LANG_CUSTOMTXTINVALID, "Reading %s: Invalid file format.\n")


//-----------------------------------------------
//   COMMAND LINE HELP (-h)
//-----------------------------------------------

// Introduction, prefixed with "TTDPATCH V<version> - "
SETTEXT(LANG_COMMANDLINEHELP, "Patches TTD and starts the patched program %s\n"
	  "\n"
	  "Usage: TTDPATCH [-C cfg-file] [switches] [CD Path] [-W cfg-file]\n"
	  "\n")

// Lines of help for all on/off switches, each at most 38 chars long.
// If you need more chars just insert another line.
TEXTARRAY(halflines,) =
	{ "-a:  All switches but -x",
	  "-d:  Always show full date",
	  "-f:  Make trains refittable",
	  "-g:  Some general fixes",
	  "-k:  Keep small airports",
	  "-l:  Up to 7 station platforms",
	  "-n:  New non-stop handling",
	  "-q:  Improved (un)load time algorithm",
	  "-s:  Enable the sign cheats",
	  "-u:  Enhance multiplayer games", 
	  "-v:  Verbosely show the switches",
	  "-w:  Automatic pre-signal setups",
	  "-y:  Skip unknown version query",
	  "-z:  Mammoth trains (126 cars)",

	  "-B:  Allow longer bridges",
	  "-D:  Dynamite can destroy more items",
	  "-E:  Move red error popups",
	  "-F:  Full load means any cargo type",
	  "-H:  Custom bridge heads",
	  "-I:  Turn off inflation",
	  "-J:  Allow more airports per city",
	  "-L:  Borrow/repay max. with 'Ctrl'",
	  "-N:  News reports on more events",
	  "-O:  Office Tower accept food",
	  "-P:  Persistent engines if used",
	  "-R:  Road vehicles queue up",
	  "-S:  New ship models",
	  "-T:  New train models",

	  "-2:  Windows 2000/XP compatibility",

	  "-Xb: Bribe option in L.A. menu",
	  "-Xd: Add depots to vehicle orders",
	  "-Xe: Eternal games after 2070",
	  "-Xf: Feeder service w/forced unload",
	  "-Xg: Gradual loading of vehicles",
	  "-Xh: New town buildings",
	  "-Xi: No industry closures with stable",
	  "     economy",
	  "-Xl: Build canals and locks",
	  "-Xm: Load option in disk menu",
	  "-Xo: Make sign cheats cost money",
	  "-Xp: New performance calculation",
	  "-Xr: Always rebuild TTDLOAD.OVL",
	  "-Xs: Show speed in status bars",
	  "-Xw: Extended pre-signal setups",
	  "-Xx: Save and load additional data",

	  "-XA: Forced auto-renewal with -Xa",
	  "-XB: Enable construction while paused",
	  "-XE: Electrified railways",
	  "-XF: Enable experimental features",
	  "-XH: Save+display news history",
	  "-XL: Show profit in vehicle list",
	  "-XO: Enabled shared/copied orders",
	  "-XP: New aircraft models",
	  "-XR: New road vehicle models",
	  "-XS: Manage AI subsidiaries",
	  "-XZ: Low memory version (3.5MB)",
 
	  "-Ya: Ratings more tolerant to veh.ages",
	  "-Yb: Building more things on slopes",
	  "-Yc: Track types have different cost",
	  "-Yd: New bridges",
	  "-Yh: Allow higher bridges",
	  "-Ym: Allow manual track conversion",
	  "-Yn: Enable new station graphics",
	  "-Ys: Rail signals on road traffic side",
	  "-Yt: Show more stats in town window",
	  "-Yw: Faster train selling",

	  "-YC: Build directly on coasts",
	  "-YD: Enhanced difficulty settings",
	  "-YF: FIFO loading",
	  "-YH: More/new hotkeys",
	  "-YL: Speed limits for train wagons",
	  "-YN: Enable new town name schemes",
	  "-YS: Semaphore signals before 1975",

	  "-Zc: Enable new cargo types",
	  "-Zd: New station cargo distribution",
	  "-Ze: Allow rails on rail tunnel",
	  "-Zf: Allow main view to follow vehicle",
	  "-Zi: Enable new industries",
	  "-Zj: Enable shorter road vehicles",
	  "-Zo: Enable building one-way roads",
	  "-Zu: Enable articulated road vehicles",

	  "-ZA: Enable new airports",
	  "-ZC: Enable AI transport type chances",
	  "-ZD: Enables the cloning of trains",
	  "-ZH: Hides trees in transparent mode",
	  "-ZI: Enable irregular stations",
	  "-ZM: Collect more company statistics",
	  "-ZN: Enables newRoutes",
	  "-ZO: Allow landscaping under objects",
	  "-ZQ: Enable PBS through-signals",
	  "-ZR: Prevent towns from building roads",
	  "-ZS: Enable new sound effects",
	  "-ZT: Allow buildings tramways",
	  "-ZU: Enable programmable signals",
	  "-ZV: Enables variable running costs",
	  "-ZW: Enable new signal graphics",
	  "-ZX: Enable adjacent stations",
	  "-ZZ: Enable route tracing restrictions",

	  NULL
	};
SETARRAY(halflines);

// Text describing the switches with values.  The lines have to be shorter
// than 79 chars, excluding the "\n".  Start new lines if necessary.
SETTEXT(LANG_FULLSWITCHES, "\n"
	  "-e #:    Increase possible station spread\n"
	  "-i #:    Default service interval is the given number of days\n"
	  "-x #:    Extend the vehicle array to 850*#. Read the documentation!\n"
	  "-mc #:   New mountain or curve handling, respectively\n"
	  "-trpb #: Increase number of trains, road vehicles, planes or ships, resp.\n"
	  "-A #:    Enable autoreplace for vehicles with given minimum reliability\n"
	  "-G #:    Selectable station goods. # is days before cargo disappears again.\n"
	  "-M #:    Allow multi-headed trains, set speed increase in percent.\n"
	  "-U #:    Enable the new locomotion-like gui. 1 for new gui without ctrl.\n"
	  "-Xa #:   Automatically renew vehicles # months after end of their life span\n"
	  "-Xc #:   Control the occurence of plane crashes\n"
	  "-Yr #:   Modify train/road veh. crashes to the given type (1/2)\n"
	  "-Xt #:   Set the maximum size a town expands to\n"
	  "-Xv #:   Sort vehicle lists and set the time between two updates\n"
	  "-Xz #:   Snap windows together\n"
	  "-XC #:   Allow more currencies,  and set currency display options\n"
	  "-XD #:   Choose which disasters may occur\n"
	  "-XI #:   Enable path based signalling\n"
	  "-XN #:   TTD newspaper in color after the given year\n"
	  "-XM #:   Combine monorail and maglev track systems\n"
	  "-XT #:   Set one out of how many towns grows faster and larger\n"
	  "-XX #:   New monorail and maglev bridge speeds, in percent of max. veh. speed\n"
	  "-XY #:   Set default start year for new random games\n"
	  "-XW #:   Stretch TTD's window to this size in pixels (Windows version only)\n"
	  "-X1 #, -X2 #: Max. time train waits at red one-way resp. two-way signal in days\n"
	  "-Yf #:   Make freight trains more massive by the given factor\n"
	  "-Yg #:   Changeable gamespeed. # is speed at game start\n"
	  "-Yl #:   Enable mouse wheel support and set options (Windows version only)\n"
	  "-Yo #, -Zm #:   Control some features of other switches (see the documentation)\n"
	  "-Yp #:   Allow planting many trees, choose plant mode\n"
	  "-YA #:   Abandoned roads lose their owners, choose mode with parameter\n"
	  "-YB #:   More build options, control options with parameter\n"
	  "-YE #:   Set time in seconds that red error popups are displayed\n"
	  "-YM #:   Show more (or fewer) steam plumes, value sets amount\n"
	  "-YG #:   Enhance the user interface, choose option with parameter\n"
	  "-YO #:   Enable the snow line in the temperate climate and set its height\n"
	  "-YP #:   Planes fly at #/4 times their indicated speed.\n"
	  "-YR #:   Override map refresh frequency to # ticks\n"
	  "-YT #:   Set town growth rate algorithm\n"
	  "-YW #:   Set maximum allowed window count\n"
	  "-Za #:   Enable more animation (sets number of animated tiles)\n"
	  "-Zb #:   Set probability for town road branches\n"
	  "-Zg #:   Force initial game options\n"
	  "-Zh #, -Zw #: Set screen resolution height and width\n"
	  "-Zn #:   Set network timeout in seconds\n"
	  "-Zx #, -Zy #, -Zz #: Set chance for AI to build rail/road/air route\n"
	  "-Zp #, -Zr #, -Zs #, -Zt #: Warn about lost aircraft, road vehicles, ships and\n"
	  "         trains after this many days\n"
	  "-ZF #:   Enable certain game features in the Toyland climate\n"
	  "-ZY #:   Set maximum rail station size (still limited by station spread)\n"
	  "\n"
	  "-C cfg-file:  Read this configuration file instead of ttdpatch.cfg\n"
	  "-W cfg-file:  Creates a configuration file with the current configuration\n"
	  "-Xn cfg-file: Uses this file as configuration file for new graphics sets\n"
	  "\n"
	  "Capitalization is important!\n"
	  "\n"
	  "Example:  ttdpatch -fnqz -m 00 -c 13 -trpb 240 -FG -A 2 -v\n"
	  "\n"
	  "(Hint:  If everything scrolled by too fast, enter \"ttdpatch -h|more\")\n"
	  "\n")

// Referral to the docs, prefixed by "Copyright (C) 1999 by Josef Drexler.  "
SETTEXT(LANG_HELPTRAILER, "See TTDPATCH.TXT for more details.\n")


//-----------------------------------------------
//  COMMAND LINE AND CONFIG FILE PARSING
//-----------------------------------------------

// if an on/off switch has a value other than the above (%s = wrong value)
SETTEXT(LANG_UNKNOWNSTATE, "Warning: Unknown on/off state %s, set to off.\n")

// switch is unknown.  %c is '-' or '/' etc, %s is the switch char
SETTEXT(LANG_UNKNOWNSWITCH, "Unknown switch '%c%s'.  Use -h for help.\n")

// switch bit name is unknown.  First %s is bit name, 2nd is switch name
SETTEXT(LANG_UNKNOWNSWITCHBIT, "Unknown bit '%s' for switch '%s'.\n")

// cfg command %s is unknown
SETTEXT(LANG_UNKNOWNCFGLINE, "Warning: Invalid cfg line '%s'.\n")

// Names of the switches for the '-v' options
// First string is shown always, second only if set and with the given
// value of the switch in %d.
// These lines (both parts) are limited to 36 chars, also consider how large
// the expansion of the %d can be for that switch.
SWITCHTEXT(uselargerarray, "Extend total vehicles", " to %d*850")
SWITCHTEXT(usenewcurves, "New curve handler", " for %04x")
SWITCHTEXT(usenewmountain, "New mountain handler", " for %04x")
SWITCHTEXT(usenewnonstop, "New non-stop handling", "")
SWITCHTEXT(increasetraincount, "New train count", ": %d")
SWITCHTEXT(increaservcount, "New road vehicle count", ": %d")
SWITCHTEXT(setnewservinterval, "New def.service interval", ": %d days")
SWITCHTEXT(usesigncheat, "Use Sign cheat", "")
SWITCHTEXT(allowtrainrefit, "Allow train refit", "")
SWITCHTEXT(increaseplanecount, "New aircraft count", ": %d")
SWITCHTEXT(increaseshipcount, "New ship count", ": %d")
SWITCHTEXT(keepsmallairports, "Keep small airports", "")
SWITCHTEXT(largerstations, "Incr. station spread", " to %d sq.")
SWITCHTEXT(morestationtracks, "Extensible stations", "")
SWITCHTEXT(longerbridges, "Longer bridges", "")
SWITCHTEXT(improvedloadtimes, "Improved load time calc.", "")
SWITCHTEXT(mammothtrains, "Mammoth trains (length 127)", "")
SWITCHTEXT(presignals, "Set pre-signals automatically", "")
SWITCHTEXT(officefood, "Office Towers accept food", "")
SWITCHTEXT(noinflation, "Turn off inflation", "")
SWITCHTEXT(maxloanwithctrl, "Max borrow/repay with 'Ctrl'", "")
SWITCHTEXT(persistentengines, "Persistent engines if used", "")
SWITCHTEXT(fullloadany, "Full load means any cargo", "")
SWITCHTEXT(selectstationgoods, "Selectable station goods", " for %d days")
SWITCHTEXT(morethingsremovable, "More things removable", "")
SWITCHTEXT(multihead, "Multi-headed trains", ", speed-up: %d%%")
SWITCHTEXT(newlineup, "Road vehicle queueing", "")
SWITCHTEXT(lowmemory, "Low memory version (3.5MB)", "")
SWITCHTEXT(generalfixes, "General fixes (see docs)", "")
SWITCHTEXT(moreairports, "More airports allowed per town", "")
SWITCHTEXT(bribe, "Show bribe option", "")
SWITCHTEXT(noplanecrashes, "Plane crash control", ": %d")
SWITCHTEXT(showspeed, "Show speed in status bars", "")
SWITCHTEXT(autorenew, "Auto-renew engines", " at %d months")
SWITCHTEXT(cheatscost, "Sign cheats cost money", "")
SWITCHTEXT(extpresignals, "Set pre-signals with 'Ctrl'", "")
SWITCHTEXT(diskmenu, "Show load option in disk menu", "")
SWITCHTEXT(win2k, "Apply Windows 2000/XP patches", "")
SWITCHTEXT(feederservice, "Feeder service with forced unload", "")
SWITCHTEXT(gotodepot, "Add depots to vehicle orders", "")
SWITCHTEXT(newships, "New ship models", "")
SWITCHTEXT(subsidiaries, "Manage AI subsidiaries", "")
SWITCHTEXT(gradualloading, "Gradual loading of vehicles", "")
SWITCHTEXT(moveerrorpopup, "Move red error popups", "")
SWITCHTEXT(setsignal1waittime, "New train wait time on signals", ":")
SWITCHTEXT(setsignal2waittime, "", "")				// dummy entry
SWITCHTEXT(maskdisasters, "Mask of disasters", ": %d")
SWITCHTEXT(forceautorenew, "Force auto-renewal of engines", "")
SWITCHTEXT(morenews, "News reports on more events", "")
SWITCHTEXT(unifiedmaglev, "Unified maglev", ", mode %d")
SWITCHTEXT(newbridgespeeds, "Max. speed on maglev bridges", ": %d%%")
SWITCHTEXT(eternalgame, "Play forever after 2070", "")
SWITCHTEXT(showfulldate, "Always show full date", "")
SWITCHTEXT(newtrains, "New train models", "")
SWITCHTEXT(newrvs, "New road vehicle models", "")
SWITCHTEXT(newplanes, "New aircraft models", "")
SWITCHTEXT(signalsontrafficside, "Signals on 'traffic' side of track", "")
SWITCHTEXT(electrifiedrail, "Electrified railroads", "")
SWITCHTEXT(newstartyear, "Default start year", ": %d")
SWITCHTEXT(newerrorpopuptime, "New error popup timeout", ": %d sec.")
SWITCHTEXT(newtowngrowthfactor, "Change town growth factor", " to %d")
SWITCHTEXT(largertowns, "Larger towns", ", each 1 out of %d")
SWITCHTEXT(miscmods, "Miscellaneous mods", ": %ld")
SWITCHTEXT(miscmods2, "More miscellaneous mods", ": %ld")
SWITCHTEXT(loadallgraphics, "Always load all new graphics", "")
SWITCHTEXT(saveoptdata, "Save and load optional data", "")
SWITCHTEXT(morebuildoptions, "More build options", ": %d")
SWITCHTEXT(semaphoresignals, "Semaphores before 1975", "")
SWITCHTEXT(morehotkeys, "More/new hotkeys", "")
SWITCHTEXT(plantmanytrees, "Plant many trees", ", mode %d")
SWITCHTEXT(morecurrencies, "Enable more currencies", ", flags: %d")
SWITCHTEXT(manualconvert, "Allow manual track conversion", "")
SWITCHTEXT(newtowngrowthrate, "New town growth rate algorithm", ": %d")
SWITCHTEXT(displmoretownstats, "Display more town stats", "")
SWITCHTEXT(enhancegui, "Enhanced game interface", "")
SWITCHTEXT(newagerating, "Ratings more tolerant to veh. ages", "")
SWITCHTEXT(buildonslopes, "Build more things on sloped land", "")
SWITCHTEXT(buildoncoasts, "Build directly on coasts", "")
SWITCHTEXT(experimentalfeatures, "Enable experimental features", ": %u")
SWITCHTEXT(tracktypecostdiff, "Track types have different cost", "")
SWITCHTEXT(planespeed, "Use real plane speed", ": %d/4")
SWITCHTEXT(fastwagonsell, "Faster train selling", "")
SWITCHTEXT(newrvcrash, "Change train/rv crashes", " (mode %d)")
SWITCHTEXT(stableindustry, "Prevent industry closedowns", "")
SWITCHTEXT(newperformance, "New performance rating", "")
SWITCHTEXT(sortvehlist, "Sort vehicle lists", ", delay: %d")
SWITCHTEXT(showprofitinlist, "Show profit in vehicle list", "")
SWITCHTEXT(newspapercolour, "Newpapers are in colour", " after %d")
SWITCHTEXT(sharedorders, "Enable shared/copied orders", "")
SWITCHTEXT(moresteam, "Show more steam plumes", ": %x")
SWITCHTEXT(abandonedroads, "Abandoned roads lose their owners", ", mode %d")
SWITCHTEXT(newstations, "Enable new station graphics", "")
SWITCHTEXT(buildwhilepaused, "Enable construction while paused", "")
SWITCHTEXT(losttrains, "Warning about lost trains", " after %d days")
SWITCHTEXT(lostrvs, "Warning about lost road vehicles", " after %d days")
SWITCHTEXT(lostships, "Warning about lost ships", " after %d days")
SWITCHTEXT(lostaircraft, "Warning about lost aircraft", " after %d days")
SWITCHTEXT(maprefresh, "New map refresh frequency", ": %d ticks")
SWITCHTEXT(disconnectontimeout, "Disconnect a network game if there is no response", " for %d sec.")
SWITCHTEXT(moretoylandfeatures, "Enable some random game features in toyland", ": %d")
SWITCHTEXT(stretchwindow, "Stretch TTD's window", " to %d pixels")
SWITCHTEXT(canals, "Build canals and locks", "")
SWITCHTEXT(higherbridges, "Allow higher bridges", "")
SWITCHTEXT(gamespeed, "Changeable gamespeed", ", initially %d")
SWITCHTEXT(freighttrains, "Make freight trains more massive", " (x%d)")
SWITCHTEXT(mousewheel, "Enable mouse wheel",", setting: %d")
SWITCHTEXT(morewindows, "Increase maximum window count", " to %d")
SWITCHTEXT(enhanceddiffsettings, "Enhanced difficulty settings", "")
SWITCHTEXT(newbridges, "New bridges", "")
SWITCHTEXT(newhouses, "New town buildings", "")
SWITCHTEXT(newtownnames,"New town name styles","")
SWITCHTEXT(moreanimation,"Allow more animated tiles",", up to %d")
SWITCHTEXT(newshistory, "News history", "")
SWITCHTEXT(wagonspeedlimits, "Speed limits for train wagons", "")
SWITCHTEXT(pathbasedsignalling, "Enable path based signalling", "")
SWITCHTEXT(aichoosechances, "Specify which chances to use when the ai decides what to build", "")
SWITCHTEXT(custombridgeheads, "Custom bridge heads", "")
SWITCHTEXT(townbuildnoroads, "Towns build no roads", "")
SWITCHTEXT(newcargodistribution, "Enhanced cargo distribution", "")
SWITCHTEXT(windowsnap, "Windows snap together", " when closer than %d pixels")
SWITCHTEXT(resolutionwidth, "Resolution width", " %d pixels")
SWITCHTEXT(resolutionheight, "Resolution height", " %d pixels")
SWITCHTEXT(newindustries, "New industries", "")
SWITCHTEXT(locomotiongui, "Enable locomotion style gui", "")
SWITCHTEXT(fifoloading, "Enable FIFO loading", "");
SWITCHTEXT(tempsnowline, "Enable snow line on temperate", "")
SWITCHTEXT(townroadbranchprob, "Change town road branch prob.", " to %d")
SWITCHTEXT(newcargos, "Allow new cargo types", "")
SWITCHTEXT(enhancemultiplayer, "Enhance multiplayer games (allow more players)", "")
SWITCHTEXT(newsounds, "Allow adding new sounds to the game", "")
SWITCHTEXT(morestats, "Enable collection of more statistics", "")
SWITCHTEXT(onewayroads, "Allow changing roads to one-way with 'Ctrl'", "")
SWITCHTEXT(irrstations, "Enable irregular station construction", "")
SWITCHTEXT(autoreplace, "Upgrade vehicles when they get old", "; %d%% min. reliability for new model")
SWITCHTEXT(autoslope, "Allows terraforming without removing structures", "")
SWITCHTEXT(followvehicle, "Follow vehicle motion in main map", "")
SWITCHTEXT(trams, "Enable trams on Roads", "")
SWITCHTEXT(enhancetunnels, "Allows building track on top of tunnel entrances", "")
SWITCHTEXT(forcegameoptions, "Allows you to force game options","")
SWITCHTEXT(shortrvs, "Enabled Shortened (or lengthened) RVs", "")
SWITCHTEXT(articulatedrvs, "Enabled Articulated RVs", "")
SWITCHTEXT(newairports, "Allows using new airport types","")
SWITCHTEXT(newroutes, "Allows the changing of Rails and Roads through grf files", "")
SWITCHTEXT(clonetrain, "Allows the cloning of a train through the depot window.", "")
SWITCHTEXT(tracerestrict, "Enables train routetracing to be restricted", "")
SWITCHTEXT(stationsize, "Set maximum rail station size (still limited by station spread)", "")
SWITCHTEXT(adjacentstation, "Adjacent station building and remote merging with other stations", "")
SWITCHTEXT(newsignals, "New signal graphics", "")
SWITCHTEXT(newobjects, "Enable new objects", "")
SWITCHTEXT(vruncosts, "Enables grfs to have variable running costs", "")
SWITCHTEXT(hidetranstrees, "Make trees completely invisible in transparent buildings mode", "")
SWITCHTEXT(psignals, "Allows signals states to be controlled by user criteria","")
SWITCHTEXT(tsignals, "Allows PBS reservations the opposite way through selected one-way signals","")

//---------------------------------------
//  BIT SWITCH DESCRIPTIONS
//---------------------------------------

// Description for noplanecrashes bits
BITSWITCH(noplanecrashes)
BIT(normdis,      "normal plane crashes off if disasters off")
BIT(jetsdis,      "crashes of jets on small airports off if disasters off")
BIT(normbrdown,   "normal plane crashes only for broken down planes, rate * 4")
BIT(jetssamerate, "same rate for jets on small airports and normal crashes")
BIT(normoff,      "normal plane crashes off")
BIT(jetsoff,      "jets on small airport crashes off")

// Description for miscmods bits
BITSWITCH(miscmods)
BIT(nobuildonbanks,        "towns don't build on waterbanks")
BIT(servintonlyhuman,      "servint setting doesn't apply to AI players")
BIT(noroadtakeover,        "towns don't claim all roads in the scenario editor")
BIT(gradualloadbywagon,    "gradual loading loads wagon by wagon first")
BIT(dontfixlitres,         "don't change litres so that 1000 l is a ton instead of 100 l")
BIT(dontfixtropicbanks,    "don't fix bank types in the sub-tropical climate")
BIT(dontfixhousesprites,   "don't fix offices being displayed as churches")
BIT(oldtownterrmodlimit,   "don't change the upper cost of terrain modification for towns")
BIT(nozeppelinonlargeap,   "prevent Zeppelins from crashing at large airports")
BIT(nodefaultoldtracktype, "don't use previous track type as new default")
BIT(usevehnnumbernotname,  "don't change news messages to use vehicle names")
BIT(norescalecompanygraph, "don't rescale company graph when companies are deselected")
BIT(noyearlyfinances,      "don't display yearly finances on Jan 1st")
BIT(notimegiveaway,        "don't try to give time slices away to conserve power")
BIT(nodesynchwarning,      "don't warn about multiplayer games being desynched")
BIT(noworldedgeflooding,   "don't let the edge of the map flood")
BIT(doshowintro,           "show the game intro (don't skip it)")
BIT(nonewspritesorter,     "don't use new sprite sorting algorithm")
BIT(nodiagonalflooding,    "disable diagonal flooding and corner coasts")
BIT(noenhancedcomp,        "don't enhance savegame compression algorithm")
BIT(breakdownatsignal,     "don't fix trains breaking down while waiting on red signals")
BIT(smallspritelimit,      "don't increase the sprite limit")
BIT(displaytownsize,       "display town size in the name")
BIT(noextendstationrange,  "don't increase the maximum allowed distance between station sign and industry for cargo to be delivered")
BIT(nooldvehiclenews,      "don't generate news messages when vehicles get old")
BIT(dontfixpaymentgraph,   "don't fix the X axis of the cargo payment rate window")
BIT(alwaysshowoneway,      "Always show one-way indicators")
BIT(dontshowaltitude,      "Don't show altitude in tile info window")
BIT(nogrfidsinscreenshots, "Don't show active grfids in screenshots")
BIT(dontchangesnow,        "Don't change how height is calculated for snowiness")
BIT(notransparentdepots,   "Don't make road and tram depots transparent in transparent-buildings mode")
BIT(nodepotnumbers,        "Don't display depot numbers")

// Description for miscmods2 bits
BITSWITCH(miscmods2)
BIT(noenhancetrees,        "Force grass under the tree when it's planted on bare land or desert")
BIT(ignoretaskbar,         "Don't consider the size of the Taskbar when positioning the game window")

// Description for morebuildoptions bits
BITSWITCH(morebuildoptions)
BIT(ctunnel,         "allow crossing tunnels")
BIT(oilrefinery,     "allow oil refinery everywhere")
BIT(moreindustries,  "allow more than one industry of the same type")
BIT(removeobjects,   "allow removing statues, lighthouses and transmitters")
BIT(removeindustry,  "allow removing industries")
BIT(closeindustries, "allow same industries to be very close to each other")
BIT(enhancedbuoys,   "allow buoys that work like normal stations")
BIT(bulldozesignals, "automatically bulldoze signals on track")

// Description for experimentalfeatures bits
BITSWITCH(experimentalfeatures)
BIT(slowcrossing, "trains slow down before crossings")
BIT(cooperative,  "cooperative play, very limited")
BIT(mandatorygrm, "make GRF Resource Management mandatory for .grf files")
BIT(incvehconsist, "build even more then 255 trains per company (very experimental)")
BIT(signalgui,     "alter signals with the signal window (very experimental)")
BIT(newterraingen, "new terrain generator for random landscapes")
BIT(engineconvert, "converts an engine to a extra head (very experimental)")
BIT(previewdd,     "Show previews in the station drop down")
BIT(extradetails,  "Show more specs in the vehicle details window")
BIT(asyncmp,       "Internet multiplayer support")

// Description for maskdisasters bits
BITSWITCH(maskdisasters)
BIT(zeppelincrash,      "Allow zeppelin crash")
BIT(smallufo,           "Allow small UFO")
BIT(refineryexplosion,  "Allow refinery explosion")
BIT(factoryexplosion,   "Allow factory explosion")
BIT(largeufo,           "Allow large UFO")
BIT(smallsubmarine,     "Allow small submarine")
BIT(largesubmarine,     "Allow large submarine")
BIT(coalminesubsidence, "Allow coal mine subsidence")

// Description for mousewheel bits
BITSWITCH(mousewheel)
BIT(cursorzoom, "Zoom at cursor location instead of screen center")
BIT(safezoom,   "Zoom only after rolling wheel two notches")
BIT(legacy,     "Enable support for older (legacy) operating systems and drivers (not normally needed)")

// Description for plantmanytrees bits
BITSWITCH(plantmanytrees)
BIT(morethanonepersquare,   "Allow planting more than one tree per square")
BIT(rectangular,            "Enable planting over a rectangular area with 'Ctrl'")
BIT(morethanonerectangular, "More than one tree on a square in the rectangular planting mode")

// Description for moretoylandfeatures bits
BITSWITCH(moretoylandfeatures)
BIT(lighthouses, "Enable lighthouses on sea shores in Toyland")
BIT(woodlands,   "Enable woodlands (clusters of trees) in Toyland")

// Description for locomotiongui bits
BITSWITCH(locomotiongui)
BIT(usenewgui,      "Enable the new gui")
BIT(defaultnewgui,  "Use the new gui by default (with this disabled the new gui can be reached with ctrl, when enabled with ctrl the old gui will be used)")
BIT(defaultstation, "Make the station build button open the locomotion gui station tab.")

// Description for pathbasedsignalling bits
BITSWITCH(pathbasedsignalling)
BIT(autoconvertpresig,    "Convert pre, exit and combo signals into PBS signals")
BIT(manualpbssig,         "Allow manually setting PBS signals")
BIT(preservemanualpresig, "Don't convert junctions with manually set signals into PBS")
BIT(showreservedpath,     "Show reserved track pieces darker")
BIT(shownonjunctionpath,  "Show reserved track pieces on non-junction tiles too")
BIT(allowunsafejunction,  "Don't hold trains at unsafe PBS signal")
BIT(allowunsafereverse,   "Don't stop trains that can't reverse safely")

// Description for newsounds bits
BITSWITCH(newsounds)
BIT(highfrequency, "(DOS only) Mix sounds at 22KHz instead of the default 11KHz. Allows correct playpack of 22KHz samples.")

// Description for morecurrencies bits
BITSWITCH(morecurrencies)
BIT(symbefore, "Currency symbol displayed always before number")
BIT(symafter,  "Currency symbol displayed always after number")
BIT(noeuro,    "Do not introduce the Euro")
BIT(comma,     "Always use comma to separate thousands")
BIT(period,    "Always use period to separate thousands")

// Description for forcegameoptions bits
BITSWITCH(forcegameoptions)
BIT(trafficleft,	"Force the road traffic side to be left")
BIT(trafficright,	"Force the road traffic side to be right")
BIT(imperial,		"Force the use of imperial (miles) distance units")
BIT(metric,		"Force the use of metric (kilometers) distance units")
BIT(townsenglish,	"Set town name style to English")
BIT(townsfrench,	"Set town name style to French")
BIT(townsgerman,	"Set town name style to German")
BIT(townsamerican,	"Set town name style to American")
BIT(townslatin,		"Set town name style to Latin American")
BIT(townssilly,		"Set town name style to Silly")
BIT(autosavedisabled,	"Set autosave to off")
BIT(autosave3months,	"Set autosave to 3 months")
BIT(autosave6months,	"Set autosave to 6 months")
BIT(autosave12months,	"Set autosave to 12 months")

// A cfg file (%s) could not be found and is ignored.
SETTEXT(LANG_CFGFILENOTFOUND, "Couldn't find cfg file %s.  Ignored.\n")

// Couldn't write the config file
SETTEXT(LANG_CFGFILENOTWRITABLE, "Couldn't open %s for writing.\n")

// A non-comment line is longer than 32 chars, rest ignored.
SETTEXT(LANG_CFGLINETOOLONG, "Warning!  Configuration line is longer than %d chars, truncated.\n")

// Shown if an obsolete switch is used. First option is %s which is the
// config name, second one is %s which is the command line char
SETTEXT(LANG_SWITCHOBSOLETE, "The switch `%s' (%s) is obsolete. Please do not use it, it will\n"
		"be removed in a future version.\n")

//---------------------------------------------------
//   CONFIG FILE COMMENTS (for '-W')
//---------------------------------------------------

// This is the intro at the start of the config file.  No constraints on line lengths.
SETTEXT(CFG_INTRO,
	CFG_COMMENT "\n"
	CFG_COMMENT "TTDPatch Configuration File, automatically created by TTDPatch -W filename.\n"
	CFG_COMMENT "(TTDPatch %s)\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Format for the switches is:\n"
	CFG_COMMENT "   switchname = switchvalue\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "The \"=\" can be omitted, as can the spaces.  Case is ignored.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "For yes/no [y/n] switches, the value can be one of:\n"
	CFG_COMMENT "   yes, y, on, 1, no, n, off, 0\n"
	CFG_COMMENT "If the value is omitted, a yes/no switch defaults to yes.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "For the switches with a value option [v], the range is given in the\n"
	CFG_COMMENT "description, as is the default if the value is omitted.  The switch can\n"
	CFG_COMMENT "be turned off by giving it one of the 'off' values.\n"
	CFG_COMMENT "\n"
	CFG_COMMENT "Comments are all lines starting with any non-alphabetical character.\n"
	CFG_COMMENT "\n")

// Line before previously unset switches
SETTEXT(CFG_NEWSWITCHINTRO, "**** New switches ****")

// Line before previously unset bits in bit switches
SETTEXT(CFG_NEWBITINTRO, "**** New bits ****")

// For switches which have no command line equivalent
SETTEXT(CFG_NOCMDLINE, "no command line switch")

// Definitions of the cfg file comments.
// All can have a place holder %s to stand for the actual setting name,
// and all but CFG_CDPATH can have a %s *after* the %s for the command
// line switch.
// They will have the "comment" char and a space prefixed.
//
SETTEXT(CFG_SHIPS, "`%s' (%s) sets the maximum number of ships.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_CURVES, "`%s' (%s) sets curve speeds to normal (0), faster (1), fastest (2) or realistic (3).  One digit for each of railroad, monorail, maglev and road vehicles.  Default 0120.")
SETTEXT(CFG_MOUNTAINS, "`%s' (%s) sets mountain speeds to normal (0), faster (1), fastest (2) or realistic (3).  One digit for each of railroad, monorail, maglev and road vehicles.  Default 0120.")
SETTEXT(CFG_SPREAD, "`%s' (%s) makes it possible to have stations more spread out.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TRAINREFIT, "`%s' (%s) makes it possible to refit train engines.")
SETTEXT(CFG_SERVINT, "`%s' (%s) allows to change the initial service interval for new engines.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_NOINFLATION, "`%s' (%s) turns off all inflation, both for cost and revenue.")
SETTEXT(CFG_LARGESTATIONS, "`%s' (%s) allows to add more platforms or make a station longer, up to 15x15.")
SETTEXT(CFG_NONSTOP, "`%s' (%s) makes the \"Non-stop\" switch behave differently.")
SETTEXT(CFG_PLANES, "`%s' (%s) sets the maximum number of planes.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_LOADTIME, "`%s' (%s) enables a different calculation for load/unload times.")
SETTEXT(CFG_ROADVEHS, "`%s' (%s) sets the maximum number of road vehicles.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_SIGNCHEATS, "`%s' (%s) enables the sign cheats.")
SETTEXT(CFG_TRAINS, "`%s' (%s) sets the maximum number of trains.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_VERBOSE, "`%s' (%s) shows a summary of the switches before starting TTD.")
SETTEXT(CFG_PRESIGNALS, "`%s' (%s) automatically sets up 'pre-signals' to improve station handling.")
SETTEXT(CFG_MOREVEHICLES, "`%s' (%s) increases the total number of vehicles to value*850.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_MAMMOTHTRAINS, "`%s' (%s) allows mammoth trains with up to 126 cars.")
SETTEXT(CFG_FULLLOADANY, "`%s' (%s) makes a train leave a station if any type of cargo is full.")
SETTEXT(CFG_SELECTGOODS, "With `%s' (%s) goods arrive only after the service has been inaugurated, and disappear after the given number of days if the service stops.  Specifying 2 means goods never disappear.  Range: %ld..%ld.  Default: %ld.")
SETTEXT(CFG_DEBTMAX, "`%s' (%s) enables borrowing/repaying the maximum amount by holding down the 'Ctrl' key.")
SETTEXT(CFG_OFFICEFOOD, "`%s' (%s) makes office towers accept food (tropic/arctic scenarios).")
SETTEXT(CFG_ENGINESPERSIST, "`%s' (%s) keeps engines around for as long as they are in use.")
SETTEXT(CFG_CDPATH, "`%s' (%s) sets the CD path.")
SETTEXT(CFG_KEEPSMALLAP, "`%s' (%s) keeps small airports around forever.")
SETTEXT(CFG_LONGBRIDGES, "`%s' (%s) allows bridges of up to 127 squares length.")
SETTEXT(CFG_DYNAMITE, "`%s' (%s) allows more things to be removed with dynamite.")
SETTEXT(CFG_MULTIHEAD, "`%s' (%s) allows an arbitrary number of engines on a train.  Buy extra engines with 'Ctrl'.  Parameter is max. speed-up by additional engines, in percent from %ld to %ld, default %ld%%.")
SETTEXT(CFG_RVQUEUEING, "`%s' (%s) makes road vehicles queue up in front of a station, not turn around.")
SETTEXT(CFG_LOWMEMORY, "`%s' (%s) allows TTDPatch to run with approx. 3.5MB of memory, but makes it impossible to load games saved with a larger `morevehicles' setting.")
SETTEXT(CFG_GENERALFIXES, "`%s' (%s) fixes various little things, see the docs for more info on what exactly it does.")
SETTEXT(CFG_MOREAIRPORTS, "`%s' (%s) allows building more airports than the normal two per city.")
SETTEXT(CFG_BRIBE, "`%s' (%s) adds a `bribe' option to the local authority menu.")
SETTEXT(CFG_PLANECRCTRL, "`%s' (%s) allows you to control when planes are allowed to crash.")
SETTEXT(CFG_SHOWSPEED, "`%s' (%s) shows the current speed for all vehicles in the status bar of their window.")
SETTEXT(CFG_AUTORENEW, "`%s' (%s) renews engines when serviced this number of months after they get very old.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_CHEATSCOST, "`%s' (%s) makes sign cheats cost money when used.")
SETTEXT(CFG_EXTPRESIGNALS, "`%s' (%s) allows to cycle between normal, pre-signals, exits and combined signals with 'Ctrl'.")
SETTEXT(CFG_FORCEREBUILDOVL, "`%s' (%s) makes TTDPatch rebuild TTDLOAD.OVL or TTDLOADW.OVL every time it is started.")
SETTEXT(CFG_DISKMENU, "`%s' (%s) adds a load option to the disk menu, and a load game (or save game with 'Ctrl') to the scenario editor.")
SETTEXT(CFG_WIN2K, "`%s' (%s) makes the Windows version of TTD compatible with Windows 2000/XP.")
SETTEXT(CFG_FEEDERSERVICE, "`%s' (%s) modifies forced unload and profit on a station accepting that cargo to leave the cargo at the station, not cash in.")
SETTEXT(CFG_GOTODEPOT, "`%s' (%s) allows you to add depots to vehicles' orders.")
SETTEXT(CFG_NEWSHIPS, "`%s' (%s) activates new ship models with new graphics.")
SETTEXT(CFG_SUBSIDIARIES, "`%s' (%s) allows you to manage AI companies if you own 75%%.")
SETTEXT(CFG_GRADUALLOADING, "`%s' (%s) changes the way vehicles are loaded to a more realistic gradual loading (also activates `loadtime').")
SETTEXT(CFG_MOVEERRORPOPUP, "`%s' (%s) moves all red error popups to the top-right corner of the screen.")
SETTEXT(CFG_SIGNAL1WAITTIME, "`%s' (%s) changes the number of days after which a train waiting on a 1-way signal turns around.  Range 0..254, or 255 to wait forever.")
SETTEXT(CFG_SIGNAL2WAITTIME, "`%s' (%s) changes the number of days after which a train waiting on a 2-way signal turns around.  Range 0..254, or 255 to wait forever.")
SETTEXT(CFG_DISASTERS, "`%s' (%s) allows you to choose which disasters may occur.")
SETTEXT(CFG_FORCEAUTORENEW, "`%s' (%s) forces servicing of vehicles when it is time for the auto-renewal (see `autorenew').")
SETTEXT(CFG_MORENEWS, "`%s' (%s) generates messages/news reports on more events, see the docs for more information.")
SETTEXT(CFG_UNIFIEDMAGLEV, "`%s' (%s) makes it possible to buy monorail engines in maglev depots or vice versa.  Mode: 1 - convert all maglev engines to monorail; 2 - convert all monorail engines to maglev; 3 - keep separate monorail and maglev.")
SETTEXT(CFG_BRIDGESPEEDS, "`%s' (%s) increases the speed limits on tubular monorail and maglev bridges to this percentage of the highest maximum engine speed in the class.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_ETERNALGAME, "`%s' (%s) allows you to keep playing forever, the date isn't reset after 2070.")
SETTEXT(CFG_SHOWFULLDATE, "`%s' (%s) always show the full date in the status, not only when the game is paused.")
SETTEXT(CFG_NEWTRAINS, "`%s' (%s) activates new train models with new graphics.")
SETTEXT(CFG_NEWRVS, "`%s' (%s) activates new road vehicle models with new graphics.")
SETTEXT(CFG_NEWPLANES, "`%s' (%s) activates new aircract models with new graphics.")
SETTEXT(CFG_SIGNALSONTRAFFICSIDE, "`%s' (%s) displays railroad signals on the same side of track road vehicles drive on.")
SETTEXT(CFG_ELECTRIFIEDRAIL, "`%s' (%s) removes one of the magnetic track systems (Monorail or MagLev) and replaces it with an electrified railroad system.")
SETTEXT(CFG_STARTYEAR, "`%s' (%s) sets the default start year for random games and allows greater choice of starting years in the scenario editor.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_ERRORPOPUPTIME, "`%s' (%s) changes the time after which red error popup windows automatically close.  Range 1..255 (in seconds), or 0 for a very long time.  Default 10.")
SETTEXT(CFG_TOWNGROWTHLIMIT, "`%s' (%s) changes the factor that limits the maximum possible extent of towns.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_LARGERTOWNS, "`%s' (%s) makes each one out of a given number of towns grow faster and larger (also applying `towngrowthlimit' selectively).  Range %ld..%ld.  Default %ld (one out of four towns).")
SETTEXT(CFG_MISCMODS, "`%s' (%s) makes it posible to modify the working of some other switches, see the docs on more info.")
SETTEXT(CFG_MISCMODS2, "`%s' (%s) makes it posible to modify the working of some other switches (similarly to miscmods), see the docs on more info.")
SETTEXT(CFG_LOADALLGRAPHICS, "`%s' (%s) forces TTDPatch to always load all .grf files in newgrf(w).cfg, regardless of whether they were used previously in a loaded game (etc.) or not.")
SETTEXT(CFG_SAVEOPTDATA, "`%s' (%s) makes TTDPatch save and load additional (optional) data at the end of savegames.")
SETTEXT(CFG_MOREBUILDOPTIONS, "`%s' (%s) enables more build options.")
SETTEXT(CFG_SEMAPHORES, "`%s' (%s) turns new signals built before 1975 into semaphore signals.")
SETTEXT(CFG_MOREHOTKEYS, "`%s' (%s) enables new hotkeys.")
SETTEXT(CFG_MANYTREES, "`%s' (%s) allows planting many trees at once.")
SETTEXT(CFG_MORECURRENCIES,"`%s' (%s) enables more currencies and the Euro.")
SETTEXT(CFG_MANCONVERT,"`%s' (%s) allows manual track type conversion by placing new tracks over existing tracks.")
SETTEXT(CFG_NEWAGERATING, "`%s' (%s) makes station ratings more tolerant to vehicle ages.  Now wagons can be up to 21 instead of 3 years old.")
SETTEXT(CFG_ENHANCEGUI,"`%s' (%s) enhances the user interface.  Change the settings from the entry in TTD's toolbox menu.")
SETTEXT(CFG_TOWNGROWTHRATEMODE, "`%s' (%s) makes it possible to define rules for the calculation of the growth rate for towns.  Mode: 0 - TTD original, 1 - TTD extended, 2 - custom.  See the docs for more information.")
SETTEXT(CFG_TOWNGROWTHRATEMIN, "`%s' (%s) defines the minimum growth rate of towns, in new houses per century.  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TOWNGROWTHRATEMAX, "`%s' (%s) defines the maximum growth rate of towns, in new houses per century.  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRACTSTATIONEXIST, "`%s' (%s) defines how much the existence of active stations increases the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRACTSTATIONS, "`%s' (%s) defines how much each active station increases the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRACTSTATIONSWEIGHT, "`%s' (%s) defines how effectively active stations contribute to the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRPASSOUTWEIGHT, "`%s' (%s) defines how effectively transported passengers contribute to the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRMAILOUTWEIGHT, "`%s' (%s) defines how effectively transported mail contributes to the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRPASSINMAX, "`%s' (%s) defines the maximum number of incoming passengers that can affect growth of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRPASSINWEIGHT, "`%s' (%s) defines how effectively incoming passengers contribute to the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRMAILINOPTIM, "`%s' (%s) defines the optimum population per each 2 bags of incoming mail (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRMAILINWEIGHT, "`%s' (%s) defines how effectively incoming mail contributes to the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRGOODSINOPTIM, "`%s' (%s) defines the optimum population per each 2 crates of incoming goods (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRGOODSINWEIGHT, "`%s' (%s) defines how effectively incoming goods contribute to the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRFOODINMIN, "`%s' (%s) defines the minimum food requirement of towns in snow-covered or desert areas, in population per 2 tons of incoming food (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRFOODINOPTIM, "`%s' (%s) defines the optimum population per each 2 tons of incoming food (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRFOODINWEIGHT, "`%s' (%s) defines how effectively incoming food contributes to the growth rate of a town (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRWATERINMIN, "`%s' (%s) defines the minimum water requirement of towns in desert areas, in population per 2 tons (2,000 liters) of incoming water (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRWATERINOPTIM, "`%s' (%s) defines the optimum population per each 2 tons (2,000 liters) of incoming water in the sub-tropical climate (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRWATERINWEIGHT, "`%s' (%s) defines how effectively incoming water contributes to the growth rate of a town in the sub-tropical climate (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRSWEETSINOPTIM, "`%s' (%s) defines the optimum population per each 2 bags of incoming candy (sweets) in the toyland climate (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRSWEETSINWEIGHT, "`%s' (%s) defines how effectively incoming candy (sweets) contributes to the growth rate of a town in the toyland climate (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRFIZZYDRINKSINOPTIM, "`%s' (%s) defines the optimum population per each 2 incoming fizzy drinks in the toyland climate (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRFIZZYDRINKSINWEIGHT, "`%s' (%s) defines how effectively incoming fizzy drinks contribute to the growth rate of a town in the toyland climate (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRTOWNSIZEBASE, "`%s' (%s) defines the base number of town buildings for the calculation involving `tgrtownsizefactor' (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TGRTOWNSIZEFACTOR, "`%s' (%s) defines how much the size of a town influences its growth rate (see the docs for more information).  Active only if `towngrowthratemode' is set to 2.  Range %ld..%ld.  Default %ld (i.e. 25%% influence).")
SETTEXT(CFG_TOWNMINPOPULATIONSNOW, "`%s' (%s) defines the minimum population to which towns in snow-covered areas can grow even without food supplies.  Active if `towngrowthratemode', `towngrowthlimit' or `generalfixes' is enabled.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TOWNMINPOPULATIONDESERT, "`%s' (%s) defines the minimum population to which towns in desert areas can grow even without food and water supplies.  Active if `towngrowthratemode', `towngrowthlimit' or `generalfixes' is enabled.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_MORETOWNSTATS, "With `%s' (%s) additional statistics are displayed in town information windows.")
SETTEXT(CFG_BUILDONSLOPES, "`%s' (%s) makes it possible to build tracks, roads and stations on sloped land, on a foundation like houses.")
SETTEXT(CFG_BUILDONCOASTS, "`%s' (%s) makes it possible to build on coasts or riverbanks without having to use the dynamite tool first.")
SETTEXT(CFG_TRACKTYPECOSTDIFF, "`%s' (%s) makes different track types have different cost.")
SETTEXT(CFG_EXPERIMENTALFEATURES, "`%s' (%s) enables the latest experimental features.")
SETTEXT(CFG_PLANESPEED, "`%s' (%s) makes planes fly at up to their indicated speed, not a quarter thereof, and reduces speed to 5/8 in case of a breakdown.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_FASTWAGONSELL, "`%s' (%s) allows faster selling of trains with the 'Ctrl' key.")
SETTEXT(CFG_NEWRVCRASH, "`%s' (%s) changes train/road vehicle crashes.  1 makes the train break down after the crash; 2 disables train/road vehicle crashes at all.  Default 1.")
SETTEXT(CFG_STABLEINDUSTRY, "`%s' (%s) prevents industries from closing down if Economy is set to Steady in Difficulty settings.")
SETTEXT(CFG_NEWPERF, "`%s' (%s) applies a more reasonable performance calculation regarding vehicle profits.")
SETTEXT(CFG_SORTVEHLIST, "`%s' (%s) sorts vehicles in vehicle list windows. The parameter sets how much time elapses between two updates. Lower settings requre more CPU time, but keep the list more up-to date. The setting of 10 means approximately a TTD day. Range %ld..%ld. Default %ld.")
SETTEXT(CFG_NEWSPAPERCOLOUR, "`%s' (%s) changes newspapers to colour in the given year.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_SHAREDORDERS, "`%s' (%s) allows shared or copied orders.")
SETTEXT(CFG_SHOWPROFITINLIST, "`%s' (%s) shows colour-coded profit in the list of vehicles.")
SETTEXT(CFG_MORESTEAM, "`%s' (%s) shows more (or fewer) steam plumes. Parameter has two digits, first for length of steam plume, second for frequency, with 2 being TTD's default.  Adding/subtracting one doubles/halves the length or frequency.  Range %02lx..%02lx.  Default %02lx.")
SETTEXT(CFG_ABANDONEDROADS, "`%s' (%s) makes roads lose their owner if they aren't used for a period of time, so you can remove unused roads if they're in the way. You also get the ownership of unowned roads if your vehicles use them. In mode 0, all roads lose their owners, in mode 1, roads near towns are taken over by the towns if their aren't used for a while, in mode 2 they're taken over instantly.")
SETTEXT(CFG_NEWSTATIONS, "`%s' (%s) enables new station graphics.")
SETTEXT(CFG_BUILDWHILEPAUSED, "`%s' (%s) enables all construction options even when the game is paused.")
SETTEXT(CFG_TRAINLOSTTIME, "`%s' (%s) gives a warning about lost trains after the given number of days.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_RVLOSTTIME, "`%s' (%s) gives a warning about lost road vehicles after the given number of days.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_SHIPLOSTTIME, "`%s' (%s) gives a warning about lost ships after the given number of days.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_AIRCRAFTLOSTTIME, "`%s' (%s) gives a warning about lost aircraft after the given number of days.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_MAPREFRESH, "`%s' (%s) overrides the frequency TTD updates the map window.  Lower numbers mean faster refresh and more CPU usage.  TTD's default is 64.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_NETWORKTIMEOUT, "`%s' (%s) disconnects a network game if there is no response for the given number of seconds.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_TOYLANDFEATURES, "`%s' (%s) enables landscape features that are normally disabled in random games in the toyland climate, such as lighthouses.")
SETTEXT(CFG_STRETCHWINDOW, "`%s' (%s) stretches the TTD window to this horizontal size in pixels (only for the Windows version of TTD in windowed mode).  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_CANALS, "`%s' (%s) allows building canals and locks using the `buy land' tool from the dock construction menu.")
SETTEXT(CFG_FREIGHTTRAINS, "`%s' (%s) multiplies the cargo carried by cargo trains with the given factor, to simulate very long freight trains.  This only affects train acceleration, the trains do not actually transport more.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_GAMESPEED, "`%s' (%s) Makes the gamespeed changeable. This requires the hotkeys patch. Press 'q' to speed up the game by a factor 2 (to a max of 8x speed) and 'w' to slow it down.  Parameter is the initial setting.  Range %ld..%ld.  Default %ld.")
SETTEXT(CFG_HIGHERBRIDGES, "`%s' (%s) allows building of higher bridges.")
SETTEXT(CFG_NEWGRFCFG, "`%s' (%s) chooses the configuration file for new graphics sets.")
SETTEXT(CFG_MOUSEWHEEL, "`%s' (%s) enables using the mouse wheel in the Windows version.")
SETTEXT(CFG_MOREWINDOWS, "`%s' (%s) allows more windows to be open on the screen. TTD's default is 10, but 3 slots are always occupied (main toolbar, main view, status bar), so the actual maximum count is 7. Drop-down menus and news messages count as windows as well. Range %ld..%ld. Default %ld.")
SETTEXT(CFG_ENHANCEDDIFFICULTYSETTINGS, "'%s' (%s) makes it possible to select 'none' for the number of industries in the difficulty settings.")
SETTEXT(CFG_NEWBRIDGES, "`%s' (%s) enables new graphics for bridges.")
SETTEXT(CFG_NEWHOUSES, "`%s' (%s) activates new town building types with new graphics.")
SETTEXT(CFG_NEWTOWNNAMES, "`%s' (%s) allows adding new town name styles for random games via new grf files.")
SETTEXT(CFG_MOREANIMATION, "`%s' (%s) allows increasing the number of tiles that can be animated. TTD's default is 256. Range %ld..%ld. Default %ld.")
SETTEXT(CFG_NEWSHISTORY, "`%s' (%s) enables collecting and displaying of news history.")
SETTEXT(CFG_WAGONSPEEDLIMITS, "`%s' (%s) enables speed limits for train wagons.")
SETTEXT(CFG_PATHBASEDSIGNALLING, "`%s' (%s) enables path based signalling. Before enabling it PLEASE read the manual, this feature is somewhat difficult to use correctly.")
SETTEXT(CFG_CUSTOMBRIDGEHEADS, "`%s' (%s) custom bridge heads.")
SETTEXT(CFG_TOWNBUILDNOROADS, "`%s' (%s) towns build no roads.")
SETTEXT(CFG_NEWCARGODISTRIBUTION, "`%s' (%s) enhanced cargo distribution.")
SETTEXT(CFG_WINDOWSNAP, "`%s' (%s) let windows snap together. Range %ld..%ld. Default %ld.")
SETTEXT(CFG_RESOLUTIONWIDTH, "`%s' (%s) enables and sets the width of the resolution patch.")
SETTEXT(CFG_RESOLUTIONHEIGHT, "`%s' (%s) enables and sets the height of the resolution patch.")
SETTEXT(CFG_AICHOOSECHANCES, "`%s' (%s) specify which chances to use when the ai decides what to build next (chance of building a ship route is 1-railchance-rvchance-airchance).")
SETTEXT(CFG_AIBUILDRAILCHANCE, "`%s' (%s) the chance that the ai will build a rail-route when it wants to build a new route. Range %ld..%ld, 0=0%%, 65535=100%%. Default %ld.")
SETTEXT(CFG_AIBUILDRVCHANCE, "`%s' (%s) the chance that the ai will build a rv-route when it wants to build a new route. Range %ld..%ld, 0=0%%, 65535=100%%. Default %ld.")
SETTEXT(CFG_AIBUILDAIRCHANCE, "`%s' (%s) the chance that the ai will build a air-route when it wants to build a new route. Range %ld..%ld, 0=0%%, 65535=100%%. Default %ld.")
SETTEXT(CFG_NEWINDUSTRIES, "`%s' (%s) enables support for new industry types.")
SETTEXT(CFG_LOCOMOTIONGUI, "`%s' (%s) enable the new locomotion style gui.")
SETTEXT(CFG_FIFOLOADING, "`%s' (%s) enable FIFO loading.")
SETTEXT(CFG_TEMPSNOWLINE, "`%s' (%s) enables snow line on temperate (needs an appropriate GRF file to actually show snow)")
SETTEXT(CFG_TOWNROADBRANCHPROB, "`%s' (%s) changes the probability of a town building a road branch. 0 means almost no branches, 65535 means branch everywhere possible. TTD's default is 26214. Range %ld..%ld. Default %ld.")
SETTEXT(CFG_NEWCARGOS, "`%s' (%s) enables support for new cargo types.")
SETTEXT(CFG_ENHMULTI, "`%s' (%s) enhances multiplayer games by allowing more human players.")
SETTEXT(CFG_ONEWAYROADS, "`%s' (%s) enables one-way roads")
SETTEXT(CFG_NEWSOUNDS, "`%s' (%s) allows adding new sounds to the game via custom GRF files.")
SETTEXT(CFG_IRRSTATIONS, "`%s' (%s) allows to build station in irregular forms.")
SETTEXT(CFG_MORESTATS, "`%s' (%s) enables collection of more statistics (only works if enhancegui is also enabled).")
SETTEXT(CFG_AUTOREPLACE, "`%s' (%s) upgrades vehicles to the best available new type, with the given minimum reliability in percent.  Range 1..100, default 80.")
SETTEXT(CFG_AUTOSLOPE, "`%s' (%s) allows to terraform without removeing structure.")
SETTEXT(CFG_FOLLOWVEHICLE, "`%s' (%s) allows the main view to follow a vehicle with a right mouse click on the Center View button in the vehicles window.")
SETTEXT(CFG_TRAMS, "`%s' (%s) allows trams to be built.")
SETTEXT(CFG_ENHANCETUNNELS, "`%s' (%s) allows to build track on top of tunnel entrances")
SETTEXT(CFG_FORCEGAMEOPTIONS, "`%s' (%s) allows you to force game options.")
SETTEXT(CFG_SHORTRVS, "`%s' (%s) enable shortened (or lengthened) RVs")
SETTEXT(CFG_ARTICULATEDRVS, "`%s' (%s) enable articulated RVs")
SETTEXT(CFG_NEWAIRPORTS, "`%s' (%s) allows using new airport types supplied by GRFs")
SETTEXT(CFG_NEWROUTES, "`%s' (%s) allows the changing of rails and roads though GRF files")
SETTEXT(CFG_CLONETRAIN, "`%s' (%s) allows the cloning of a train through the depot window.")
SETTEXT(CFG_TRACERESTRICT, "%s (%s) enables train routetracing to be restricted according to user criteria")
SETTEXT(CFG_STATIONSIZE, "%s (%s) changes the maximum railway station size to the specified value, note stations are still limited by the spread switch. Range 1..255 default 255. Options: on/off/number")
SETTEXT(CFG_ADJSTATIONS, "%s (%s) allows new station facilities to be merged to any station in range, even if it is adjacent to an existing station.")
SETTEXT(CFG_NEWSIGNALS, "`%s' (%s) enables new graphics for signals.")
SETTEXT(CFG_NEWOBJECTS, "`%s' (%s) enables new objects.")
SETTEXT(CFG_VRUNCOSTS, "`%s' (%s) enables grfs to have variable running costs for vehicles (no warnings will be given when the costs change).")
SETTEXT(CFG_NOTRANSTREES, "`%s' (%s) make trees completely invisible in transparent buildings mode.")
SETTEXT(CFG_PSIGNALS, "`%s' (%s) allows signals states to be controlled by user criteria, requires presignals")
SETTEXT(CFG_TSIGNALS, "`%s' (%s) allows PBS reservations the opposite way through selected one-way signals, requires PBS")

//----------------------------------------------------
//   SWITCH DISPLAY ('-v')
//----------------------------------------------------

// Wait for a key before displaying the switches
SETTEXT(LANG_SWWAITFORKEY, "\nPress Enter to run TTD, Escape to abort, or any other key to show the settings.")

// Introduction
SETTEXT(LANG_SHOWSWITCHINTRO, "    Switch settings:   (%c enabled, %c disabled)\n")

// Five characters: vertical line for the table; enabled switch; disabled switch;
// table heading; table heading column separator.
SETTEXT(LANG_SWTABLEVERCHAR, "³*úÄÂ")

// 1-way and 2-way captions after "New train wait time on red signals"
SETTEXT(LANG_SWONEWAY, "One-way: ")
SETTEXT(LANG_SWTWOWAY, "Two-way: ")

// Train wait time is either in days or infinite
SETTEXT(LANG_TIMEDAYS, "%d day(s)")
SETTEXT(LANG_INFINITETIME, "infinite")

// Shows the keys to scroll the verbose switch table
SETTEXT(LANG_SCROLLKEYS, " Keys: Up Down PgUp PgDown Home End ")

// ... and to abort TTDPatch
SETTEXT(LANG_SCROLLABORTKEY, " Escape = abort ")

// Shows the load options for ttdload.  %s is the given parameters to be passed to ttdload
SETTEXT(LANG_SWSHOWLOAD, "Enter/Space = run \"TTDLOAD %s\"")

SETTEXT(LANG_SWABORTLOAD, "\nProgram load aborted at user request.\n")


//---------------------------------------
//  STARTUP AND REPORTING
//---------------------------------------

// Internal error in TTDPatch (%d is error number)
SETTEXT(LANG_INTERNALERROR, "*** Internal TTDPatch error #%d ***\n")

// Error fixing the Windows version HDPath registry entry
SETTEXT(LANG_REGISTRYERROR, "TTD is not installed properly (registry error %d)\n")

// Trying no-registry file
SETTEXT(LANG_TRYINGNOREGIST, "Trying no-registry information from %s\n")

// no-registry file failed
SETTEXT(LANG_NOREGISTFAILED, "No-registry information not available.\n")

// DOS reports not enough memory available to start TTD
SETTEXT(LANG_NOTENOUGHMEMTTD, "Not enough memory available to start TTD, need %d KB more.\n")

// Other out-of-memory messages
// %s is a function or variable name to identify where the memory allocation failed
SETTEXT(LANG_NOTENOUGHMEM, "%s: Not enough memory available, need %d KB more.\n")

// Swapping TTDPatch out
SETTEXT(LANG_SWAPPING, "Swapping out.\n")

// Just before running ttdload, show this.
// 1st %s is ttdload.ovl, then %s is a space if there are options,
// and the 3rd %s contains the options
SETTEXT(LANG_RUNTTDLOAD, "Starting %s%s%s\n")

// Error executing ttdload.  1st %s is ttdload.ovl, 2nd %s is the error message from the OS
SETTEXT(LANG_RUNERROR, "Couldn't execute %s: %s\n")

// Failed to create the new process for ttdloadw.ovl
SETTEXT(LANG_CRPROCESSFAIL, "Create process failed")

// Interprocess communication error: TTDPatchW seems to be already running
SETTEXT(LANG_IPCEXISTS, "Another instance of TTDPatch is already running!\n")

// Failed to convert language strings to Unicode
SETTEXT(LANG_STRINGCONVFAIL, "Error while preparing TTDPatch data!\n")

// Show the result after after running, %s is one of the following strings
SETTEXT(LANG_RUNRESULT, "Result: [%s]\n")
SETTEXT(LANG_RUNRESULTOK, "OK")
SETTEXT(LANG_RUNRESULTERROR, "Error!")


//---------------------------------------
//  MESSAGES DISPLAYED BY TTDLOAD
//---------------------------------------

// Messages in this category will have "TTDPatch: " prefixed and "\r\n" suffixed
// when displayed by the DOS version.

// Out of memory (in protected mode)
SETTEXT(LANG_PMOUTOFMEMORY, "Not enough free memory!")

// Interprocess communication failed (WinTTDX only)
SETTEXT(LANG_PMIPCERROR, "Interprocess communication error")
