#!/usr/bin/perl -nl
# Generate names of bit flag bits
#
# Input: bitnames.ah   Output: bitnames.h
#
use strict;
use warnings;

our %bitid;
BEGIN {
print "// This file is autogenerated. DO NOT EDIT.";
print "// Edit bitnames.ah or perl/bitnames.pl instead.\n";
print "";
print "#ifndef NOSWITCHLIST";

#%bitid = map { 1 << $_ => $_ } 0..31;
#$bitid{1} = "0 but true";
#print STDERR "$_ -> $bitid{$_}" for keys %bitid;
}

our $bitswitch;
our @bits;
our @bitswitches;
our @numbits;
our @allbits;

y/\r\n//d;

next if m#//.*defbit#;	# ignored commented out defbit instructions

my $desc;
$desc=$1 if s#//\s*(.*)##;

#if (m#//\s*BITFLAGS\s*(\w+)#) {
if (/defbitvar\s*(\w+)/) {
	#print STDERR "Start flags for $1";
	$bitswitch = $1;
	@bits = ();
	push @bitswitches, lc $1;
	next;
}

next unless $bitswitch;

#if (m#//\s*ENDBITFLAGS#) {
if (/enddefbits/) {
	#print STDERR "Flags done for $bitswitch";
	print "const char *${bitswitch}_bitnames[] = {";
	print "\t", $_->[0] ? qq("$_->[0]") : qq{"(reserved)"}, ","
		# ', "', $_->[1] || "(reserved)", '",'
		 for @bits;
	print "\tNULL,"; #, NULL,";
	print "};\n";
	$bitswitch = undef;
	push @numbits, scalar @bits;
	next;
}

#my ($id,$val,$desc)=m#%define\s+(\w+)\s+(\w+)\s*//\s*(.*)#;
my ($id,$bit)=m/defbit\s*(\w+)\s*,\s*(\d+)/;

die "Invalid bit definition (line $.):\n$_" unless $id && defined($bit) && $desc;

#print STDERR "Got line $id/$val/$desc";

# handle binary,octal,hexadecimal notation
$bit = oct($bit) if $bit =~ /^0/;

s/.*?_// for $id;
#my ($prefix,$name) = split /_/, $id, 2;

#print STDERR "Is $name/$val";
#my $bit = $bitid{0+$val} or die "Invalid number `$val' (line $.)";

die "bitnames.ah:$.: .$id wants bit number $bit already taken by .$bits[$bit][0].\n" if $bits[$bit];
$bits[$bit] = [ lc $id, $desc ];

push @allbits, [ lc $id, $bit, $#bitswitches ];

END {
	print "const char **bitnames[] = {";
	print "\t${_}_bitnames," for @bitswitches;
	print "};";
	print "#endif";
	print "";
	print "#define BITSWITCH_$bitswitches[$_] $_" for 0..$#bitswitches;
	print "#define BITSWITCHNUM_DEF ", scalar @bitswitches;
	print "\n#ifdef WANTBITSWITCHNAMES";
	print "const char *bitswitchnames[] = {";
	print qq(\t"$_",) for @bitswitches;
	print "};";
	print "const int numbits[] = { ", map("$_, ", @numbits), "};";
	print "#endif";
	print "";
	print "#ifdef WANTBITNUMS";
	print qq(\t#define $_->[0]_NUM $_->[1]\n\t#define $_->[0]_SWITCH $_->[2])
		for @allbits;
	print "#endif"
}
